### PR TITLE
Normalizing NED parameters 

### PR DESCRIPTION
**Pull request by Naphann**
Currently there is no naming convention used in quisp NED files. I propose normalizing the convention to snake_case for parameters to be the same as C++ variable name convention we are using.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)

### CODE REVIEW

**Comment by zigen** [comment]
e2e-test failed
> <!> Error: Cannot assign '0 By default the ratio is 1:1:1' to parameter 'Realistic_Layer2_Simple_MIM_MM_5km.EndNode1[0].quantum_port_receiver$o[0].channel.channel_x_error_rate': syntax error -- at /__w/quisp/quisp/quisp/networks/test.ini:17, at /__w/quisp/quisp/quisp/networks/topology_realistic_layer2_experiments.ned:233 -- in channel (quisp::channels::QuantumChannel) Realistic_Layer2_Simple_MIM_MM_5km.EndNode1[0].quantum_port_receiver$o[0].channel (id=14), during network setup

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 9 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: 9 of 64 files reviewed, 2 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/two_node_purification` line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH7m8X_2-kEuqRK1fTQ:-NH7m8X_2-kEuqRK1fTR:b-1674ap) ([raw file](https://github.com/sfc-aqua/quisp/blob/d4de0f1ee6516fdbf39003af6d1027d8ca2c8242/quisp/two_node_purification#L1)):*
> ```
> EndNode1<-->QuantumChannel{cost=0.20278;distance=10km;fidelity=1;bellpair_per_sec=4.93146;tomography_time=15.614030451942;tomography_measurements=77;actual_meas=77; GOD_clean_pair_total=77; GOD_X_pair_total=0; GOD_Y_pair_total=0; GOD_Z_pair_total=0;}<-->EndNode2; F=1; X=0; Z=2.77556e-17; Y=0
> ```

This seems to be the result file. We should add some ext for the result files to ignore it.
___
*[`quisp/two_node_purification_dm` line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH7mUk7DUZOI4c1Wape:-NH7mUk7DUZOI4c1Wapf:b-g1joxq) ([raw file](https://github.com/sfc-aqua/quisp/blob/d4de0f1ee6516fdbf39003af6d1027d8ca2c8242/quisp/two_node_purification_dm#L1)):*
> ```
> EndNode1<--->EndNode2
> ```

This is also a density matrix result file. do you keep it intentionally?

**Review by zigen — COMMENTED** [review]
> Reviewed 36 of 64 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: 45 of 64 files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
> Reviewed 19 of 64 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by Naphann — COMMENTED** [review]
I tried to fix it. It still fails ... let me retry again

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451#-:-NH8-2Cn8cArjYAWYzyv:b-unohcc)* status: 48 of 67 files reviewed, all discussions resolved (waiting on @res6idue and @zigen)

___
*[`quisp/two_node_purification` line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH7m8X_2-kEuqRK1fTQ:-NH8--GG6pOKdzJIP_0D:b2nign6) ([raw file](https://github.com/sfc-aqua/quisp/blob/d4de0f1ee6516fdbf39003af6d1027d8ca2c8242/quisp/two_node_purification#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

This seems to be the result file. We should add some ext for the result files to ignore it.
</blockquote></details>

yes
___
*[`quisp/two_node_purification_dm` line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH7mUk7DUZOI4c1Wape:-NH7zxHY-rZSQH6nZZVV:b-pvh45y) ([raw file](https://github.com/sfc-aqua/quisp/blob/d4de0f1ee6516fdbf39003af6d1027d8ca2c8242/quisp/two_node_purification_dm#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

This is also a density matrix result file. do you keep it intentionally?
</blockquote></details>

no, I will remove it

**Review by zigen — APPROVED** [review]
> Reviewed 18 of 19 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: all files reviewed, 4 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/networks/test.ini` line 17 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OC7ZEe9A6OnPw8X1:-NH8OC7ZEe9A6OnPw8X2:b848itj) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L17)):*
> ```INI
> # Error on optical qubit in a channel
> **.channel_loss_rate = 0 # per km. 1 - 10^(-0.2/10)
> **.channel_x_error_rate = 0 By default the ratio is 1:1:1
> ```

still there...
___
*[`quisp/networks/test.ini` line 71 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OEzp6L9uzXdCWZ_o:-NH8OEzp6L9uzXdCWZ_p:bm1ehj8) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L71)):*
> ```INI
> **.memory_x_error_rate = 0
> **.memory_y_error_rate = 0
> **.memory_z_error_rate = 0 By default the ratio is 1:1:1
> ```

also here
___
*[`quisp/networks/test.ini` line 97 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OGhX7C5LkCvpjRgy:-NH8OGhX7C5LkCvpjRgz:bb7hf91) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L97)):*
> ```INI
> # Expected Outcome: High X error rate ~0.5
> **.tomography_output_filename = "Test1"
> **.channel_x_error_rate = 0.5 By default the ratio is 1:1:1
> ```

here
___
*[`quisp/networks/test.ini` line 135 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OIKj9d67IIt01uZw:-NH8OIKj9d67IIt01uZx:bb7hf91) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L135)):*
> ```INI
> # Expected Outcome: High Z error rate ~0.5
> **.tomography_output_filename = "Test6"
> **.memory_z_error_rate = 0.5 By default the ratio is 1:1:1
> ```

here

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: 38 of 67 files reviewed, 4 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/networks/test.ini` line 17 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OC7ZEe9A6OnPw8X1:-NH8XyF2EbJoyZgQQQ3c:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L17)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

still there...
</blockquote></details>

Done.
___
*[`quisp/networks/test.ini` line 71 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OEzp6L9uzXdCWZ_o:-NH8Xygt0nY6YmIJSDob:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L71)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

also here
</blockquote></details>

Done.
___
*[`quisp/networks/test.ini` line 97 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OGhX7C5LkCvpjRgy:-NH8XzCk2fmzXTUqHjt4:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L97)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.
___
*[`quisp/networks/test.ini` line 135 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/451#-NH8OIKj9d67IIt01uZw:-NH8XzeN7DgVk74CUeRA:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/d537b2974c4c422ed1d60379b729c9b45c4b12f4/quisp/networks/test.ini#L135)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.

**Review by zigen — APPROVED** [review]
> Reviewed 29 of 29 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/451#-:-NH8kjqe8WLPfgj8I1GZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Pull request merged**
