### PR TITLE
Introduce RuleSetGenerator

### PR DESCRIPTION
**Pull request by zigen**
this PR separates RuleSetGenerator from ConnectionManager.

This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)

### CODE REVIEW

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 230 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4TdUeAAvRTY0WB1dk:-NO4TdUeAAvRTY0WB1dl:b5t9pcp) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L230)):*
> ```cpp
> 
>   // This must be -1 (not found) because not interface to itself
>   int dest_qnic_address = routing_daemon->return_QNIC_address_to_destAddr(responder_addr);
> ```

I think this name is misleading. Since we are referring to our qnic address that connects to the next hop.
`qnic_address_to_next_hop` would be better? 
___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 236 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4ToU7-eFr6KVtBD22:-NO4ToU7-eFr6KVtBD23:bsfac1p) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L236)):*
> ```cpp
> 
>   // interface toward to the initiator node
>   int src_qnic_address = routing_daemon->return_QNIC_address_to_destAddr(initiator_addr);
> ```

For this one, `qnic_address_to_previous_hop`?

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h` line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4wyAe8sVRTG0x2eV_:-NO4wyAf4Ir4qcgsQKkP:b-62cdn0) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h#L13)):*
> ```objc
> class RuleSetGenerator {
>  public:
>   RuleSetGenerator(int responder_addr) : responder_addr(responder_addr) {}
> ```

Is it possible to take the address information from `par("address")` in RuleSetGenerator instead of giving it as an argument?
I don't know which is more realistic, but I would assume that this component could have access to the metadata of the node.

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h` line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4wyAe8sVRTG0x2eV_:-NO5-SYQ3yuF72mKmkTD:b-ttutbw) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h#L13)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is it possible to take the address information from `par("address")` in RuleSetGenerator instead of giving it as an argument?
I don't know which is more realistic, but I would assume that this component could have access to the metadata of the node.
</blockquote></details>

 Just curious. Is there any reason why you would want to do it like that? Since each node would have its own RuleSetGenerator and the address would never change anyway.

**Review by zigen — COMMENTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 230 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4TdUeAAvRTY0WB1dk:-NO7jkVs5na69XBfMsTn:b-3m769k) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L230)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think this name is misleading. Since we are referring to our qnic address that connects to the next hop.
`qnic_address_to_next_hop` would be better? 
</blockquote></details>

yeah but this is a responder, so, dest qnic must not exist.
wait, we don't need this to assign it anymore.
I'll refactor it.
___
*[`quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h` line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4wyAe8sVRTG0x2eV_:-NO7jH_495PmvO5SdP82:b-qip2jy) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h#L13)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

 Just curious. Is there any reason why you would want to do it like that? Since each node would have its own RuleSetGenerator and the address would never change anyway. 
</blockquote></details>

RuleSetGenerator is not a omnetpp module or component, so we need to pass it from outside.
And, this way is better for unit testing because it's pure C++ class.

**Review by Naphann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 230 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4TdUeAAvRTY0WB1dk:-NO7oDRv3XCsfOzbzbNC:b1vtjfv) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L230)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

yeah but this is a responder, so, dest qnic must not exist.
wait, we don't need this to assign it anymore.
I'll refactor it.
</blockquote></details>

you're right, this is only called at the responder.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 230 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4TdUeAAvRTY0WB1dk:-NO8-wV4EZ7kcW5yfIw_:bn2y2nz) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L230)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

you're right, this is only called at the responder. 
</blockquote></details>

this never happen if routing daemon works properly.
this should be handled by routing daemon unit tests, so I removed this part.
tatsu is working on the test.
___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 236 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4ToU7-eFr6KVtBD22:-NO80GABB_NYOnyTQFXq:b-nhoy39) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L236)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

For this one, `qnic_address_to_previous_hop`?
</blockquote></details>

now this is only one qnic addr, so I just rename it to `qnic_addr` and clarify it with a comment.
for now, this method is short and we can figure out what it is.

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 236 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4ToU7-eFr6KVtBD22:-NO81gy60y3N6QiHKlXI:b-w5fgus) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L236)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

now this is only one qnic addr, so I just rename it to `qnic_addr` and clarify it with a comment.
for now, this method is short and we can figure out what it is.
</blockquote></details>

This might be just me overthinking but depending on routing algorithm and routing table at each node, is it guarantee that the qnic to previous hop and qnic to initiator will always be the same? I’m talking about once the routing algorithm and resource management are more developed.

At end nodes (one interface) it shouldn’t matter but when you do recursive layer with possible multipath between two nodes (routers), will this be true?

**Review by Naphann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 236 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4ToU7-eFr6KVtBD22:-NO84_cd6SCxg1soiFod:b-kc1gk8) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L236)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

This might be just me overthinking but depending on routing algorithm and routing table at each node, is it guarantee that the qnic to previous hop and qnic to initiator will always be the same? I’m talking about once the routing algorithm and resource management are more developed.

At end nodes (one interface) it shouldn’t matter but when you do recursive layer with possible multipath between two nodes (routers), will this be true? 
</blockquote></details>

ah that's good point. thanks! let me check it.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 236 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4ToU7-eFr6KVtBD22:-NO864Fx-MIadc8kSpNz:b-icpngf) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L236)):*
> is it guarantee that the qnic to previous hop and qnic to initiator will always be the same?
this is not guaranteed, so it should be `previous_addr` by `req->getSrcAddr()` or path info, not `initiator_addr`.
I'll fix it.

**Review by Naphann — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by Naphann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490#-:-NODE5u33y6gnG5_u-NC:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/490)* status: all files reviewed, 2 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h` line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/490#-NO4wyAe8sVRTG0x2eV_:-NOEi71M7NB23qLX57XU:btdsfzr) ([raw file](https://github.com/sfc-aqua/quisp/blob/f0f076a20103354c3aaee2b5e4f01c89372c9062/quisp/modules/QRSA/ConnectionManager/RuleSetGenerator.h#L13)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

RuleSetGenerator is not a omnetpp module or component, so we need to pass it from outside.
And, this way is better for unit testing because it's pure C++ class.
</blockquote></details>

I see.

**Pull request merged**
