### PR TITLE
Rule implementation

### PR DESCRIPTION
**Pull request by Chibikuri**
In this PR, I'll finish functions of serialization.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)

### CODE REVIEW

**Review by rum-yasuhiro — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @rum-yasuhiro)

___
*[quisp/rules/Clause.h, line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBNpYAAjIrLWVJWx3G:-MuBNpYBAAhD78HT96pt:b-6k55pr) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Clause.h#L13)):*
> ```objc
> };
> 
> class EnoughResourceConditionClause : public BaseClause {
> ```

Condition classに入れるClauseなので、EnoughResourceClauseの方が良いと思いますがいかがでしょうか？
___
*[quisp/rules/Condition.cc, line 5 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBXBwjDw2lXc3sH7ts:-MuBXBwjDw2lXc3sH7tt:b-n3kv3h) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Condition.cc#L5)):*
> ```cpp
> #include "Clause.h"
> namespace quisp::rules {
> void Condition::addClause(std::unique_ptr<BaseClause> clause) { clauses.push_back(*clause); }
> ```

Every time `clause.push_back(*clause)` called creates copy. 
How about put pointer itself?

`clauses` type should be like: 
```
std::vector<std::unique_ptr<BaseClause>> clauses;
```

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @rum-yasuhiro)

___
*[quisp/rules/Clause.h, line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBNpYAAjIrLWVJWx3G:-MuBe_fI4Jm1pUvBYy_4:bidgi9g) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Clause.h#L13)):*
<details><summary><i>Previously, rum-yasuhiro (Yasuhiro Ohkura) wrote…</i></summary><blockquote>

Condition classに入れるClauseなので、EnoughResourceClauseの方が良いと思いますがいかがでしょうか？
</blockquote></details>

Please refer to this issue. https://github.com/sfc-aqua/quisp/issues/210
I don't know what is a good name tho.
___
*[quisp/rules/Condition.cc, line 5 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBXBwjDw2lXc3sH7ts:-MuBfKI_1iUZAFjKf4Za:b-633e5i) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Condition.cc#L5)):*
<details><summary><i>Previously, rum-yasuhiro (Yasuhiro Ohkura) wrote…</i></summary><blockquote>

Every time `clause.push_back(*clause)` called creates copy. 
How about put pointer itself?

`clauses` type should be like: 
```
std::vector<std::unique_ptr<BaseClause>> clauses;
```
</blockquote></details>

That's exactly what I'm doing here, isn't it?
This is the vector implementation and it's a vector of BaseClause unique pointer. 
https://github.com/sfc-aqua/quisp/blob/03c126001e526820efbdf56ab6e5f2510b67af9d/quisp/rules/Condition.h#L12
I'm using `move` here. So just moving ownership from one place to another.
https://en.cppreference.com/w/cpp/utility/move

**Review by rum-yasuhiro — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @rum-yasuhiro)

___
*[quisp/rules/Clause.h, line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBNpYAAjIrLWVJWx3G:-MuENzX_E3AYv1cJ2L0J:bgafefe) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Clause.h#L13)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Please refer to this issue. https://github.com/sfc-aqua/quisp/issues/210
I don't know what is a good name tho.
</blockquote></details>

Okay, I see what you're thinking.
`EnoughResourceConditionClause ` seems fine.
Hmm ... Other possible is, I don't know, but just `EnoughResourceCondition`  and `SomethingAction` ?

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @rum-yasuhiro)

___
*[quisp/rules/Clause.h, line 13 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuBNpYAAjIrLWVJWx3G:-MuFTPSi8YXaKoFUmzGM:b-huqkxy) ([raw file](https://github.com/sfc-aqua/quisp/blob/d93b025ecd5e2ca25c8e62f4e0b540e19f88f95f/quisp/rules/Clause.h#L13)):*
<details><summary><i>Previously, rum-yasuhiro (Yasuhiro Ohkura) wrote…</i></summary><blockquote>

Okay, I see what you're thinking.
`EnoughResourceConditionClause ` seems fine.
Hmm ... Other possible is, I don't know, but just `EnoughResourceCondition`  and `SomethingAction` ?
</blockquote></details>

Possibly. We can do it in another PR.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1, 7 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @rum-yasuhiro)

___
*[quisp/rules/Condition.cc, line 2 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuIwfX06c2MUY4JPXAR:-MuIwfX06c2MUY4JPXAS:b-15qtyk) ([raw file](https://github.com/sfc-aqua/quisp/blob/03c126001e526820efbdf56ab6e5f2510b67af9d/quisp/rules/Condition.cc#L2)):*
> ```cpp
> #include "Condition.h"
> #include <memory>
> ```

we don't need to include <memory> and "Clause.h" because we already included it in "Condition.h"
___
*[quisp/rules/RuleSet.cc, line 17 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuIxKQW5AeWHgweiCM0:-MuIxKQW5AeWHgweiCM1:b290e28) ([raw file](https://github.com/sfc-aqua/quisp/blob/03c126001e526820efbdf56ab6e5f2510b67af9d/quisp/rules/RuleSet.cc#L17)):*
> ```cpp
>   rule->parent_ruleset_id = ruleset_id;
>   rules.push_back(std::move(rule));
>   Rule *raw_pointer = rules.at(rules.size() - 1).get();
> ```

you can get and store the raw pointer before moving the rule, then you don't need to call `rules.at()`, like:
```cpp
  rule->parent_ruleset_id = ruleset_id;
  Rule *raw_ptr = rule.get();
  rules.push_back(std::move(rule));
  return raw_ptr;

```

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: all files reviewed, 3 unresolved discussions (waiting on @rum-yasuhiro and @zigen)

___
*[quisp/rules/Condition.cc, line 2 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuIwfX06c2MUY4JPXAR:-MuJiOG-3w5nOnAme9xB:b-o419a3) ([raw file](https://github.com/sfc-aqua/quisp/blob/03c126001e526820efbdf56ab6e5f2510b67af9d/quisp/rules/Condition.cc#L2)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we don't need to include <memory> and "Clause.h" because we already included it in "Condition.h"
</blockquote></details>

Right, fixed.
___
*[quisp/rules/RuleSet.cc, line 17 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/363#-MuIxKQW5AeWHgweiCM0:-MuJj4CH-SpbfCIxpbIn:buuhrbq) ([raw file](https://github.com/sfc-aqua/quisp/blob/03c126001e526820efbdf56ab6e5f2510b67af9d/quisp/rules/RuleSet.cc#L17)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you can get and store the raw pointer before moving the rule, then you don't need to call `rules.at()`, like:
```cpp
  rule->parent_ruleset_id = ruleset_id;
  Rule *raw_ptr = rule.get();
  rules.push_back(std::move(rule));
  return raw_ptr;

```
</blockquote></details>

True. Fixed it thanks!

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363#-:-MuJkvmZ2z-_L4RXkEFD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rum-yasuhiro)

**Comment by Chibikuri** [comment]
@rum-yasuhiro How about now?

**Review by rum-yasuhiro — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/363)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
