### PR TITLE
Create message transfer base action

### LINKED ISSUE #412: Separate Actions into several basis actions
**Is your feature request related to a problem? Please describe.**
All actions should be composed of several atomic actions so that user can combine several actions into single set of actions.
This will also allows developer to make a new actions easily. 

**Describe the solution you'd like**
Make one single action into several atomic base actions.

### LINKED ISSUE #417: Create a message transfer action
Create a base action to send a message from one place to another.

### PR DESCRIPTION
**Pull request by Chibikuri**
Created static functions to generate result packets.
Close #417 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

___
*[`quisp/rules/Active/actions/DoublePurifyAction_test.cc` line 218 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/415#-NArQ_p88lftiQY_k9v_:-NArQ_p88lftiQY_k9va:b-bmnwuq) ([raw file](https://github.com/sfc-aqua/quisp/blob/0f9d63e60df343744fe1903d01e87d678e7c8775/quisp/rules/Active/actions/DoublePurifyAction_test.cc#L218)):*
> ```cpp
>   EXPECT_EQ(result->getRule_id(), action->rule_id);
>   EXPECT_EQ(result->getRuleset_id(), action->ruleset_id);
>   // EXPECT_EQ(result->getEntangled_with(), qubit);
> ```

remove it because of https://github.com/sfc-aqua/quisp/issues/416
___
*[`quisp/rules/Active/actions/base/TransferMessage.h` line 7 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/415#-NArPUd1AHalh8Wei_4l:-NArPUd1AHalh8Wei_4m:b-g1gn8r) ([raw file](https://github.com/sfc-aqua/quisp/blob/0f9d63e60df343744fe1903d01e87d678e7c8775/quisp/rules/Active/actions/base/TransferMessage.h#L7)):*
> ```objc
> namespace quisp::rules::active::actions::base {
> 
> class TransferMessage : public BaseAction {
> ```

Do we need to make it a class? I don't know the detail of its design, but for now, you should use a "static method."
These are just wrappers for creating messages.

**Comment by Chibikuri** [comment]
> > Reviewed 26 of 26 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415)_ status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)
> 
> _[`quisp/rules/Active/actions/DoublePurifyAction_test.cc` line 218 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/415#-NArQ_p88lftiQY_k9v_:-NArQ_p88lftiQY_k9va:b-bmnwuq) ([raw file](https://github.com/sfc-aqua/quisp/blob/0f9d63e60df343744fe1903d01e87d678e7c8775/quisp/rules/Active/actions/DoublePurifyAction_test.cc#L218)):_
> 
> > ```c++
> >   EXPECT_EQ(result->getRule_id(), action->rule_id);
> >   EXPECT_EQ(result->getRuleset_id(), action->ruleset_id);
> >   // EXPECT_EQ(result->getEntangled_with(), qubit);
> > ```
> 
> remove it because of #416
> 
> _[`quisp/rules/Active/actions/base/TransferMessage.h` line 7 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/415#-NArPUd1AHalh8Wei_4l:-NArPUd1AHalh8Wei_4m:b-g1gn8r) ([raw file](https://github.com/sfc-aqua/quisp/blob/0f9d63e60df343744fe1903d01e87d678e7c8775/quisp/rules/Active/actions/base/TransferMessage.h#L7)):_
> 
> > ```objc
> > namespace quisp::rules::active::actions::base {
> > 
> > class TransferMessage : public BaseAction {
> > ```
> 
> Do we need to make it a class? I don't know the detail of its design, but for now, you should use a "static method." These are just wrappers for creating messages.

I'll remove the class definition here since I don't need it.

**Review by zigen — COMMENTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/415#-:-NBKcjEG8kkm5sNJEym1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
