### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by zigen**
there're tons of copy-and-pasted codes and it causes many warnings. 
this PR fix it.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/236)

### CODE REVIEW

**Comment by Chibikuri** [comment]
I still got some warnings from some modules. Should I leave them now?
Screen Shot 2021-07-05 at 17 04 38

**Comment by zigen** [comment]
yeah, I'll leave it in another PR

**Review by Naphann — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by Chibikuri — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
