### PR TITLE
Fix casting to reduce double checking the type

### PR DESCRIPTION
**Pull request by rum-yasuhiro**
Fix this issue:
https://github.com/sfc-aqua/quisp/issues/295

This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334)

### CODE REVIEW

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334#-:-MsTPLXC38WL9LlP6CVP:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @zigen)

**Review by zigen — APPROVED** [review]
@rum-yasuhiro thanks, so far so good!
 I'm waiting for the other parts of the same fixes needed

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334#-:-MsUAjbw7p6pioLULOfx:b-qjm16u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rum-yasuhiro)

**Review by zigen — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rum-yasuhiro)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334#-:-MsrT4Gu02-JlHh__Cqz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rum-yasuhiro)

**Comment by zigen** [comment]
@rum-yasuhiro CI failed. could you check? you might need to format the code with `$ make format`

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/334#-:-Msral14B63a4k7gWAy_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rum-yasuhiro)

**Comment by zigen** [comment]
@rum-yasuhiro the PR is approved (LGTM) and now you can merge it! 🎉

**Pull request merged**
