### PR TITLE
fix wasm build

### PR DESCRIPTION
**Pull request by zigen**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/401)

### CODE REVIEW

**Review by Chibikuri — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/401#-:-N8s_xlXC4AMDyVQCiOk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Comment by zigen** [comment]
why the main workflow got errors ...

**Comment by Chibikuri** [comment]
Seems this part. https://github.com/sfc-aqua/quisp/blob/b98bfef606ab7ebf6264f398d4de68a1f5da7245/.github/workflows/main.yml#L10
Credential has been expired?

**Comment by zigen** [comment]
yeah, that part. also, I suspected and replaced the token, but it won't work.
maybe there's some change about the secrets handling in GitHub Actions?

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Comment by zigen** [comment]
finally, I set the secret `GHCR_PAT` on my repo's setting and it works.

**Pull request merged**
