### PR TITLE
Basic Traffic Generator 

### PR DESCRIPTION
**Pull request by Naphann**
This changes introduce a new way to generate traffic inside the network. While it is still basic, it is able to generate the same traffic as previous version and more. 

Changes to QNode module:
- it now has 2 additional parameters; `mass` and `isInitiator`
- when the isInitiator is set to true, it will generate traffic defined in Application module

Changes to Application module:
- It now has one new parameter; numberOfBellPairs. 
- remove redundant parameters

**How traffic is generated:**
If the `QNode.isInitiator` is set to `true` connection request will be randomly generated based on the `QNode.Application.sendIaTime` which is a volatile double and the number of Bell pairs requested will be sampled from uniform distribution (10, 100). These two value can be set in `.ini` file if default value is not to be used by users.

Destination is selected based on the mass parameter each QNode has (discrete distribution). 

**How to set parameter to get previous traffic pattern**:

1. No request at all -  set all `QNode.isInitiator` to false (this remove the need for `is_e2e_connection`)
2. One node to be initiator and one node to be responder - set initiator node `isInitiator` to true and responder node to have non-zero mass while other end nodes to have 0 mass.
3. One node to be initiator and randomly select responder - same as (2) but set mass to reflect how the responder should be select
4. All-to-all - set every `QNode.isInitiator` to true and select mass to represent how responders should be sampled
5. Number of request per simulation can be set from `QNode.Application.sendIaTime` 

Additional constraints on this PR:
- Now all simulation must have `sim-time-limit` set to non-zero value otherwise application will output error due to unable to determine how many request will be generated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/437)

### CODE REVIEW

**Comment by Naphann** [comment]
This new commit relax the sim-time-limit requirement and any simulation that doesn't have sim-time-limit set will perpetually generate traffic

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 4 of 7 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/437)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @Naphann)

___
*[`quisp/networks/quisp_tutorial.ini` line 11 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/437#-NG0PXzxELK5smp5VCbI:-NG0PXzxELK5smp5VCbJ:b-b6ju02) ([raw file](https://github.com/sfc-aqua/quisp/blob/43b056a3dd534b6170a4e076a85d8a512a5bbc49/quisp/networks/quisp_tutorial.ini#L11)):*
> ```INI
> #from topology_linear_network.ned
> network = Linear_One_MM
> sim-time-limit = 100s
> ```

I think this should be in `[Genera]` as default

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/437)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[`quisp/networks/quisp_tutorial.ini` line 11 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/437#-NG0PXzxELK5smp5VCbI:-NG0VFK62Ew7spxD1xQi:bohszml) ([raw file](https://github.com/sfc-aqua/quisp/blob/43b056a3dd534b6170a4e076a85d8a512a5bbc49/quisp/networks/quisp_tutorial.ini#L11)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think this should be in `[Genera]` as default
</blockquote></details>

Moved to `[General]`

**Review by zigen — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/437)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/437#-:-NG0VWwE8-VlF1CHElE-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
