### PR TITLE
Add application id to connection setup messages

### LINKED ISSUE #435: Connection setup and reject messages should have unique identifier
Currently, connection setup and reject messages only contain source and address and how many Bell pairs are required for the connection.

When the application is able to generate multiple request and not all of them are rejected, it will be impossible for the application to know which request got rejected and which got accepted. So the message should contain application ID or some kind of unique identifier to the connection message.

**suggested fix**:

Associate each application request with application id and put them inside the connection setup/reject message.

### PR DESCRIPTION
**Pull request by makotonakai**
## Fix
#435 

## What I have done so far

- Add application_id property to ConnectionSetupRequest, RejectConnectionSetupRequest and ConnectionSetupResponse
- Add setApplication_id / getApplication_id methods to ConnectionSetupRequest, RejectConnectionSetupRequest and ConnectionSetupResponse
- Add application_id to JsonLogger (ConnectionSetupRequest, RejectConnectionSetupRequest and ConnectionSetupResponse)

## The problem that I am currently encountering

The unit test for ConnectionManager (RespondToRequest) does not work on my local environment after I added the setApplication_id / getApplication_id, because the respondToRequest method itself creates ConnectionSetupResponse with the given application id, while the unit test creates the ConnectionSetupRequest using the (classical?) message outside the method

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 2 unresolved discussions (waiting on @makotonakai)

___
*[`quisp/messages/connection_setup_messages.msg` line 8 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4WZ07KQpA5IbnRZe:-NPQ4WZ07KQpA5IbnRZf:b7hupyu) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/messages/connection_setup_messages.msg#L8)):*
> ```
> packet ConnectionSetupRequest extends Header
> {
>     int application_id;
> ```

use `@getter(getApplicationId)` and  `@setter(setApplicationId)` for accessors name.
https://doc.omnetpp.org/omnetpp/manual/#sec:msg-defs:properties
___
*[`quisp/modules/Application/Application.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4zZb1nI9XC3z3_xp:-NPQ4zZb1nI9XC3z3_xq:b2b0gj1) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/modules/Application/Application.h#L33)):*
> ```objc
> 
>  protected:
>   int application_id;
> ```

how should we specify the application_id?

**Comment by makotonakai** [comment]
> > Reviewed 7 of 7 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)_ status: all files reviewed, 2 unresolved discussions (waiting on @makotonakai)
> 
> _[`quisp/messages/connection_setup_messages.msg` line 8 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4WZ07KQpA5IbnRZe:-NPQ4WZ07KQpA5IbnRZf:b7hupyu) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/messages/connection_setup_messages.msg#L8)):_
> 
> > ```
> > packet ConnectionSetupRequest extends Header
> > {
> >     int application_id;
> > ```
> 
> use `@getter(getApplicationId)` and `@setter(setApplicationId)` for accessors name. https://doc.omnetpp.org/omnetpp/manual/#sec:msg-defs:properties
> 
> _[`quisp/modules/Application/Application.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4zZb1nI9XC3z3_xp:-NPQ4zZb1nI9XC3z3_xq:b2b0gj1) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/modules/Application/Application.h#L33)):_
> 
> > ```objc
> >  protected:
> >   int application_id;
> > ```
> 
> how should we specify the application_id?



> > Reviewed 7 of 7 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)_ status: all files reviewed, 2 unresolved discussions (waiting on @makotonakai)
> 
> _[`quisp/messages/connection_setup_messages.msg` line 8 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4WZ07KQpA5IbnRZe:-NPQ4WZ07KQpA5IbnRZf:b7hupyu) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/messages/connection_setup_messages.msg#L8)):_
> 
> > ```
> > packet ConnectionSetupRequest extends Header
> > {
> >     int application_id;
> > ```
> 
> use `@getter(getApplicationId)` and `@setter(setApplicationId)` for accessors name. https://doc.omnetpp.org/omnetpp/manual/#sec:msg-defs:properties
> 
> _[`quisp/modules/Application/Application.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4zZb1nI9XC3z3_xp:-NPQ4zZb1nI9XC3z3_xq:b2b0gj1) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/modules/Application/Application.h#L33)):_

Roger that

> > ```objc
> >  protected:
> >   int application_id;
> > ```
> 
> how should we specify the application_id?

That's what I'm working on.  I'll add more commits if I figure that out.

**Comment by makotonakai** [comment]
> > Reviewed 5 of 5 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)_ status: all files reviewed, 3 unresolved discussions (waiting on @makotonakai)
> 
> _[`quisp/messages/connection_setup_messages.msg` line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPSEmMd11EVpM3zjUkK:-NPSEmMd11EVpM3zjUkL:bm8uoe3) ([raw file](https://github.com/sfc-aqua/quisp/blob/5e165f9535f86cce82eaea2f0998beb2f85adc70/quisp/messages/connection_setup_messages.msg#L8)):_
> 
> > ```
> > packet ConnectionSetupRequest extends Header
> > {
> >     int application_id @getter(getApplication_id) @setter(setApplication_id);
> > ```
> 
> I don't want to mix the cases (snake_case and CamelCase). so `getApplicationId` and `setApplicationId` are better. we should use easy-to-expect names. I don't want to be confused getApplicationId or getApplication_id.

Sorry, I just fixed this

**Comment by makotonakai** [comment]
> _[`quisp/modules/Application/Application.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4zZb1nI9XC3z3_xp:-NPSGHwW2kHaHMdHITxw:b-g76853) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/modules/Application/Application.h#L33)):_
> 
> Previously, makotonakai (Makoto "dave" Nakai) wrote…
> btw, do you plan to send multiple requests which have different id from one Application module in your project?
> 
Not for my project, but it would be necessary in the future, especially if some users want to simulate several applications in the same network.  I guess this can be possible if I add another id (e.g. message_id) and increment it as the number of messages increases

**Comment by makotonakai** [comment]
> _[`quisp/modules/Application/Application_test.cc` line 44 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPSF_JS3vIN3elI284M:-NPSF_JS3vIN3elI284N:bc0tpm3) ([raw file](https://github.com/sfc-aqua/quisp/blob/5e165f9535f86cce82eaea2f0998beb2f85adc70/quisp/modules/Application/Application_test.cc#L44)):_
> 
> > ```c++
> >   virtual ~AppTestTarget() { EVCB.gateDeleted(toRouterGate); }
> >   std::unordered_map<int, int> getEndNodeWeightMap() { return this->end_node_weight_map; }
> >   int getId() { return this->id; }
> > ```
> 
> do we need this? it's a public member, so we can access to it with `app->id`.

No, it's protected one, so that's why I added a function to retrieve that like the ones for other protected members.
https://github.com/makotonakai/quisp/blob/add-application-id/quisp/modules/Application/Application.h#L32

**Comment by makotonakai** [comment]
Sorry for my late replies @zigen -san

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 2 unresolved discussions (waiting on @makotonakai)

___
*[`quisp/modules/Application/Application_test.cc` line 44 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPSF_JS3vIN3elI284M:-NP_NJugB0kV11R7NFMc:b-xy3lvc) ([raw file](https://github.com/sfc-aqua/quisp/blob/5e165f9535f86cce82eaea2f0998beb2f85adc70/quisp/modules/Application/Application_test.cc#L44)):*
<details><summary><i>Previously, makotonakai (Makoto "dave" Nakai) wrote…</i></summary><blockquote>

No, it's protected one, so that's why I added a function to retrieve that like the ones for other protected members.
https://github.com/makotonakai/quisp/blob/add-application-id/quisp/modules/Application/Application.h#L32

</blockquote></details>

okay, declare `using quisp::modules::Application::id`.  then you can make it public for this class

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 2 unresolved discussions (waiting on @makotonakai)

___
*[`quisp/modules/Application/Application.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPQ4zZb1nI9XC3z3_xp:-NP_Nu6OCJAcEMSjaHwL:b-7lm34b) ([raw file](https://github.com/sfc-aqua/quisp/blob/e2e09ac5cc43b1ff0a2ae335576115b710258ec7/quisp/modules/Application/Application.h#L33)):*
<details><summary><i>Previously, makotonakai (Makoto "dave" Nakai) wrote…</i></summary><blockquote>

Not for my project, but it would be necessary in the future, especially if some users want to simulate several applications in the same network.  I guess this can be possible if I add another id (e.g. message_id) and increment it as the number of messages increases
</blockquote></details>

okay.

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @makotonakai)

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 1 unresolved discussion (waiting on @makotonakai)

___
*[`quisp/modules/Application/Application.h` line 33 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/507#-NPaXWMz6uxB3KXeCMNd:-NPaXWMz6uxB3KXeCMNe:bm0s0of) ([raw file](https://github.com/sfc-aqua/quisp/blob/5df15ffab3c8eeeafa29c290aa13f8fc55146e43/quisp/modules/Application/Application.h#L33)):*
> ```objc
> 
>  protected:
>   int id;
> ```

Could you add documentation for the `id` like how to use?
For now, this member has never been initialized, and it will confuse us later.

**Review by zigen — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 1 unresolved discussion (waiting on @makotonakai)

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507)* status: all files reviewed, 1 unresolved discussion (waiting on @makotonakai)

**Comment by makotonakai** [comment]
@zigen -san Could you tell me where the documentation is located?

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507#-:-NPflHXV90BFswXyeTKv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @makotonakai)

**Comment by makotonakai** [comment]
@zigen -san,  I need your additional approval cuz I fixed some unit tests that failed in the previous commit...

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/507#-:-NPg2AjW0wxMwB--PyfP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @makotonakai)

**Pull request merged**
