### PR TITLE
setup GitHub Actions

### PR DESCRIPTION
**Pull request by zigen**
#196 #195
- [x] run-unit-test
- [x] clang-format
- [x] clang-tidy
- [x] test.sh

for module tests, we need to fix it to work on release build because omnetpp docker image has only a release build.
So, I'll work on it in the next PR.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/247)

### CODE REVIEW

**Comment by zigen** [comment]
hmm, Travis ci might need an action.
https://travis-ci.com/github/sfc-aqua/quisp/requests

now Travis gives 10k credit to OSS projects at first and then we might need to claim it.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

but "GitHub actions" is free for the public repository, so I want to use this and it releases us from the management of these credit issues.
I'll try GitHub Actions tomorrow.
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

**Review by Chibikuri — APPROVED** [review]
I think all changes should be fine. Thanks!
:lgtm:

> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/247#-:-Mf6OTHc-wPrs16RsBHl:b-8ll7gg)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @Naphann)

**Review by Naphann — APPROVED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Naphann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/247#-:-Mf6QuKV-QXV9oJgxvlI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Comment by zigen** [comment]
Thanks for reviewing!

**Pull request merged**
