### PR TITLE
Add qubit gate error test

### PR DESCRIPTION
**Pull request by zigen**
- [x] add unit tests for 
  - `apply_single_qubit_gate_error`
  - `apply_two_qubit_gate_error`
  - `SetSingleQubitGateErrorCeilings`
  - `SetTwoQubitGateErrorCeilings`
- [x] refactor these methods
- [x] fix error rate goes infinity bug
- [x] remove useless comments  

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/240)

### CODE REVIEW

**Review by Naphann — COMMENTED** [review]
It works on my machine and the refactor looks good.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/240#-:-MePOQeH1SHy3luCh-ga:bvr0g49)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 335 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/240#-MePo1WCD9E4oKqZYr6_:-MePo1WCD9E4oKqZYr6a:b-e3g0rn) ([raw file](https://github.com/sfc-aqua/quisp/blob/58ce541ec3c959e5a2a5c1d89bc354c6e0867ae7/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L335)):*
> ```objc
>   virtual measurement_operator Random_Measurement_Basis_Selection();
>   virtual void setSingleQubitGateErrorModel(SingleGateErrorModel &model, std::string gate_name);
>   virtual TwoQubitGateErrorModel setTwoQubitGateErrorCeilings(TwoQubitGateErrorModel &model, std::string gate_name);
> ```

If you change the single qubit one, why not change this one as well? Just curious.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/240)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 335 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/240#-MePo1WCD9E4oKqZYr6_:-MePtH6395tYCjVZBupx:b-drnekm) ([raw file](https://github.com/sfc-aqua/quisp/blob/58ce541ec3c959e5a2a5c1d89bc354c6e0867ae7/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L335)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

If you change the single qubit one, why not change this one as well? Just curious.
</blockquote></details>

ah, just I forgot to fix it. I'll fix it in this PR. thanks!

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 335 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/240#-MePo1WCD9E4oKqZYr6_:-MePuuys5SJ-NGho0lKi:bhgq2sn) ([raw file](https://github.com/sfc-aqua/quisp/blob/58ce541ec3c959e5a2a5c1d89bc354c6e0867ae7/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L335)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

ah, just I forgot to fix it. I'll fix it in this PR. thanks!
</blockquote></details>

Ok, I'll approve when you push the next revision!

**Review by Naphann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
