### PR TITLE
Refactor RoutingDaemon

### PR DESCRIPTION
**Pull request by Tatzhiro**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Tatzhiro)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 32 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNi_ajH1XneiQgrkakL:-NNi_ajH1XneiQgrkakM:b-vygtbo) ([raw file](https://github.com/sfc-aqua/quisp/blob/ffaf888d6cbf5af2290863abaaba64b2fc5a2e62/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L32)):*
> ```objc
>   double calculateSecPerBellPair(cTopology::LinkOut* outgoing_link);
> 
>   void set_qrtable(cTopology* topo);
> ```

function name should be camelCase.
This method generates a quantum routing table rather than setting it.
And, the name "qrtable" is not common and not easy to understand.
So, `generateRoutingTable` seems better.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 33 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNiaj1J3L0GfNDuyPFg:-NNiaj1J3L0GfNDuyPFh:b-if0ms5) ([raw file](https://github.com/sfc-aqua/quisp/blob/ffaf888d6cbf5af2290863abaaba64b2fc5a2e62/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L33)):*
> ```objc
> 
>   void set_qrtable(cTopology* topo);
>   QNIC get_QNIC_info_of(cGate *parentModuleGate);
> ```

use camelCase name.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 99 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNib7zaAwU8mzKDFU4H:-NNib7zaAwU8mzKDFU4I:b-jpvl3c) ([raw file](https://github.com/sfc-aqua/quisp/blob/ffaf888d6cbf5af2290863abaaba64b2fc5a2e62/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L99)):*
> ```cpp
> // Calculate bell pair generation rate to use it as channel cost
> // The cost metric is taken from https://arxiv.org/abs/1206.5655
> double RoutingDaemon::calculateSecPerBellPair(cTopology::LinkOut* outgoing_link) {
> ```

if we didn't change the `outgoing_link`, it'd be better to add `const` qualifier.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 149 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNibPNE8g6QJ_g2ZyfQ:-NNibPNE8g6QJ_g2ZyfR:byppdej) ([raw file](https://github.com/sfc-aqua/quisp/blob/ffaf888d6cbf5af2290863abaaba64b2fc5a2e62/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L149)):*
> ```cpp
> 
> QNIC RoutingDaemon::get_QNIC_info_of(cGate *parentModuleGate) {
>   QNIC thisqnic;
> ```

we don't have any other qnic, so we can rename it to just `qnic`.

**Review by Tatzhiro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 99 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNib7zaAwU8mzKDFU4H:-NNiq3P35hKG2TB6gEZg:bdn990e) ([raw file](https://github.com/sfc-aqua/quisp/blob/ffaf888d6cbf5af2290863abaaba64b2fc5a2e62/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L99)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

It seems to me that `outgoing_link` is setting its member variable with setWeight function.
</blockquote></details>

Sorry I realized `outgoing_link` here is in `calculateSecPerBellPair` so you are right that I should add `const`.

**Review by zigen — CHANGES_REQUESTED** [review]
it's much better than before! 
so we want to confirm your change works properly. 
could you write unit tests for the RoutingDaemon?  

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488#-:-NNkksjl9BerTo8cr0zL:b-mxbris)* status: all files reviewed, 2 unresolved discussions (waiting on @Tatzhiro)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 151 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNkkMY-BUgAKi0L-eJQ:-NNkkMY-BUgAKi0L-eJR:b1fzlzi) ([raw file](https://github.com/sfc-aqua/quisp/blob/1cedc965a1e8d5e82ac8d305e125a3cc5dcf1e49/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L151)):*
> ```cpp
> QNIC RoutingDaemon::getQNicInfoOf(const cGate *const module_gate) {
>   QNIC qnic;
>   qnic.address = module_gate->getPreviousGate()->getOwnerModule()->par("self_qnic_address");
> ```

we can keep `module_gate->getPreviousGate()->getOwnerModule()` as variable for readability.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 152 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNkkE3o4KCDtkBcdF9H:-NNkkE3o4KCDtkBcdF9I:bk438v8) ([raw file](https://github.com/sfc-aqua/quisp/blob/1cedc965a1e8d5e82ac8d305e125a3cc5dcf1e49/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L152)):*
> ```cpp
>   QNIC qnic;
>   qnic.address = module_gate->getPreviousGate()->getOwnerModule()->par("self_qnic_address");
>   qnic.type = (QNIC_type)(int)module_gate->getPreviousGate()->getOwnerModule()->par("self_qnic_type");
> ```

it's better to use `par("self_qnic_type")->intValue()`
https://doc.omnetpp.org/omnetpp/api/classomnetpp_1_1cPar.html#a6eca1af955634a64f1a990f384894267

**Review by Tatzhiro — COMMENTED** [review]
I will work on making the unit test!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488#-:-NNo1Kzt5x0VGKGFf1WV:bqh5f8z)* status: all files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 151 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNkkMY-BUgAKi0L-eJQ:-NNo1HNC0rJ-C-YBlHVb:bsc5uw6) ([raw file](https://github.com/sfc-aqua/quisp/blob/1cedc965a1e8d5e82ac8d305e125a3cc5dcf1e49/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L151)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we can keep `module_gate->getPreviousGate()->getOwnerModule()` as variable for readability.
</blockquote></details>

I will name it `module`
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 152 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNkkE3o4KCDtkBcdF9H:-NNo1GFYCpbfV6A58Our:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/1cedc965a1e8d5e82ac8d305e125a3cc5dcf1e49/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L152)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's better to use `par("self_qnic_type")->intValue()`
https://doc.omnetpp.org/omnetpp/api/classomnetpp_1_1cPar.html#a6eca1af955634a64f1a990f384894267
</blockquote></details>

Done.

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488)* status: all files reviewed, 2 unresolved discussions (waiting on @Tatzhiro)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 152 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/488#-NNkkE3o4KCDtkBcdF9H:-NNo4EkG1vxHX62FjE2V:bo3u6zg) ([raw file](https://github.com/sfc-aqua/quisp/blob/1cedc965a1e8d5e82ac8d305e125a3cc5dcf1e49/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L152)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you forgot to push it?

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/488#-:-NOmpYiZ-k6vfdDA0Kzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tatzhiro)

**Pull request merged**
