### PR TITLE
Add Y Purification and Concept of short-live qubits (photons) using qubit pool inside backend

### LINKED ISSUE #487: Backend functionality to create a new backend qubit without specifying ID
In order to properly simulate the link level generation, entanglement swaps at the BSA node.
An ability to create a new qubit from the backend without specifying ID would be nice to have. Also maybe it's good if the qubit instance itself also stores its ID so we can delete it easily with just the qubit reference.

### PR DESCRIPTION
**Pull request by Naphann**
In this PR, 
- I add a new helper function for making Y error purification.
- remove deprecated functions in backend and in qubits
- introduce qubit pool for short-live qubits (non stationary qubits should be used as short-live)
- change the CNOT semantics from target->control to control->target 

This PR closes #487.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 26 of 32 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: 29 of 35 files reviewed, 1 unresolved discussion (waiting on @Chibikuri, @Naphann, and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 122 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NO84qoR8PoyyPAp3mma:-NO84qoR8PoyyPAp3mmb:b-oyb7h) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L122)):*
> ```cpp
> void QuantumChannel::validateParameters() {
>   if (err.error_rate < 0 || 1 < err.error_rate) {
>     throw cRuntimeError("quantum channel has invalid total error rate");
> ```

I think it's better to use `error` method because it shows which component causes the error.
or this might be useful https://doc.omnetpp.org/omnetpp/api/classomnetpp_1_1cRuntimeError.html#a82223345c6a880f377805d02e941913f

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: 29 of 35 files reviewed, 1 unresolved discussion (waiting on @Chibikuri, @res6idue, and @zigen)

___
*[`quisp/channels/QuantumChannel.cc` line 122 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NO84qoR8PoyyPAp3mma:-NO88TrL8aIV8W1ePgIR:bkfmy0e) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L122)):*
From my understanding, it already gives us information about where the error is raised. The signature with `CObject* where` is for custom object if we want to use something else.
The `error()` method specify it like this 
> Equivalent to <tt>throw cRuntimeError(<i>same argument list</i>)</tt>.

And when I test the error it does show this statement 
```
<!> Error: quantum channel has invalid total error rate -- in channel (quisp::channels::QuantumChannel) two_node_MIM.EndNode1.quantum_port$o[0].channel (id=11), during network initialization
```

**Review by zigen — APPROVED** [review]
> Reviewed 5 of 32 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 122 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NO84qoR8PoyyPAp3mma:-NO8ICAA1xvPil4jFykr:b4esupd) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L122)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

From my understanding, it already gives us information about where the error is raised. The signature with `CObject* where` is for custom object if we want to use something else.
The `error()` method specify it like this 
> Equivalent to <tt>throw cRuntimeError(<i>same argument list</i>)</tt>.

And when I test the error it does show this statement 
```
<!> Error: quantum channel has invalid total error rate -- in channel (quisp::channels::QuantumChannel) two_node_MIM.EndNode1.quantum_port$o[0].channel (id=11), during network initialization
```
</blockquote></details>

okay, that's nice.

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492#-:-NO8Ihui5TWCriqaM-iQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri and @res6idue)

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 8 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOEo26iCxLFgIp9jJGj:-NOEo26iCxLFgIp9jJGk:beudjlz) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L8)):*
> ```cpp
> #include <stdexcept>
> #include <unsupported/Eigen/MatrixFunctions>
> #include "PhotonicQubit_m.h"
> ```

I don't get the whole picture yet, but will this photonic qubit will be replaced by the ShortLive qubit?

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 8 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOEo26iCxLFgIp9jJGj:-NOF5s2D-0ObEVszja-p:b3nhcbw) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L8)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I don't get the whole picture yet, but will this photonic qubit will be replaced by the ShortLive qubit?
</blockquote></details>

we have the photonic qubit class as message to send it through a quantum channel.
PhotonicQubit contains a reference to a short live qubit.
https://github.com/sfc-aqua/quisp/blob/master/quisp/PhotonicQubit.msg#L16

**Review by Naphann — COMMENTED** [review]
A little more context on why we want the short-live qubit and what does it offer.

This PR's main change is to move from using the same backend qubit the same way as stationary qubit. It used to assume that a photon emitted from a stationary qubit is only one with Id created by `{qnic_address, qnic_index, qnic_type, qubit_index}` but the `qnic_type` supplied to Id constructor was `100` to make it unique.

Now that we are preparing for multiple photon emission while the photons in flight might still live, we expect qubits to be create and delete a lot which would deter the performance. So I introduce the concept of short-live qubits which for now never gets deleted but once finished using will be sent back to the pool for reuse later.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492#-:-NOF8cTA0JwCsOZ0AJpE:b-6oeiob)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 8 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOEo26iCxLFgIp9jJGj:-NOF7_aG-VZ4rERndAmc:bix26c3) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L8)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we have the photonic qubit class as message to send it through a quantum channel.
PhotonicQubit contains a reference to a short live qubit.
https://github.com/sfc-aqua/quisp/blob/master/quisp/PhotonicQubit.msg#L16
</blockquote></details>

Yes as zigen said, this PR's main change is to move from using the same backend qubit the same way as stationary qubit. It used to assume that a photon emitted from a stationary qubit is only one with Id created by `{qnic_address, qnic_index, qnic_type, qubit_index}` but the `qnic_type` supplied to Id constructor was `100` to make it unique.

Now that we are preparing for multiple photon emission while the photons in flight might still live, we expect qubits to be create and delete a lot which would deter the performance. So I introduce the concept of short-live qubits which for now never gets deleted but once finished using will be sent back to the pool for reuse later.

I'll add this paragraph to the main PR comment as well.

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492#-:-NOFC8g-3TnyWgVQwycs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann and @res6idue)

___
*[`quisp/channels/QuantumChannel.cc` line 8 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOEo26iCxLFgIp9jJGj:-NOEoWuiEipVL8VcPKHq:b-wtger5) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L8)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Yes as zigen said, this PR's main change is to move from using the same backend qubit the same way as stationary qubit. It used to assume that a photon emitted from a stationary qubit is only one with Id created by `{qnic_address, qnic_index, qnic_type, qubit_index}` but the `qnic_type` supplied to Id constructor was `100` to make it unique.

Now that we are preparing for multiple photon emission while the photons in flight might still live, we expect qubits to be create and delete a lot which would deter the performance. So I introduce the concept of short-live qubits which for now never gets deleted but once finished using will be sent back to the pool for reuse later.

I'll add this paragraph to the main PR comment as well.
</blockquote></details>

That made sense to me. Thanks

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann and @res6idue)

**Review by zigen — APPROVED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 2 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 211 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOF_B-B7x4jGfYVY8tB:-NOF_B-B7x4jGfYVY8tC:b-ey5x8) ([raw file](https://github.com/sfc-aqua/quisp/blob/9ef169eed767c4ad4a84680d6407df25d9eab57d/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L211)):*
> ```objc
>     pkt_for_left->setOperation_type(left_op);
>     pkt_for_left->setNew_partner(right_partner_addr.val);
>     pkt_for_left->setMeasured_qubit_index(left_qubit_index);
> ```

btw we can't use the left_qubit_index and right_qubit_index, because we did set these values on the hacks...
we need the "tag" mechanism to notify that.

**Review by Naphann — COMMENTED** [review]
> Dismissed @Chibikuri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue and @zigen)

___
*[`quisp/channels/QuantumChannel.cc` line 8 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOEo26iCxLFgIp9jJGj:-NOF_2va51_7pTCMJybb:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c29e7eef8b932682c696c9c068be7421ff15197b/quisp/channels/QuantumChannel.cc#L8)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

That made sense to me. Thanks
</blockquote></details>

Done.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 211 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/492#-NOF_B-B7x4jGfYVY8tB:-NOFaGqgAAE10JvMZmJa:biqwcb4) ([raw file](https://github.com/sfc-aqua/quisp/blob/9ef169eed767c4ad4a84680d6407df25d9eab57d/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L211)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

btw we can't use the left_qubit_index and right_qubit_index, because we did set these values on the hacks...
we need the "tag" mechanism to notify that.
</blockquote></details>

I guess I haven't done entanglement-swapping simulations to realize that. I will check that thanks.

**Review by Chibikuri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue and @zigen)

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by res6idue — APPROVED** [review]
> Reviewed 21 of 32 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Review by res6idue — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/492#-:-NOFk6_CBoH25LNuF8lz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Pull request merged**
