### PR TITLE
reorganize directory structure

### PR DESCRIPTION
**Pull request by zigen**
This PR reorganizes the directory structure like the following screen shot.
The current problem is the whole `.ned` files are in the `networks` directory, and too many files in one directory.
obviously the QNode and other components should be in `modules` directory because these are not networks, one of the comonents or modules.

This PR might affect everyone who is working on this project, so be careful to merge.

Screen Shot 2020-10-27 at 14 39 20

### CODE REVIEW

**Comment by Chibikuri** [comment]
Ah, I think this structure is clear to see. @rdviii What do you think?

**Comment by Chibikuri** [comment]
Sorry for the late response.  I'm starting reviewing.

**Comment by Chibikuri** [comment]
I'm checking your changes in my local and I found the tests are not running.
I guess the target objects should be updated in Makefile. 

I'll modify and push it.

**Comment by Chibikuri** [comment]
Let me take over this pull request in another pull request.

**Comment by zigen** [comment]
@Chibikuri thanks for taking over this in #184

**Pull request closed without merging**
