### PR TITLE
Update CI work flow

### PR DESCRIPTION
**Pull request by Chibikuri**
Currently, CI doesn't check the format and run tests when we create PR.
This PR tries to add format, tests to the CI workflow. 

Add
- [ ] clang-format
- [ ] clang-tidy
- [ ] unit-test
- [ ] module-test
- [ ] Format QuantumChannel
#196 #195

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/226)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Comment by zigen** [comment]
@Chibikuri are you busy? I need this fix, if you're busy now, ask someone or I'll take this.

**Comment by Chibikuri** [comment]
@zigen If you are available, that would be very helpful...
I'm a bit busy with papers.

**Comment by zigen** [comment]
okay, I'll take this

**Pull request closed without merging**
