### PR TITLE
TopologyInitializer for routingdaemon done

### PR DESCRIPTION
**Pull request by Tatzhiro**
Closes issue #461 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520)

### CODE REVIEW

**Review by zigen — APPROVED** [review]
> Reviewed 15 of 30 files at r1, 2 of 13 files at r2, 2 of 4 files at r3, 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Review by zigen — APPROVED** [review]
could you run `$make format` ? then it looks good!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520#-:-NS_ueHq4_egmSGl2TuJ:bytjmii)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Review by zigen — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520#-:-NSdPkF7Bhaaf_rxMBhD:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Naphann)

**Review by Tatzhiro — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520#-:-NSjAwaH9e9SPjrpDfqv:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Tatzhiro)

**Review by Tatzhiro — COMMENTED** [review]
> Reviewed 1 of 30 files at r1, 1 of 4 files at r3, 26 of 29 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tatzhiro)

**Pull request merged**
