### PR TITLE
add MeasureResult enums

### LINKED ISSUE #227: Error tracking return wrong values
As raised by @PorametPat 

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L317-L320

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L340-L343

These methods are very misleading. They should not be called `measure_X` or `measure_Z` since they output whether there are errors or not. It should be renamed to `hasXError` and `hasZError`. And also the return value is wrong. 

They currently output 
- `false` if there is a bit flip
- `true` if there is no flip error

but as used here 

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/rules/Action.cc#L105-L113

It checks for `false` to mean there are no bit flip. 

Unless I misunderstood the `par("God_ZError")` to mean the opposite this is a very serious bug.

### PR DESCRIPTION
**Pull request by zigen**
fix #227
the `measure_Z` method applies a memory error as a side effect. so this result type should be changed, not renamed.
I introduced `MeasureZResult` scoped-enum and each action will do some operations by checking this enum value.

- [x] add `MeasureZResult`
- [x] add unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Naphann and @PorametPat)

___
*[quisp/rules/actions/SwappingAction.cc, line 75 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/255#-MfwmKXU1t4TdfLDaHWe:-MfwmKXU1t4TdfLDaHWf:b-86e6nh) ([raw file](https://github.com/sfc-aqua/quisp/blob/cfacc15040b5818d1350a333e8f0308e23fdcc0f/quisp/rules/actions/SwappingAction.cc#L75)):*
> ```cpp
>   if (left_measure == MeasureZResult::NO_ERROR && right_measure == MeasureZResult::NO_ERROR) {
>     EV << "operation type 0, operation left I, operation right I\n";
>     operation_type_left = 0;
> ```

these operation_type vars are also confusing. I'll replace it with enum later

**Review by Naphann — CHANGES_REQUESTED** [review]
For some reason, the module test failed on my machine with this error.
```
cd quisp && opp_makemake -f --deep -O out -i ./makefrag -M debug  --make-so
Creating Makefile in /Users/naphann/projects/quisp/quisp...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C quisp -j
PKG_CONFIG_STATUS=0
Creating shared library: out/clang-debug//libquisp_dbg.dylib
cd module_tests && ./runtest
/Users/naphann/projects/quisp/module_tests/application/Application.test
opp_test.py: extracting files from *.test files into /Users/naphann/projects/quisp/module_tests/work...

Creating Makefile in /Users/naphann/projects/quisp/module_tests/work...
PKG_CONFIG_STATUS=0
Application/mock_router.cc
In file included from Application/mock_router.cc:4:
In file included from /Users/naphann/projects/quisp/module_tests/../quisp/test_utils/TestUtils.h:10:
/Users/naphann/projects/quisp/module_tests/../quisp/test_utils/mock_modules/MockQubit.h:3:10: fatal error: 'gmock/gmock.h' file not found
#include "gmock/gmock.h"
         ^~~~~~~~~~~~~~~
1 error generated.
```

> Reviewed 2 of 4 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgQlAFdCgAZZ_XM6-z8:bp6glki)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @PorametPat and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 655 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/255#-MgQi24LEt5YcLeG6jKb:-MgQi24LEt5YcLeG6jKc:buck3bs) ([raw file](https://github.com/sfc-aqua/quisp/blob/4d221b22170d9c057976cb760f5d93d148cda03d/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L655)):*
> ```cpp
>   apply_memory_error(resource_qubit);
>   /*Target qubit*/ this->CNOT_gate(resource_qubit /*controlled qubit*/);
>   bool meas = this->measure_Z() == MeasureZResult::HAS_X_ERROR;
> ```

In the old code `meas` is `true` when there is no error. 

```cpp
bool StationaryQubit::measure_Z() {
  // Need to add noise here later
  apply_single_qubit_gate_error(Measurement_error);
  return !par("GOD_Xerror");
}
```
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 665 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/255#-MgQiH5lEvvuA6B2jYHd:-MgQiH5lEvvuA6B2jYHe:b-b6lgei) ([raw file](https://github.com/sfc-aqua/quisp/blob/4d221b22170d9c057976cb760f5d93d148cda03d/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L665)):*
> ```cpp
>   /*Target qubit*/ resource_qubit->CNOT_gate(this /*controlled qubit*/);
>   this->Hadamard_gate();
>   bool meas = this->measure_Z() == MeasureZResult::HAS_X_ERROR;
> ```

`meas` should be `true` if there is no error at least from the old code (same as above)

**Review by zigen — COMMENTED** [review]
could you try `$ make distclean && make run-unit-test`?
it seems there's no `/googletest` in the repository root. distclean removes all submodules and then it will re-init submodules again. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgZakGX4rzJRYsB-ZtC:b-x3hnq4)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @Naphann, @PorametPat, and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 655 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/255#-MgQi24LEt5YcLeG6jKb:-MgZaa9KAFfiLKzmq6a9:b8pgxfq) ([raw file](https://github.com/sfc-aqua/quisp/blob/4d221b22170d9c057976cb760f5d93d148cda03d/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L655)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

In the old code `meas` is `true` when there is no error. 

```cpp
bool StationaryQubit::measure_Z() {
  // Need to add noise here later
  apply_single_qubit_gate_error(Measurement_error);
  return !par("GOD_Xerror");
}
```
</blockquote></details>

thanks for reviewing! that's right. I totally overlooked it... I'll fix it.

**Review by Naphann — COMMENTED** [review]
The unit test is working fine. I always do the `distclean` and `clean` every time there's a new commit. Just the `make run-module-test` that isn't working. For some reason, it doesn't know where `<gmock/gmock>` inside the `test_utils\mock_modules`

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgZcuGF8pLwOIVXkYWR:b-2xfp1d)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @Naphann, @PorametPat, and @zigen)

**Review by zigen — COMMENTED** [review]
ah, okay, I reproduced it in my environment. let me fix. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgZfbZQBY30SXzRCCF8:b-v4hhp7)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @PorametPat)

**Review by zigen — COMMENTED** [review]
thanks, now I fixed it.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgZgYHR3U43sglvNtLG:byuzg2c)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @PorametPat)

**Review by Naphann — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255#-:-MgZi7GMDUeLnl_xZvf-:bnfp4nl)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @PorametPat)

**Comment by PorametPat** [comment]
___
*[quisp/rules/actions/SimultaneousSwappingAction.cc, line 72 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/255#-Mg_ABXg8RP-3RsAcv5F:-Mg_ABXh9okP7cMHAFm6:b6uveo9) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1a2b2b11f202c4ab347e1e59e95a999eac30be8/quisp/rules/actions/SimultaneousSwappingAction.cc#L72)):*
> ```cpp
> 
>   left_qubit->Hadamard_gate();
>   right_qubit->CNOT_gate(left_qubit);
> ```

This may be a separate issue. Not sure if this is come since my part or not, but the order of gates is swap. We need to do CNOT before Hadamard for Bell measurement.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @PorametPat)

___
*[quisp/rules/actions/SimultaneousSwappingAction.cc, line 72 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/255#-Mg_ABXg8RP-3RsAcv5F:-Mg_HMuY5MNL4TH1o3bn:bs3euxf) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1a2b2b11f202c4ab347e1e59e95a999eac30be8/quisp/rules/actions/SimultaneousSwappingAction.cc#L72)):*
<details><summary><i>Previously, PorametPat wrote…</i></summary><blockquote>

This may be a separate issue. Not sure if this is come since my part or not, but the order of gates is swap. We need to do CNOT before Hadamard for Bell measurement.
</blockquote></details>

thanks for reviewing! that's the crucial point. fortunitely it is easy to fix, so I'll fix it in this PR!

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @Naphann and @PorametPat)

___
*[quisp/rules/actions/SimultaneousSwappingAction.cc, line 72 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/255#-Mg_ABXg8RP-3RsAcv5F:-Mg_MfG28zdKGrqlpt7A:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1a2b2b11f202c4ab347e1e59e95a999eac30be8/quisp/rules/actions/SimultaneousSwappingAction.cc#L72)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

thanks for reviewing! that's the crucial point. fortunitely it is easy to fix, so I'll fix it in this PR!
</blockquote></details>

Done.

**Comment by zigen** [comment]
@PorametPat if there's no problem, could you make it "satisfied" and click "LGTM" button and then publish it on reviewable?

スクリーンショット 2021-08-08 20 08 30
スクリーンショット 2021-08-08 20 08 24

**Review by PorametPat — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
