### PR TITLE
fix bug in the finish function of HardwareMonitor

### PR DESCRIPTION
**Pull request by Chibikuri**
I found a bug when we finished the simulation.
During cleaning up codes, the finish function was broken. 
Now it's fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/233)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
did you check your changes? should I point the same things again and again?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/233#-:-Md_X7F77zgvgM-o8gE0:b-xpi0bu)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 58 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_WkXO7JYabRN7Nli7:-Md_WkXO7JYabRN7Nli8:b-6pp68s) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L58)):*
> ```objc
>   std::vector<int> used_qnics;
>   // in the case of retry connection setup, the partner could be changed.
>   std::multimap<int, int> qnic_partner_map;
> ```

should we need multimap? 
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 89 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_Wxuu6xPiZJ46Yxu8:-Md_Wxuu6xPiZJ46Yxu9:bfqlk6z) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L89)):*
> ```objc
>   virtual void sendLinkTomographyRuleSet(int my_address, int partner_address, QNIC_type qnic_type, int qnic_index, unsigned long rule_id);
>   virtual QNIC search_QNIC_from_Neighbor_QNode_address(int neighbor_address);
>   virtual Matrix4cd extended_reconstruct_Density_Matrix(int qnic_id, int partner);
> ```

the method name should be started with a verb.
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 1157 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_WdW14Um67oFYVozs:-Md_WdW20prEoG8KC0mO:b4t6miw) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L1157)):*
> ```cpp
> }
> 
> cModule *HardwareMonitor::getQNode() {
> ```

please use `ComponentProvider`
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 1210 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_Wa0M8FUuRIKIh1H5:-Md_Wa0M8FUuRIKIh1H6:b-41bwa) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L1210)):*
> ```cpp
>     cModule *controller = thisNode.getSubmodule("Controller");
>     if (controller == nullptr) {
>       error("HoM Controller or ABSA Controller not found");
> ```

do you use ABSA?

**Review by Naphann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/233)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 64 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_VwjQDzngCLoM7cpV:-Md_VwjRCEH67G_leUk3:b-gwreaa) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L64)):*
> ```objc
>   cModule *getQnic(int qnic_index, QNIC_type qnic_type);
>   NeighborTable neighbor_table;
>   LawData *tomography_data;
> ```

Typo? Should be RawData (same comment as the declaration part)
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 83 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_WSco1t3VLo1gmTw3:-Md_WSco1t3VLo1gmTw4:b-x83h98) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L83)):*
> ```objc
> 
>   virtual std::unique_ptr<NeighborInfo> createNeighborInfo(const cModule &thisNode);
>   virtual cModule *getQNode();
> ```

Why not using ComponentProvider and use the getQNode method?
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 84 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_Wnxs85gozWwDkDhZ:-Md_Wnxs85gozWwDkDh_:b-riqr99) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L84)):*
> ```objc
>   virtual std::unique_ptr<NeighborInfo> createNeighborInfo(const cModule &thisNode);
>   virtual cModule *getQNode();
>   virtual cModule *getQNodeWithAddress(int address);
> ```

this should be from provider as well. I'm not sure if this is already implemented in ComponentProvider.
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 165 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_X04x4lCQP1Zh5U9V:-Md_X04x4lCQP1Zh5U9W:bbh4lyb) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L165)):*
> ```cpp
>     /*Link tomography measurement result/basis from neighbor received.*/
>     LinkTomographyResult *result = check_and_cast<LinkTomographyResult *>(msg);
>     int partner = result->getPartner_address();
> ```

I think `partner_addr` is more readable. But I really think we should use new typedef for it instead of using `int` as it doesn't convey meaning
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 205 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_XGJr6X8IMsddE-c8:-Md_XGJr6X8IMsddE-c9:b-cz0kff) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L205)):*
> ```cpp
>           temp.partner_GOD_clean = result->getGOD_clean();
>         }
>         temporal_tomography_output[local_qnic.address][partner].insert(std::make_pair(result->getCount_id(), temp));
> ```

Is this a typo? Should it be `temporary_tomography_output` What does temporal mean if it's already correct?
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 332 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_XnhZ-ncX17f6UvNi:-Md_XnhZ-ncX17f6UvNj:b-4frz9i) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L332)):*
> ```cpp
>       } else if ((it->second.my_GOD_clean == 'Y' && it->second.partner_GOD_clean == 'F') || (it->second.my_GOD_clean == 'F' && it->second.partner_GOD_clean == 'Y')) {
>         GOD_Y_pair_total++;
>       }  // end if
> ```

do we need this comment?
___
*[quisp/modules/QRSA/HardwareMonitor/IHardwareMonitor.h, line 74 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_W6Ep52To7IAhs6eB:-Md_W6Ep52To7IAhs6eC:b-9hbad8) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/IHardwareMonitor.h#L74)):*
> ```objc
> // "XX" -> {plus_plus = 56, plus_minus = 55, minus_plus = 50, minus_minus = 50},
> // "XY" -> {....
> typedef std::map<int, std::map<std::string, output_count>> LawData;  // qnic -> partner . basis string . output
> ```

Is this a typo? What is LawData? Should it be RawData?

**Comment by Chibikuri** [comment]
Oh, give me a sec.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/233)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h, line 84 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_Wnxs85gozWwDkDhZ:-Md_YIco3tl0Sx12MJTn:baspddp) ([raw file](https://github.com/sfc-aqua/quisp/blob/d0f7dd93fa3cfa75d008c8b97731f0e8aa84bbe8/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L84)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

this should be from provider as well. I'm not sure if this is already implemented in ComponentProvider.
</blockquote></details>

it hasn't implemented yet. so I accepted this for now. but later we should implement it on ComponentProvider

**Comment by Chibikuri** [comment]
I'm sorry for bothering you again and again...

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/233)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 348 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_g_2U4y5LNo4vWCAG:-Md_g_2U4y5LNo4vWCAH:b-ehnyk8) ([raw file](https://github.com/sfc-aqua/quisp/blob/19ca640ed293a1136598d15b4df1d67defda7899/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L348)):*
> ```cpp
>       }
>     }  // end for
>        // extended density matrix
> ```

do we need this comment? it's obvious by the variable name and the method.
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 1198 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_gOrU2aJBR7vFRjeA:-Md_gOrU2aJBR7vFRjeB:b-37jwxu) ([raw file](https://github.com/sfc-aqua/quisp/blob/19ca640ed293a1136598d15b4df1d67defda7899/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L1198)):*
> ```cpp
>     EV << address_one << ":" << address_two << "\n";
>     if (address_one == -1 && address_two == -1) {
>       error("HoM Controller or ABSA Controller is not initialized properly");
> ```

are you using ABSA? please check your changes before commit
___
*[quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc, line 1225 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_gKEb79wtG3CRI3LS:-Md_gKEb79wtG3CRI3LT:b840t0q) ([raw file](https://github.com/sfc-aqua/quisp/blob/52e52e2f1e24063c6c5de2303aaf253bb1b2b976/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L1225)):*
> ```cpp
> 
>   error(
>       "This simulator only recognizes the following network level node "
> ```

why you delete this?
___
*[quisp/modules/QRSA/HardwareMonitor/IHardwareMonitor.h, line 76 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/233#-Md_g2J93qczqkf2XGq5:-Md_g2J93qczqkf2XGq6:b-qruvpw) ([raw file](https://github.com/sfc-aqua/quisp/blob/19ca640ed293a1136598d15b4df1d67defda7899/quisp/modules/QRSA/HardwareMonitor/IHardwareMonitor.h#L76)):*
> ```objc
> typedef std::map<int, std::map<std::string, output_count>> RawData;  // qnic -> partner . basis string . output
> typedef std::map<int, link_cost> LinkCostMap;
> typedef std::map<int, std::map<int, tomography_outcome>> ExtendedTomographyOutcome;  // partner -> <count_id, outcome>
> ```

this name absolutely confusing us.

**Comment by Chibikuri** [comment]
I got where was the problem. Let me close this once and fix only where the problem.

**Pull request closed without merging**
