### PR TITLE
Create ActiveRuleSet and transplant current RuleSet to it.

### PR DESCRIPTION
**Pull request by Chibikuri**
# Goal in this PR
- [x] Create ActiveRuleSet (ARS) for clean up their responsibility
- [x] Write tests for ARS
- [x] Remove an argument called  `entangled partner` of current RuleSet.
- [x] Replace current RuleSet and Rules with ActiveRuleSet and ActiveRule

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/335)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 27 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/335)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/rules/ActiveRule.h, line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmEUdo-UtUlBOrmJoN:-MsmEUdo-UtUlBOrmJoO:b-d3rhhh) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRule.h#L1)):*
> ```objc
> /** \file Rule.h
> ```

don't we need this boilerplate?
___
*[quisp/rules/ActiveRule.cc, line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmS5xiCut12MNkh_1S:-MsmS5xiCut12MNkh_1T:b1kd3s5) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRule.cc#L1)):*
> ```cpp
> /** \file Rule.cc
> ```

could you fix or remove it?
___
*[quisp/rules/ActiveRuleSet.h, line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmOYGe8rIvFOg00otB:-MsmOYGe8rIvFOg00otC:b3ceay3) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRuleSet.h#L8)):*
> ```objc
> namespace rules {
> 
> /** \class RuleSet RuleSet.h
> ```

this should be ActiveRuleSet, and you can remove the file name because it is optional in the doxygen comment.
___
*[quisp/rules/ActiveRuleSet.cc, line 12 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmQTFY5ZCnKAM-9GHm:-MsmQTFY5ZCnKAM-9GHn:b-mnp8c6) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRuleSet.cc#L12)):*
> ```cpp
>  * @param _owner_addr
>  */
> ActiveRuleSet::ActiveRuleSet(unsigned long _ruleset_id, int _owner_addr) {
> ```

how about the member-initializer list?
https://en.cppreference.com/w/cpp/language/constructor
for example:
```cpp 
ActiveRuleSet::ActiveRuleSet(unsigned long _ruleset_id, int _owner_addr) : 
  ruleset_id(_ruleset_id), 
  owner_addr(_owner_addr), 
  started_at(simTime()) {
}
```

reason:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c49-prefer-initialization-to-assignment-in-constructors

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/335)* status: 25 of 29 files reviewed, 4 unresolved discussions (waiting on @zigen)

___
*[quisp/rules/ActiveRule.h, line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmEUdo-UtUlBOrmJoN:-MsmjDu23-rXYRrQ-Vpd:bss4a2b) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRule.h#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

don't we need this boilerplate?
</blockquote></details>

Removed.
___
*[quisp/rules/ActiveRule.cc, line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmS5xiCut12MNkh_1S:-MsmjJMi3UOt9ffK_dpu:ba3dfob) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRule.cc#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

could you fix or remove it?
</blockquote></details>

Removed
___
*[quisp/rules/ActiveRuleSet.h, line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmOYGe8rIvFOg00otB:-MsmjaGXB3Kk8nGZCAj0:b-e06j4t) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRuleSet.h#L8)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

this should be ActiveRuleSet, and you can remove the file name because it is optional in the doxygen comment.
</blockquote></details>

OK, removed.
___
*[quisp/rules/ActiveRuleSet.cc, line 12 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/335#-MsmQTFY5ZCnKAM-9GHm:-MsmjuY81iCZgfLVHhYB:bsv6c9) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbff7124af065ba80815abe489d6c4dcb5b35d28/quisp/rules/ActiveRuleSet.cc#L12)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

how about the member-initializer list?
https://en.cppreference.com/w/cpp/language/constructor
for example:
```cpp 
ActiveRuleSet::ActiveRuleSet(unsigned long _ruleset_id, int _owner_addr) : 
  ruleset_id(_ruleset_id), 
  owner_addr(_owner_addr), 
  started_at(simTime()) {
}
```

reason:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c49-prefer-initialization-to-assignment-in-constructors
</blockquote></details>

Applied, thanks.

**Review by zigen — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/335#-:-MsnB2WU5W1QUSikwOXB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
