### PR TITLE
add QubitRecord, QNicStore and QNicRecord files

### PR DESCRIPTION
**Pull request by zigen**
スクリーンショット 2021-12-10 13 47 29

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
I added these classes, but they have not been fully implemented yet. 
QubitRecord has only the `isBusy` state and `Busy_OR_FreeQubitStateTable` and related methods are removed from RuleEngine.
Basically, I intended to use QNicStore as a general interface for QubitRecord and QNicRecord which contains the software states for Qubits and QNICs.

> Reviewed 23 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318#-:-MqiUqoS2ZidUtEWxPhG:b-2dmcfb)* status: 23 of 24 files reviewed, 2 unresolved discussions

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_photon_shooting_test.cc, line 42 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqiWtGF0RUW1kOBxihU:-MqiWtGF0RUW1kOBxihV:b-qxti7q) ([raw file](https://github.com/sfc-aqua/quisp/blob/b1a2e8a0052d2485ec031c0cf3a70729956692d3/quisp/modules/QRSA/RuleEngine/RuleEngine_photon_shooting_test.cc#L42)):*
> ```cpp
>  public:
>   Strategy() : mockQubit(nullptr), routingDaemon(nullptr), hardwareMonitor(nullptr) {}
>   Strategy(IStationaryQubit* _qubit, MockRoutingDaemon* routing_daemon, MockHardwareMonitor* hardware_monitor, MockRealTimeController* realtime_controller)
> ```

I copied and pasted in the prev PR, but we don't need to use qubit and real-time controller. 
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_photon_shooting_test.cc, line 119 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqiWBwD4A9l-nvHhM8d:-MqiWBwD4A9l-nvHhM8e:b-m0fjya) ([raw file](https://github.com/sfc-aqua/quisp/blob/b1a2e8a0052d2485ec031c0cf3a70729956692d3/quisp/modules/QRSA/RuleEngine/RuleEngine_photon_shooting_test.cc#L119)):*
> ```cpp
> 
>   // Emitter QNIC(index:0~2) has 1 qubit, Receiver QNIC(index:0) has 1 qubit
>   EXPECT_CALL(*mockHardwareMonitor, getQnicNumQubits(0, QNIC_E)).WillRepeatedly(Return(1));
> ```

the `HardwareMonitor::getNumQnicNumQubits` method is used inside the `RuleEngine::initializeQubitStateTable` method which initializes `Busy_OR_FreeQubitStateTable`. But I removed it so we need to provide the number of qnics to ComponentProvider and its Strategy.

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 24 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 39 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqlXFWFBT8XF2M9r_d-:-MqlXFWFBT8XF2M9r_d0:bxxy40f) ([raw file](https://github.com/sfc-aqua/quisp/blob/35fc926c3bd1271c5a11f505cef9f7ccffc9c6d8/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L39)):*
> ```cpp
>   number_of_qnics_rp = par("number_of_qnics_rp");
>   if (qnic_store == nullptr) {
>     qnic_store = std::make_unique<QNicStore>(provider, number_of_qnics, number_of_qnics_r, number_of_qnics_rp);
> ```

What is the difference between QNicStore and QNicRecord?
And why do we need a component provider here?

**Review by zigen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 39 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqlXFWFBT8XF2M9r_d-:-MqldlUI58sq65Pyg0ka:b-qm55v9) ([raw file](https://github.com/sfc-aqua/quisp/blob/35fc926c3bd1271c5a11f505cef9f7ccffc9c6d8/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L39)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

What is the difference between QNicStore and QNicRecord?
And why do we need a component provider here?
</blockquote></details>

QNicRecord represents one QNIC, and QNicStore manages a number of QNICs.
During QNicStore construction, we need to collect QNIC information like the number of qubits, type, or we will need more if we want to add more features to QNIC and Qubits. 
So we need to provide the ComponentProvider to delegate the decision on how to create Qubit/QNic record to QNicStore from RuleEngine. 

in the future, we will add the actual implementation of the ComponentProvider so that it can collect QNic/Qubit information of the actual hardwares.

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 39 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqlXFWFBT8XF2M9r_d-:-Mqm-PDf9z8APx2QwUnA:b-kufkxf) ([raw file](https://github.com/sfc-aqua/quisp/blob/35fc926c3bd1271c5a11f505cef9f7ccffc9c6d8/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L39)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

QNicRecord represents one QNIC, and QNicStore manages a number of QNICs.
During QNicStore construction, we need to collect QNIC information like the number of qubits, type, or we will need more if we want to add more features to QNIC and Qubits. 
So we need to provide the ComponentProvider to delegate the decision on how to create Qubit/QNic record to QNicStore from RuleEngine. 

in the future, we will add the actual implementation of the ComponentProvider so that it can collect QNic/Qubit information of the actual hardwares.
</blockquote></details>

I see, thanks!

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318#-:-Mqm-Ti87p3cQ9ysLR7r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/318)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 39 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/318#-MqlXFWFBT8XF2M9r_d-:-MqmEgik00j_FoKdQQ_y:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/35fc926c3bd1271c5a11f505cef9f7ccffc9c6d8/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L39)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

I see, thanks!
</blockquote></details>

Done.

**Pull request merged**
