### PR TITLE
Rename Purification Protocols

### PR DESCRIPTION
**Pull request by lmpawan10**
The names of purification protocols have been renamed as follows:

1. SINGLE_X: Single_Selection_X_Purification
2. SINGLE_Z: Single_Selection_Z_Purification
3. SINGLE_Y: Single_Selection_Y_Purification
4. DOUBLE: Single_Selection_XZ_Purification
5. DOUBLE_INV: Single_Selection_ZX_Purification
6. DSSA: Double_Selection_X_Purification
7. DSSA_INV: Double_Selection_Z_Purification
8. DSDA: Double_Selection_XZ_Purification
9. DSDA_INV: Double_Selection_ZX_Purification
10. DSDA_SECOND: Double_Selection_X_Purification_Single_Selection_Z_Purification
11. DSDA_SECOND_INV: Double_Selection_Z_Purification_Single_Selection_X_Purification

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/549)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/549)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @lmpawan10)

___
*[`quisp/rules/Action.h` line 17 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/549#-NvzGLDY5UBLg-qXprrz:-NvzGLDZAR855ogCZbFv:b-je54nq) ([raw file](https://github.com/sfc-aqua/quisp/blob/b9897b9e4ea24cf02819b37f1ba70cea708f118c/quisp/rules/Action.h#L17)):*
> ```objc
> enum PurType : int {
>   INVALID,  ///< Invalid purification type
>   Single_Selection_X_Purification,  ///< Single purification for X error
> ```

this should be `SINGLE_SELECTION_X_PURIFICATION`.
these names are mixed cases. we should keep the names consistent.
that allows us to expect the identifiers easily. if not, it's hard to expect.

**Comment by lmpawan10** [comment]
All purification protocol names changed to uppercase as,

1. Single_Selection_X_Purification: SINGLE_SELECTION_X_PURIFICATION
2. Single_Selection_Z_Purification: SINGLE_SELECTION_Z_PURIFICATION
3. Single_Selection_Y_Purification: SINGLE_SELECTION_Y_PURIFICATION
4. Single_Selection_XZ_Purification: SINGLE_SELECTION_XZ_PURIFICATION
5. Single_Selection_ZX_Purification: SINGLE_SELECTION_ZX_PURIFICATION
6. Double_Selection_X_Purification: DOUBLE_SELECTION_X_PURIFICATION
7. Double_Selection_Z_Purification: DOUBLE_SELECTION_Z_PURIFICATION
8. Double_Selection_XZ_Purification: DOUBLE_SELECTION_XZ_PURIFICATION
9. Double_Selection_ZX_Purification: DOUBLE_SELECTION_ZX_PURIFICATION
10. Double_Selection_X_Purification_Single_Selection_Z_Purification: DOUBLE_SELECTION_X_PURIFICATION_SINGLE_SELECTION_Z_PURIFICATION
11. Double_Selection_Z_Purification_Single_Selection_X_Purification: DOUBLE_SELECTION_Z_PURIFICATION_SINGLE_SELECTION_X_PURIFICATION

**Review by zigen — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/549)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lmpawan10)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/549#-:-Nvzghyb2iLrLehikPfM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lmpawan10)

**Pull request merged**
