### PR TITLE
RuleSet into (ActiveRuleSet, RuleSet) based on their responsibility

### PR DESCRIPTION
**Pull request by Chibikuri**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336)

### CODE REVIEW

**Comment by zigen** [comment]
@Chibikuri don't forget to merge the latest master

**Comment by Chibikuri** [comment]
> @Chibikuri don't forget to merge the latest master

Thanks, I did.

**Comment by zigen** [comment]
@Chibikuri don't forget to merge the latest master

**Review by zigen — APPROVED** [review]
:lgtm:

let's merge it, and then refactor it. we cannot do refactor in this PR

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336#-:-N3mhg792hIRGRmD4Pc6:b-j0y79t)* status: 9 of 107 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336)* status: 9 of 107 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[`quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc` line 335 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/336#-N3U2NRlDMn7099LvOub:-N3o6gdSAoIkuVqqAIlc:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/34c7b3225d5eaf3dced012bb0a50ff9bbbcd809a/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L335)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's a map, but it's named an array...
</blockquote></details>

Done.

**Review by Chibikuri — COMMENTED** [review]
Got it!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336#-:-N3o6sGr3w7xwpkvL-KX:b-4hvi0z)* status: 9 of 107 files reviewed, 1 unresolved discussion (waiting on @zigen)

**Review by Chibikuri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336#-:-N3qyeK58XfrznhhEyTQ:bnfp4nl)* status: 9 of 107 files reviewed, 1 unresolved discussion (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
I forgot to resolve the discussion.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336#-:-N3rw4LeALDu3E9SQqnQ:b-3eqic7)* status: 9 of 107 files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336#-:-N3rwBeT9HkxSY5R8tco:bnfp4nl)* status: 9 of 107 files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — APPROVED** [review]
> Reviewed 29 of 85 files at r1, 3 of 23 files at r3, 65 of 74 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
