### PR TITLE
Use qubit record

### PR DESCRIPTION
**Pull request by zigen**
now I'm replacing `IStationaryQubit` with `IQubitRecord`.
In this PR, I'll replace RuleEngine and BellPairStore, not RuleSet.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: 0 of 20 files reviewed, 2 unresolved discussions

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 845 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/322#-MqxFl4PDNvy_QuBij1y:-MqxFl4Q5Dk2Y9XLID7f:b3ou0jd) ([raw file](https://github.com/sfc-aqua/quisp/blob/ac7270e383a45972c8ba23483f61d379c8c8d2dc/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L845)):*
> ```cpp
>     realtime_controller->applyXGate(qubit_record);
>   } else if (operation_type == 2) {
>     realtime_controller->applyZGate(qubit_record);
> ```

@chibikuri  @naphann what do you think of invoking the qubit operation in this way?
___
*[quisp/modules/QRSA/RuleEngine/QubitRecord/QubitRecord_test.cc, line 25 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/322#-MqxGIz675X-IR94U-3h:-MqxGIz675X-IR94U-3i:bqkqz4l) ([raw file](https://github.com/sfc-aqua/quisp/blob/ac7270e383a45972c8ba23483f61d379c8c8d2dc/quisp/modules/QRSA/RuleEngine/QubitRecord/QubitRecord_test.cc#L25)):*
> ```cpp
> class QubitRecordTest : public ::testing::Test {
>  protected:
>   void SetUp() override { record = QubitRecord(qnic_index, qnic_type, qubit_index); }
> ```

I totally overlooked the googletests's TestFixtures. this might be a better way.
https://google.github.io/googletest/primer.html#same-data-multiple-tests

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 845 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/322#-MqxFl4PDNvy_QuBij1y:-MqyNHjY6GwErEXq1Lq6:b-u90728) ([raw file](https://github.com/sfc-aqua/quisp/blob/ac7270e383a45972c8ba23483f61d379c8c8d2dc/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L845)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

@chibikuri  @naphann what do you think of invoking the qubit operation in this way?
</blockquote></details>

I agree with this way. I think this way should be applicable for all operations.

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 845 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/322#-MqxFl4PDNvy_QuBij1y:-MqySenF4pBW57HJwvn4:b-v2bwsv) ([raw file](https://github.com/sfc-aqua/quisp/blob/ac7270e383a45972c8ba23483f61d379c8c8d2dc/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L845)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

I agree with this way. I think this way should be applicable for all operations. 
</blockquote></details>

I don't have a problem with applying operation in this way. It does look clean.

**Review by zigen — COMMENTED** [review]
> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: 26 of 27 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QRSA/RuleEngine/QNicRecord/IQNicRecord.h, line 20 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/322#-Mr79kws5Ka06Ww0v6Qt:-Mr79kws5Ka06Ww0v6Qu:b-dy10aa) ([raw file](https://github.com/sfc-aqua/quisp/blob/29458dca28e49fa56bfc985a502c0bfc4d64ab21/quisp/modules/QRSA/RuleEngine/QNicRecord/IQNicRecord.h#L20)):*
> ```objc
>   virtual int takeFreeQubitIndex() = 0;
>   virtual void setQubitBusy(int qubit_index, bool is_busy) = 0;
>   virtual qrsa::IQubitRecord* getQubit(int qubit_index) = 0;
> ```

I totally changed the interface of `getQubit`. QNicRecord has the ownership of each QubitRecord and QNicRecord will destroy QubitsRecord. BellPairStore has no ownership of QubitRecords, it only has the pointer of that.
___
*[quisp/modules/QRSA/RuleEngine/QubitRecord/QubitRecord.h, line 11 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/322#-Mr7AO4o3cxdyVpq6FQg:-Mr7AO4o3cxdyVpq6FQh:bravfc1) ([raw file](https://github.com/sfc-aqua/quisp/blob/29458dca28e49fa56bfc985a502c0bfc4d64ab21/quisp/modules/QRSA/RuleEngine/QubitRecord/QubitRecord.h#L11)):*
> ```objc
> class QubitRecord : public IQubitRecord {
>  public:
>   QubitRecord(QNIC_type qnic_type, int qnic_index, int qubit_index);
> ```

I changed the order of arguments for consistency and readability.
it specifies in order of the scope goes narrow: QNIC Type -> QNIC Index -> Qubit Index.

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322#-:-MrKlTup1V7rBi-nSniC:bnfp4nl)* status: 20 of 28 files reviewed, 2 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: 27 of 28 files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
