### PR TITLE
Fixed bug of RuleSet generations

### PR DESCRIPTION
**Pull request by Chibikuri**
Related issue #271 

## Problem
Currently, the order of rules is important for later processing. To point out the next rules properly, this order is required when these Rules are added to RuleSet.

## Solution
In general, the distance from swapper and partners is getting larger from start to the end. To make the order of swapping proper, the swapping should be done from small distance swapping.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272)

### CODE REVIEW

**Review by zigen — APPROVED** [review]
could you write a test for this quickly?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272#-:-Mi_J784B1DlVS50LBRO:b-fztxbt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by Chibikuri — COMMENTED** [review]
OK, let me write it.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272#-:-Mi_KnrbECj55tYFT1UV:bs4vopg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
could you run clang-format?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272#-:-MiavBg23_4FdaqlVpRt:b-fnyi0e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 944 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/272#-MibAJKv8ddzxRPNr5KV:-MibAJKv8ddzxRPNr5KW:b5d6yic) ([raw file](https://github.com/sfc-aqua/quisp/blob/87838e9d8ba402027318270d6ef84407c805f733/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L944)):*
> ```cpp
>   auto rule_entanglement_swapping = std::make_unique<Rule>(ruleset_id, rule_id, rule_name, partners);
>   Condition *condition = new Condition();
>   Clause *resource_clause_left = new EnoughResourceClause(conf.left_partner, 1);
> ```

why you set this 1?

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 944 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/272#-MibAJKv8ddzxRPNr5KV:-MibAmW_9QPO2COIL8Vg:b-m7xrpm) ([raw file](https://github.com/sfc-aqua/quisp/blob/87838e9d8ba402027318270d6ef84407c805f733/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L944)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

why you set this 1?
</blockquote></details>

Oh, I mistakenly pushed this change. But I found lres represents index (==0), but enough resource clause should have the number of required resource at second argument. So this should be fixed at 1, but let me fix it in different branch.

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272#-:-MibFFGD-U8Xk7XMcBFk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/272)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 944 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/272#-MibAJKv8ddzxRPNr5KV:-MibWoRI9xnCQ1mUBbQS:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/87838e9d8ba402027318270d6ef84407c805f733/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L944)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

ah, that's right.  
</blockquote></details>

Done.

**Pull request merged**
