### PR TITLE
Change the error tracking method from error basis to graph state stabilizer 

### PR DESCRIPTION
**Pull request by Naphann**
The graph state stabilizer simulation is implemented from this paper by S. Anders et al https://arxiv.org/abs/quant-ph/0504117

This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 7 files at r2, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 221 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/367#-MuUZEzd1ol6fpzlBEaA:-MuUZEzd1ol6fpzlBEaB:bqrabmg) ([raw file](https://github.com/sfc-aqua/quisp/blob/817d2b4e2496de1d6b1d0ebdbfb1926afedf1025/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L221)):*
> ```objc
>   virtual bool Zpurify(IStationaryQubit *resource_qubit) = 0;
> 
>   virtual void CNOTGate(IStationaryQubit *control_qubit) = 0;
> ```

method names should be `camelCase`

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 221 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/367#-MuUZEzd1ol6fpzlBEaA:-MuV7X_74FGarUv2Iqfr:bylrgxy) ([raw file](https://github.com/sfc-aqua/quisp/blob/817d2b4e2496de1d6b1d0ebdbfb1926afedf1025/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L221)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

method names should be `camelCase`
</blockquote></details>

I fixed them

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 575 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/367#-MuV7xcOAA7kjP_L-DgE:-MuV7xcOAA7kjP_L-DgF:b-qqvedq) ([raw file](https://github.com/sfc-aqua/quisp/blob/e60426f0011421a8af65edaeae8b57177c14e198/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L575)):*
> ```cpp
>   applyMemoryError();
>   check_and_cast<StationaryQubit *>(resource_qubit)->applyMemoryError();
>   /*Target qubit*/ this->CNOT_gate(resource_qubit /*controlled qubit*/);
> ```

for this one, I didn't intend to change it but I accidently changed it some commits ago. And surprisingly the tests didn't catch them... Need to recheck the tests

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 173 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/367#-MuiLT8M5VvE6iYSuVb_:-MuiLT8M5VvE6iYSuVba:bsteewy) ([raw file](https://github.com/sfc-aqua/quisp/blob/e60426f0011421a8af65edaeae8b57177c14e198/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L173)):*
> ```objc
>   virtual void applyRightClifford(types::CliffordOperator op) = 0;
>   virtual bool isNeighbor(IStationaryQubit *another_qubit) = 0;
>   virtual void addEdge(IStationaryQubit *another_qubit) = 0;
> ```

which module calls these methods? it seems this IStationaryQubit interface is tightly coupled with the backend. we should uncouple IStationaryQubit and the graph state stabilizer mechanism if we can.

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 173 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/367#-MuiLT8M5VvE6iYSuVb_:-MuiUHaD200bGPKAOFTV:b2r3yw1) ([raw file](https://github.com/sfc-aqua/quisp/blob/e60426f0011421a8af65edaeae8b57177c14e198/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L173)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

which module calls these methods? it seems this IStationaryQubit interface is tightly coupled with the backend. we should uncouple IStationaryQubit and the graph state stabilizer mechanism if we can.
</blockquote></details>

I was planning to address that in the next PR but fixed it now.

**Review by zigen — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367#-:-MuxHyD8APLK2nZBeGAL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367#-:-MuyIu5E0zhk4O-2yg-1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

**Review by zigen — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367#-:-Muz1ugpDt3h1dVN67h3:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Chibikuri and @zigen)

**Review by zigen — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/367)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann)

**Pull request merged**
