### PR TITLE
Integrate Message Exchange (Purification/Entanglement Swapping) into RuleSet and Runtime

### LINKED ISSUE #98: Implement at least an application for checking if the entanglement swapping is working properly.
# What to do?
related issues #97 
- Need to implement an application to send a connection tear down packet.

### LINKED ISSUE #424: `parent_ruleset_id` is no longer used.
We can remove this. 
https://github.com/sfc-aqua/quisp/blob/53cf03ad97fc092c2961de26ead2ba8a2c48428f/quisp/rules/Rule.h#L25

### PR DESCRIPTION
**Pull request by Naphann**
Summary of what has changed:

1. Introduce new states for BSA to handle photons from only one side.
2. A Rule now contains `send_tag` and `receive_tag` instead of `shared_tag`.
3. Introduce new concepts of `sequence_number`
  - A `sequence_number` is a number assigned to each local half of Bell pairs in the order they are assigned to the Rules.
  - It is used to specify which Bell pair a message from other nodes is referring to
5. Introduce 2 new clauses and actions:
  - PurificationCorrelationClause and  PurificationCorrelation(Action)
  - SwappingCorrectionClause and SwappingCorrection(Action)
6. introduce new instructions:
  -  measurement and store result into specified bit-index of int
  - get/delete messages
  - get qubit by sequence_number
  - bitwise_and/or/xor
  - promote 
7. simulation tests for entanglement swapping

This PR closes #98 and closes #424

unfinished tasks
- [x] rebase to make each commit self-contained and has meaning

defer to later PR
- write minimum tests for each instruction
- write tests for handling every possible case for BSA (might be in other PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 40 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 40 of 59 files reviewed, 4 unresolved discussions (waiting on @Naphann)

___
*[`quisp/messages/entanglement_swapping_messages.msg` line 38 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPFxOX30FDdNSkv31RW:-NPFxOX30FDdNSkv31RX:bbrd3ud) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/messages/entanglement_swapping_messages.msg#L38)):*
> ```
>     int operation_type; // when this would reach the destination
>     int new_partner_qnic_index;
>     int new_partner_qnic_address;
> ```

I think we don't need qnic information
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 42 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG19Tg557XvJwNxYK2:-NPG19Tg557XvJwNxYK3:b7zaz5) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L42)):*
> ```objc
> 
> namespace quisp::modules {
> // using pur_result_table::PurificationResultData;
> ```

you can remove it
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 21 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG3umFEKrSpHIEe8yJ:-NPG3umFEKrSpHIEe8yK:bi0uif7) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L21)):*
> ```cpp
> #include "messages/link_generation_messages_m.h"
> #include "messages/purification_messages_m.h"
> #include "modules/PhysicalConnection/BSA/types.h"
> ```

"messages/classical_messages.h" seems enough
___
*[`quisp/runtime/def_instructions.h` line 12 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG1vn258Fxazs_8Nl0:-NPG1vn258Fxazs_8Nl1:b-s1yf3g) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/runtime/def_instructions.h#L12)):*
> ```objc
> // X-macro pattern
> // https://quuxplusone.github.io/blog/2021/02/01/x-macros/
> #include <sys/_types/_u_int32_t.h>
> ```

you mean `#include <cstdint>`? 
this file will be expanded again and again, so this line should be in `types.h` or `opcode.h`

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 59 files at r1, 8 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 7 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 11 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPLmfCu8MgrwhE0qPDz:-NPLmfCu8MgrwhE0qPE-:b-o73kvt) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L11)):*
> ```objc
> 
> #include <omnetpp.h>
> #include <omnetpp/simtime.h>
> ```

you already imported omnetpp.h, so you don't need to include this.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 172 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPLncxmBLn5AL23Xysx:-NPLncxmBLn5AL23Xysy:b-2fr5v) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L172)):*
> ```cpp
>   auto partner_address = bsa_result->getNeighborAddress();
>   auto &emitted_indices = emitted_photon_order_map[{type, qnic_index}];
>   auto indices_copy = emitted_indices;
> ```

I think we can remove this?
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN3TAPBDourIzGhspm:b-3xfw6c) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
> ```cpp
>     INSTR_GATE_CNOT_QubitId_QubitId_{{q0, q1}},
>     INSTR_MEASURE_RegId_int_QubitId_Basis_{{op_left, 0, q0, Basis::X}},
>     INSTR_MEASURE_RegId_int_QubitId_Basis_{{op_left, 1, q1, Basis::Z}},
> ```

op_right?

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 7 unresolved discussions (waiting on @zigen)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN4Tqa6QBnfI2ej9DM:bkka502) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

op_right?
</blockquote></details>

left or right doesn't really matter. I intentionally put left here so we only perform correction at one node. But the correction will be Y (which I added it).

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 7 unresolved discussions (waiting on @Naphann)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN7OGh-NZk5-2kB1f8:b5hal8w) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

left or right doesn't really matter. I intentionally put left here so we only perform correction at one node. But the correction will be Y (which I added it). 
</blockquote></details>

ah okay so put both results into one register and send the value to both nodes.
so then we don't need op_right any more?

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 7 unresolved discussions (waiting on @zigen)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN7yI_-Jx7UQ744MoH:b-nw8v8f) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

ah okay so put both results into one register and send the value to both nodes.
so then we don't need op_right any more?
</blockquote></details>

Not really, we send measurement results to the left node and always send 0 (do nothing) to the right node.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 6 unresolved discussions (waiting on @Naphann)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN8rX8-fy6OPTCjSZV:bwwdkw6) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Not really, we send measurement results to the left node and always send 0 (do nothing) to the right node. 
</blockquote></details>

okay so both node just receive it and operate it without considering the node is left or right.

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 6 unresolved discussions (waiting on @zigen)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN9Mm44M5MYKnx2z36:b-l0sicd) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

okay so both node just receive it and operate it without considering the node is left or right. 
</blockquote></details>

That's correct. They operate on the correction and update their qubits to their new partner.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 44 of 71 files reviewed, 6 unresolved discussions (waiting on @Naphann)

___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 319 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPN3TAPBDourIzGhspl:-NPN9g5PE9DmPUxz7HM7:b-jglklx) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L319)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

That's correct. They operate on the correction and update their qubits to their new partner. 
</blockquote></details>

I remember it's the original behavior. I totally forgot it. thanks

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 20 of 78 files reviewed, 6 unresolved discussions (waiting on @zigen)

___
*[`quisp/messages/entanglement_swapping_messages.msg` line 38 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPFxOX30FDdNSkv31RW:-NPQjmNf1Us-BxHX8lTu:brpmqc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/messages/entanglement_swapping_messages.msg#L38)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think we don't need qnic information
</blockquote></details>

removed.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 42 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG19Tg557XvJwNxYK2:-NPQjpRmBXEsH8dcgFzv:brpmqc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L42)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you can remove it
</blockquote></details>

removed.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 11 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPLmfCu8MgrwhE0qPDz:-NPQjoHB6QqoKtV_rZoh:brpmqc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L11)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you already imported omnetpp.h, so you don't need to include this.
</blockquote></details>

removed.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 21 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG3umFEKrSpHIEe8yJ:-NPQjqYgE-r3L6Cu1ZFA:bj14758) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L21)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

"messages/classical_messages.h" seems enough
</blockquote></details>

I import only that now in header file.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 172 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPLncxmBLn5AL23Xysx:-NPQjv6T8CS6oGJTyzjz:brpmqbp) ([raw file](https://github.com/sfc-aqua/quisp/blob/c861096c2948f7862ded2573989b11b68ac6e4b7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L172)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think we can remove this?
</blockquote></details>

removed 
___
*[`quisp/runtime/def_instructions.h` line 12 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPG1vn258Fxazs_8Nl0:-NPN4rgg2eqpwojLvq-l:brpmqc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/ce885444b6d5156210c0c00571ae3ceb9dbe551e/quisp/runtime/def_instructions.h#L12)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you mean `#include <cstdint>`? 
this file will be expanded again and again, so this line should be in `types.h` or `opcode.h` 
</blockquote></details>

removed.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 59 files at r1, 9 of 26 files at r2, 21 of 31 files at r3, 16 of 18 files at r4, 4 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 76 of 78 files reviewed, 2 unresolved discussions (waiting on @Chibikuri, @Naphann, and @res6idue)

___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 156 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPS82hmDvnPAKH0wLtD:-NPS82hmDvnPAKH0wLtE:b1xrqhd) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L156)):*
> ```objc
>     pkt->setNewPartner(new_partner_addr.val);
>     rule_engine->send(pkt, "RouterPort$o");
>     std::cout << "swap at: " << rule_engine->parentAddress << " w/seq_no  " << sequence_number << '\n';
> ```

should remove this? or later replace it by logger?
___
*[`quisp/runtime/Runtime.cc` line 195 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPS8ssGCRerrXDS0J3L:-NPS8ssGCRerrXDS0J3M:b-golxa6) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/runtime/Runtime.cc#L195)):*
> ```cpp
>   sequence_number_to_qubit[{new_partner_addr, next_rule_id, next_rule_sequence_number}] = qubit_record;
>   qubit_to_sequence_number[qubit_record] = {new_partner_addr, next_rule_id, next_rule_sequence_number};
>   std::cout << "promote from " << partner_addr << " to " << new_partner_addr << " seq_no " << next_rule_sequence_number << '\n';
> ```

should we remove it?

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 77 of 78 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @Naphann, and @res6idue)

___
*[`quisp/runtime/def_instructions.h` line 94 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPSCyB-4OKfRwOqxtkK:-NPSCyB-4OKfRwOqxtkL:b-f092yx) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/runtime/def_instructions.h#L94)):*
> ```objc
> 
> // message operations
> INSTR(GET_MESSAGE_SEQ, RegId /* read: message index */, RegId /* write: sequence number */)
> ```

I want to stick with `write <- read` format as other instructions

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 71 of 79 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @res6idue, and @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 156 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPS82hmDvnPAKH0wLtD:-NPSHkQS7dc1XQIe2kMm:b-ep5ahk) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L156)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should remove this? or later replace it by logger?
</blockquote></details>

Oh right, I forgot. Removed.
___
*[`quisp/runtime/def_instructions.h` line 94 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPSCyB-4OKfRwOqxtkK:-NPSHpSR7zq9xFB2Umm0:bh8t5mr) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/runtime/def_instructions.h#L94)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I want to stick with `write <- read` format as other instructions
</blockquote></details>

That makes sense. Fixed
___
*[`quisp/runtime/Runtime.cc` line 195 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPS8ssGCRerrXDS0J3L:-NPSHyvc15IKy65Yv_zU:b14dm40) ([raw file](https://github.com/sfc-aqua/quisp/blob/de59577d04e7c193f4556b4481690e694d4f88a6/quisp/runtime/Runtime.cc#L195)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should we remove it?
</blockquote></details>

yes, I forgot. Removed.

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 18 files at r4, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504#-:-NPUxLUIEHr9QCr7USXS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri and @res6idue)

**Review by res6idue — COMMENTED** [review]
> Reviewed 13 of 59 files at r1, 9 of 26 files at r2, 9 of 31 files at r3, 13 of 18 files at r4, 2 of 4 files at r5, 2 of 5 files at r6, 1 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by res6idue — CHANGES_REQUESTED** [review]
> Reviewed 1 of 59 files at r1, 1 of 26 files at r2, 7 of 31 files at r3, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/rules/Clause.h` line 56 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPbvvVj0SuWVOCEIJJW:-NPbvvVj0SuWVOCEIJJX:bz9sjew) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/rules/Clause.h#L56)):*
> ```objc
>   PurificationCorrelationClause(json serialized) { deserialize_json(serialized); }
>   PurificationCorrelationClause(int partner_address, int shared_rule_tag);
>   const std::string name = "purification_correlation";
> ```

Where is this variable used?
___
*[`quisp/rules/Clause.h` line 66 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPbw3--AFmSxJD8QCdt:-NPbw3--AFmSxJD8QCdu:b5rcw3q) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/rules/Clause.h#L66)):*
> ```objc
>   SwappingCorrectionClause(json serialized) { deserialize_json(serialized); }
>   SwappingCorrectionClause(int swapper_address, int shared_rule_tag);
>   const std::string name = "swapping_correction";
> ```

Same for this case

**Review by res6idue — CHANGES_REQUESTED** [review]
> Reviewed 4 of 59 files at r1, 1 of 26 files at r2, 3 of 31 files at r3, 2 of 18 files at r4, 1 of 4 files at r5, 3 of 5 files at r6, 6 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/runtime/Runtime.h` line 83 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPcAUQ3--pGEN0jU4RQ:-NPcAUQ3--pGEN0jU4RR:bgjtx6c) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/runtime/Runtime.h#L83)):*
> ```objc
>     virtual void sendLinkTomographyResult(const unsigned long ruleset_id, const Rule& rule, const int action_index, const QNodeAddr partner_addr, int count,
>                                           MeasurementOutcome outcome, int max_count, Time start_time) = 0;
>     // TODO: change to this
> ```

I couldn't understand what this comment meant to say. Does it mean that 
___
*[`quisp/runtime/Runtime.cc` line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPcB2fW8FvhpAPenpO1:-NPcB2fW8FvhpAPenpO2:bc0avtu) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/runtime/Runtime.cc#L387)):*
> ```cpp
>   if (qubit == nullptr) return;
>   if (trash_qubit == nullptr) return;
>   int result = callback->purifyZ(qubit, trash_qubit) ? 1 : 0;
> ```

Why don't we write this code like purifyX or purifyZ ?
```c++
int result = callback->purifyZ(qubit, trash_qubit);
```

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: 78 of 79 files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @res6idue, and @zigen)

___
*[`quisp/rules/Clause.h` line 56 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPbvvVj0SuWVOCEIJJW:-NPemLNC9KRl-r3PtmH9:b-ibrjv5) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/rules/Clause.h#L56)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Where is this variable used?
</blockquote></details>

Conditions and actions always have a name put in the serialization to/from JSON, it helps with the debugging and testing. But it doesn't serve any direct purposes right now.
___
*[`quisp/rules/Clause.h` line 66 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPbw3--AFmSxJD8QCdt:-NPemQ6t04WW913DNCjf:bk17593) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/rules/Clause.h#L66)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Same for this case
</blockquote></details>

same as the earlier comment.
___
*[`quisp/runtime/Runtime.h` line 83 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPcAUQ3--pGEN0jU4RQ:-NPemRuyEBO4uOFOERgg:b-jiweg9) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/runtime/Runtime.h#L83)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I couldn't understand what this comment meant to say. Does it mean that 
</blockquote></details>

We would want to redo the tomography message and its execution to use message passing 
related issues: https://github.com/sfc-aqua/quisp/issues/513, https://github.com/sfc-aqua/quisp/issues/104
___
*[`quisp/runtime/Runtime.cc` line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPcB2fW8FvhpAPenpO1:-NPenZWYAn5z--3dbJfj:b-7ql1td) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/runtime/Runtime.cc#L387)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Why don't we write this code like purifyX or purifyZ ?
```c++
int result = callback->purifyZ(qubit, trash_qubit);
```
</blockquote></details>

fixed

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> Reviewed 18 of 59 files at r1, 11 of 26 files at r2, 19 of 31 files at r3, 15 of 18 files at r4, 4 of 4 files at r5, 5 of 5 files at r6, 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504#-:-NPeq-u76yRXGYa-6q2I:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @res6idue)

**Review by res6idue — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

___
*[`quisp/runtime/Runtime.h` line 83 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/504#-NPcAUQ3--pGEN0jU4RQ:-NPfORla3UTDnhMlJJ6w:b-shgv8p) ([raw file](https://github.com/sfc-aqua/quisp/blob/05d03df94c65e46ebdce2ccb50ab1428eac4ff67/quisp/runtime/Runtime.h#L83)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

We would want to redo the tomography message and its execution to use message passing 
related issues: https://github.com/sfc-aqua/quisp/issues/513, https://github.com/sfc-aqua/quisp/issues/104
</blockquote></details>

Ok, sorry I now understand

**Review by res6idue — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504#-:-NPfOZ5PEGmmRwPFbiQq:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Review by res6idue — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)

**Comment by lmpawan10** [comment]
In the following pull request, inside QRSA/HardwareMonitor/HardwareMonitor.cc, at line 835 and 840 inside "else if (purification_type == 1031)" block, it seems that the purification protocol has to be DSDA and DSDA_INV respectively in place of DSSA and DSSA_INV. Can you check on it? @Naphann @zigen @res6idue 
If that is so, I will make changes to it accordingly in the next pull request.

**Pull request merged**
