### PR TITLE
move performance doc to wiki

### PR DESCRIPTION
**Pull request by zigen**
remove performance analysis doc, see wiki

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/305)

### CODE REVIEW

**Review by Chibikuri — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Comment by zigen** [comment]
@Chibikuri did you forget to approve? or still reviewing?

**Review by Chibikuri — APPROVED** [review]
I forgot to approve. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/305#-:-MntqdJx6DKLDs5GzVOe:bndvxrt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Comment by zigen** [comment]
thank you for reviewing!

**Pull request merged**
