### PR TITLE
Add dumbell MM and MIM network

### PR DESCRIPTION
**Pull request by TSarkar99**
Added dumbell MM and MIM network topologies.
#121 

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
thanks for contributing!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeZB5ej9vakFAtVnooR:bbatuq6)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TSarkar99)

___
*[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeZBCo91xzV92oUOc-g:bsjwfet) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):*
> ```
>         **.Speed_of_light_in_fiber = 205336.986301 km;
>     submodules:
>         EndNode1[1]: QNode {
> ```

do we need to use vector type?
https://doc.omnetpp.org/omnetpp/manual/#sec:ned-ref:submodules

IMO, it's ok to write like this
```
EndNode1: QNode {
```

**Comment by zigen** [comment]
@TSarkar99 could you put the related issue to the PR description?
https://github.com/sfc-aqua/quisp/issues/121

**Comment by TSarkar99** [comment]
> @TSarkar99 could you put the related issue to the PR description?
> #121

Sure, I will do that.

**Comment by TSarkar99** [comment]
> thanks for contributing!
> 
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeZB5ej9vakFAtVnooR:bbatuq6)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TSarkar99)
> 
> _[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeZBCo91xzV92oUOc-g:bsjwfet) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):_
> 
> > ```
> >         **.Speed_of_light_in_fiber = 205336.986301 km;
> >     submodules:
> >         EndNode1[1]: QNode {
> > ```
> 
> do we need to use vector type?
> https://doc.omnetpp.org/omnetpp/manual/#sec:ned-ref:submodules
> 
> IMO, it's ok to write like this
> 
> ```
> EndNode1: QNode {
> ```

**Comment by zigen** [comment]
hey, you don't need to close the PR!

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: 0 of 2 files reviewed, 2 unresolved discussions

___
*[quisp/networks/topology_dumbell_network.ned, line 82 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZE6Gi5XCRXZag9Io2:-MeZE6Gi5XCRXZag9Io3:b-npguof) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L82)):*
> ```
>         EndNode2[0].quantum_port_receiver++ <--> QuantumChannel {  distance = 10km; } <--> repeater1[0].quantum_port++;
>         EndNode3[0].quantum_port_receiver++ <--> QuantumChannel {  distance = 10km; } <--> repeater1[0].quantum_port++;
>         repeater1[0].quantum_port++ <--> QuantumChannel {  distance = 10km; } <--> repeater2[0].quantum_port++;
> ```
```
repeater1[0].quantum_port++ <--> QuantumChannel {  distance = 10km; } <--> repeater2[0].quantum_port++;
```
Here you would have an error. Either repeater 1 or repeater 2 should be a quantum port receiver.

**Comment by TSarkar99** [comment]
> thanks for contributing!
Pleasures :)
> 
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeZB5ej9vakFAtVnooR:bbatuq6)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TSarkar99)
> 
> _[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeZBCo91xzV92oUOc-g:bsjwfet) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):_
> 
> > ```
> >         **.Speed_of_light_in_fiber = 205336.986301 km;
> >     submodules:
> >         EndNode1[1]: QNode {
> > ```
> 
> do we need to use vector type?
> https://doc.omnetpp.org/omnetpp/manual/#sec:ned-ref:submodules
> 
> IMO, it's ok to write like this
> 
> ```
> EndNode1: QNode {
> ```
Yes, it works writing like what you have suggested. Should I change my code to what you suggested then?

**Comment by TSarkar99** [comment]
> hey, you don't need to close the PR!

Sorry, my bad

**Review by zigen — CHANGES_REQUESTED** [review]
No problem!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeZO6Bk11mYfena5S2y:blyphgc)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @TSarkar99)

___
*[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeZNEhd6PB1ByJJloew:bvlz4xk) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):*
<details><summary><i>Previously, TSarkar99 (Tanmay Sarkar) wrote…</i></summary><blockquote>

Yes, it works writing like what you have suggested. Should I change my code to what you suggested then?
</blockquote></details>

If there's no reason to write your way, you should write an easier way.
Finally, it helps us to change it when we want to change this network or configuration in the future.

**Comment by TSarkar99** [comment]
> No problem!
> 
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeZO6Bk11mYfena5S2y:blyphgc)_ status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @TSarkar99)
> 
> _[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeZNEhd6PB1ByJJloew:bvlz4xk) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):_
> 
> Previously, TSarkar99 (Tanmay Sarkar) wrote…
> > Yes, it works writing like what you have suggested. Should I change my code to what you suggested then?
> 
> If there's no reason to write your way, you should write an easier way.
> Finally, it helps us to change it when we want to change this network or configuration in the future.

Okay. I have made the changes.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: all files reviewed, 2 unresolved discussions (waiting on @TSarkar99)

___
*[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeiSmkQ3UxwJgV-7Lnw:bl0f0qt) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):*
<details><summary><i>Previously, TSarkar99 (Tanmay Sarkar) wrote…</i></summary><blockquote>

Okay. I have made the changes.
</blockquote></details>

good! now it's totally clean!
___
*[quisp/networks/topology_dumbell_network.ned, line 59 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeiSv7_35lRla6pGSOq:-MeiSv7_35lRla6pGSOr:b21lbio) ([raw file](https://github.com/sfc-aqua/quisp/blob/01af333a1b12cbd5e27de90e9b34c57a3a3a5e37/quisp/networks/topology_dumbell_network.ned#L59)):*
> ```
>             @display("i=device/pc;p=421,61");
>         }
>         repeater1: QNode {
> ```

`EndNode` is PascalCase, but here `repeater` starts with lower case.
how about `Repeater1` for consistency and readability?

**Comment by TSarkar99** [comment]
> > Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)_ status: all files reviewed, 2 unresolved discussions (waiting on @TSarkar99)
> 
> _[quisp/networks/topology_dumbell_network.ned, line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeZBCo91xzV92oUOc-f:-MeiSmkQ3UxwJgV-7Lnw:bl0f0qt) ([raw file](https://github.com/sfc-aqua/quisp/blob/4fe87d8738c627c5c3423c47881479e78e54702b/quisp/networks/topology_dumbell_network.ned#L29)):_
> 
> Previously, TSarkar99 (Tanmay Sarkar) wrote…
> good! now it's totally clean!
> 
> _[quisp/networks/topology_dumbell_network.ned, line 59 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeiSv7_35lRla6pGSOq:-MeiSv7_35lRla6pGSOr:b21lbio) ([raw file](https://github.com/sfc-aqua/quisp/blob/01af333a1b12cbd5e27de90e9b34c57a3a3a5e37/quisp/networks/topology_dumbell_network.ned#L59)):_
> 
> > ```
> >             @display("i=device/pc;p=421,61");
> >         }
> >         repeater1: QNode {
> > ```
> 
> `EndNode` is PascalCase, but here `repeater` starts with lower case.
> how about `Repeater1` for consistency and readability?

Done.

**Review by Chibikuri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @TSarkar99 and @zigen)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeihD9KCGik_iE3psD3:-MeihD9KCGik_iE3psD4:b-z2yghm) (no related file):*
I confirmed both MIM and MM are working properly on my docker environment.

---

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @TSarkar99)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeihD9KCGik_iE3psD3:-MeilkZs8oZNMckzyzQJ:b-az3zgk) (no related file):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

I confirmed both MIM and MM are working properly on my docker environment.
</blockquote></details>

I confirmed it works on my MacOS. 

---

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242#-:-MeilueI5fMyjk0PnZ0z:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @TSarkar99)

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @TSarkar99)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/242#-MeihD9KCGik_iE3psD3:-Meilyua9OLj7nh91a7c:b3geptr) (no related file):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I confirmed it works on my MacOS. 
</blockquote></details>

@chibikuri if there's no problem, click "LGTM" button and publish it.

---

**Review by Naphann — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @TSarkar99)

**Review by zigen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @TSarkar99)

**Pull request merged**
