### PR TITLE
Active ruleset generation in RuleEngine

### PR DESCRIPTION
**Pull request by Chibikuri**
What I did in this PR
- [x] Add function to build up ActiveRuleSet in RuleEngine and tests for it
- [x] Modified Qnic reservation method to fix [bug](https://github.com/sfc-aqua/quisp/issues/384)
- [x] Fixed several clauses and actions to fit the current ActiveRuleSet

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 12 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387)* status: 12 of 28 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 411 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-MzybyIX4AYmnVuCq8GI:-MzybyIX4AYmnVuCq8GJ:bunncuh) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L411)):*
> ```cpp
>     if (act->purification_type == PurType::SINGLE_X) {
>       // Purification(X)
>       auto active_action = new PurifyAction(ruleset_id, rule_id, true, false, 1, partner_addr, qnic_type, qnic_id, 0, 1);
> ```

you don't need to assign it. just `return new PurifyAction(...)`
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 430 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-Mzyc5Bx9-vijaHu3jeM:-Mzyc5Bx9-vijaHu3jeN:b-cn63j1) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L430)):*
> ```cpp
>     }
>     if (act->purification_type == PurType::DSSA) {
>       // DoubleSelectionSingleAction
> ```

remove useless comments.

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387)* status: 12 of 28 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 383 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-MzycVShEBQZxY6zkD9u:-MzycVShEBQZxY6zkD9v:bfrfia0) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L383)):*
> ```cpp
>       // EnoughResourceClause(partner_address, num_resource)
>       auto *resource_clause = new EnoughResourceClause(cond->partner_address, cond->num_resource);
>       active_condition->addClause(resource_clause);
> ```

also here, you don't need to assign it. just `active_condition->addClause(new EnoughResourceClause(cond->partner_address, cond->num_resource));`
if the class name is not intuitive, you might need to assign it to some variable.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 385 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-MzycvcB3kwxM0zGcbZf:-MzycvcB3kwxM0zGcbZg:b-w5j54l) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L385)):*
> ```cpp
>       active_condition->addClause(resource_clause);
>     } else if (auto *cond = dynamic_cast<MeasureCountConditionClause *>(clause.get())) {
>       // MeasureCountClause (num_measure)
> ```

the comment says something obvious. so you should not write this comment.

**Review by zigen — COMMENTED** [review]
> Reviewed 16 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri)

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387)* status: 27 of 28 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 385 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-MzycvcB3kwxM0zGcbZf:-N-GIo8TESpl3SnyY3y3:b-hn1ppj) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L385)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

the comment says something obvious. so you should not write this comment.
</blockquote></details>

Right, removed.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 411 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-MzybyIX4AYmnVuCq8GI:-N-GIqQqAt2qfYdDZxNd:b1b7bz3) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L411)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need to assign it. just `return new PurifyAction(...)`
</blockquote></details>

Fixed this.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 430 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/387#-Mzyc5Bx9-vijaHu3jeM:-N-GIt5U5NR-dBzMdovC:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/f55b445441b7c65e6c1acce2cc86e52c2bc45ae9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L430)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

remove useless comments.
</blockquote></details>

Done.

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/387#-:-N-L05u10IoJsBrRdZDq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
