### PR TITLE
RuleSet serialization

### PR DESCRIPTION
**Pull request by Chibikuri**
This PR aims to add functions for RuleSet serialization.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)

### CODE REVIEW

**Review by zigen — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

___
*[json, line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuO0nDu6K8KmpvsW0CN:-MuO0nDu6K8KmpvsW0CO:b-r7chix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c9b15af7e22b0d8fae063746be40585c65382d4b/json#L1)):*
> ```
> Subproject commit 4f8fba14066156b73f1189a2b8bd568bde5284c5
> ```

https://github.com/nlohmann/json/releases/tag/v3.10.5

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/makefrag, line 35 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZkE89BxzK2hITYaEN:-MuZkE89BxzK2hITYaEO:b-zdky3q) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/makefrag#L35)):*
> ```
> 
> # include path for json
> INCLUDE_PATH+=-I. -I$(PROJ_ROOT)/json/include/
> ```

you don't need `-I.` because you already added it.
___
*[quisp/rules/Rule.h, line 33 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZktso3Ulsc6TBBycU:-MuZktso3Ulsc6TBBycV:bv3676v) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.h#L33)):*
> ```objc
>   void setAction(std::unique_ptr<Action> action);
>   void setNextRule(unsigned long next_rule_id);
>   json serialize();
> ```

should we specify the return type statically? 
we might need to use the "template" or something to uncouple the `json` from the `Rule` class.
I think it's okay to fix it later.
___
*[quisp/rules/Rule.cc, line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZmNtZ3yrGRN5V0Bs2:-MuZmNtZ3yrGRN5V0Bs3:b-8jpxa7) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.cc#L8)):*
> ```cpp
> namespace quisp::rules {
> 
> void Rule::setCondition(std::unique_ptr<Condition> cond) { condition.reset(cond.release()); }
> ```

why not use `std::move`

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[quisp/makefrag, line 35 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZkE89BxzK2hITYaEN:-Mu_r2uWCGUpH7QmddYR:b-ee2q8m) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/makefrag#L35)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need `-I.` because you already added it.
</blockquote></details>

Right, will remove it.
___
*[quisp/rules/Rule.h, line 33 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZktso3Ulsc6TBBycU:-Mu_rfTc8znwbb_1JpxZ:bb13lw1) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.h#L33)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should we specify the return type statically? 
we might need to use the "template" or something to uncouple the `json` from the `Rule` class.
I think it's okay to fix it later.
</blockquote></details>

Do we have any other possible returns?
___
*[quisp/rules/Rule.cc, line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZmNtZ3yrGRN5V0Bs2:-Mu_rid5-QJ0KE4uq2KP:bwcyozl) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.cc#L8)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

why not use `std::move`
</blockquote></details>

Oh, ya. Let me fix it.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[quisp/rules/Rule.h, line 33 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZktso3Ulsc6TBBycU:-Mu_z9d79Ew9dfV1OUDZ:b-im4r38) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.h#L33)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Do we have any other possible returns?
</blockquote></details>

Ah, for other serialization formats, right?

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 3 of 14 files at r2, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368#-:-MuoSMvj3amlgNVrPNMN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/rules/Clause.cc, line 2 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/368#-Muo3oXRAQzNVmjbSZN-:-Muo3oXRAQzNVmjbSZN0:b-kfvgdh) ([raw file](https://github.com/sfc-aqua/quisp/blob/e926a1f339731c71e471368818d0f66e6417499d/quisp/rules/Clause.cc#L2)):*
> ```cpp
> #include "Clause.h"
> // #include <omnetpp.h>
> ```

delete it

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/rules/Clause.cc, line 2 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/368#-Muo3oXRAQzNVmjbSZN-:-MupmIRD9XTJkByLoHg0:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/e926a1f339731c71e471368818d0f66e6417499d/quisp/rules/Clause.cc#L2)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

delete it
</blockquote></details>

Done.

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

___
*[quisp/rules/Rule.h, line 33 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/368#-MuZktso3Ulsc6TBBycU:-MusC4OV28tQzyZ6vnjO:b-e3by1v) ([raw file](https://github.com/sfc-aqua/quisp/blob/bbcfa7df195b00f9f8d9055cbe543edebbf3d6ac/quisp/rules/Rule.h#L33)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Ah, for other serialization formats, right?
</blockquote></details>

yeah we wanna another serialization format later. so I don't wanna bind the `serialize` method for json. 
here are options:
1. use "out" arg. https://godbolt.org/z/f4rKrjsoh
2. use "template" of C++
3. separate serializer from Rule class

**Pull request merged**
