### PR TITLE
Refactor sampling with weights to a function

### LINKED ISSUE #477: Refactor sampling with weights to a function.
Currently, there are a lot of places in QuISP where we need to sample with weights. A few is shown below

https://github.com/sfc-aqua/quisp/blob/d66ab324aced885901514dc993ffee5679760007/quisp/backends/ErrorTracking/Qubit.cc#L48-L68

https://github.com/sfc-aqua/quisp/blob/d66ab324aced885901514dc993ffee5679760007/quisp/backends/ErrorTracking/Qubit.cc#L78-L122

If we can have sample with weights where we can assign labels to it and then branch on that label. The code will look nicer and shorter. Also we would have only single place of error when sampling is done.

Examples: https://stackoverflow.com/questions/65377120/using-c-discrete-distribution-with-weights-taken-from-a-data-structure

### PR DESCRIPTION
**Pull request by ntanetani**
Closes #477

There were a lot of places in QuISP where we need to sample with weights. Therefore, given a weight and a label, I implemented a function that returns a random label based on the weight.

Function Name: randomSamplingWithLabelsAndWeights
Inputs: Labels(vector of **Int**), Weights(vector of double)
Output: Label(**Int**)

The key point is that the type of label is int. You can use an enum for the label; using an enum for the label improves readability and enable to use switch statement.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/backends/GraphState/Gs_backend_test.cc` line 40 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXuUjaDapOrlbPPtck:-NOXuUjaDapOrlbPPtcl:b3ym4h5) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Gs_backend_test.cc#L40)):*
> ```cpp
>   TestRNG* rng;
>   std::unique_ptr<GsBackend> backend;
>   int randomSamplingWithLabelsAndWeights(std::vector<int> labels, std::vector<double> weights) { return GraphStateQubit::randomSamplingWithLabelsAndWeights(labels, weights); }
> ```

just you can write `using GraphStateBackend::randomSamplingWithLabelsAndWeights` in GsBackend class declaration above.
___
*[`quisp/backends/GraphState/Qubit.h` line 28 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXrHdt4eWhGsM-I8u5:-NOXrHdt4eWhGsM-I8u6:bh1qsit) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.h#L28)):*
> ```objc
> using Eigen::MatrixPower;
> using Eigen::MatrixXd;
> using std::vector;
> ```

you don't need this if you write `std::vector` below. so remove it.
___
*[`quisp/backends/GraphState/Qubit.h` line 64 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXumP346fjSQnw1Fou:-NOXumP346fjSQnw1Fov:b-s2j08j) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.h#L64)):*
> ```objc
>   EigenvalueResult noiselessMeasureX(EigenvalueResult forced_result) override;
> 
>   static int randomSamplingWithLabelsAndWeights(std::vector<int> labels, std::vector<double> weights);
> ```

the name seems too long. I think `sample` is enough for this context.
___
*[`quisp/backends/GraphState/Qubit.cc` line 4 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXrreh9cilsmQtX1QU:-NOXrreh9cilsmQtX1QV:bjzkfb5) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L4)):*
> ```cpp
> #include <stdexcept>
> #include <string>
> #include <vector>
> ```

you don't have to include these string and vector headers because you already included in the "Qubit.h"
___
*[`quisp/backends/GraphState/Qubit.cc` line 244 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXssNR1lJKVGt-7wFw:-NOXssNR1lJKVGt-7wFx:bosyr3z) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L244)):*
> ```cpp
> int GraphStateQubit::randomSamplingWithLabelsAndWeights(std::vector<int> labels, std::vector<double> weights) {
>   // Gives a random double between 0.0 ~ 1.0
>   double rand = (double)std::rand() / RAND_MAX;
> ```

use `backend->dblrand()` because we want to fix the seed value and also for unit test.
so this function must be a non-static method.
___
*[`quisp/backends/GraphState/Qubit.cc` line 248 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXtlelCEFa63Rn_3EH:-NOXtlelCEFa63Rn_3EI:bt8u8yc) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L248)):*
> ```cpp
> 
>   if (labels.size() != weights.size() + 1) {
>     throw std::runtime_error("Length of labels must be 1 longer than length of weights");
> ```

use `error` 
https://doc.omnetpp.org/omnetpp/api/classomnetpp_1_1cSimpleModule.html#af22888ea33459a0bcd483ba0c74fd607

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/backends/GraphState/Gs_backend_test.cc` line 40 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXuUjaDapOrlbPPtck:-NOXv5fn4RYSAKN6RyT6:bkfg311) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Gs_backend_test.cc#L40)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

just you can write `using GraphStateBackend::randomSamplingWithLabelsAndWeights` in GsBackend class declaration above.
</blockquote></details>

not in Gsbackend, it should be TestGsQubit.

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/backends/GraphState/Qubit.cc` line 62 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXv_Vk94yncXj8CQLN:-NOXv_Vk94yncXj8CQLO:b-wlmqr) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L62)):*
> ```cpp
>   }
> 
>   enum Labels { No_err, X_err, Z_err, Y_err };
> ```

`NO_ERR`, `X_ERR`, `Z_ERR`, `Y_ERR` are better for naming convention

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 8 unresolved discussions (waiting on @ntanetani and @zigen)

___
*[`quisp/backends/GraphState/Qubit.h` line 64 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOXumP346fjSQnw1Fou:-NOY1Mv_8tXWRorwhKkL:b-9u3te1) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.h#L64)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

the name seems too long. I think `sample` is enough for this context.
</blockquote></details>

sample function is general, I think it's best to be put in utility than in backends or in qubits. Think of this as a rng with more control, it shouldn't belong here.
___
*[`quisp/backends/GraphState/Qubit.cc` line 247 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOY1xep9ITZlxzImctO:-NOY1xep9ITZlxzImctP:b-hi4v9o) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L247)):*
> ```cpp
>   int index = 0;
> 
>   if (labels.size() != weights.size() + 1) {
> ```

to make it general, labels and weights should have the same size. We want this to be general and use everywhere in QuISP.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 4 unresolved discussions (waiting on @ntanetani)

___
*[`quisp/utils/UtilFunctions.h` line 6 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOojxtx3rgX5Xm85iRR:-NOojxtx3rgX5Xm85iRS:b-n2cqex) ([raw file](https://github.com/sfc-aqua/quisp/blob/90a9adb1ac8db35f642a1d7f8bc3bc006c3ab153/quisp/utils/UtilFunctions.h#L6)):*
> ```objc
> 
> namespace quisp {
> namespace utilFunctions {
> ```

in C++17, we can write `namespace quisp::utilFunctions {`
and also namespace identifier should be snake case.
___
*[`quisp/utils/UtilFunctions.h` line 10 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOokVRc4Lj316tCz9B0:-NOokVRc4Lj316tCz9B1:b-2c9lv4) ([raw file](https://github.com/sfc-aqua/quisp/blob/90a9adb1ac8db35f642a1d7f8bc3bc006c3ab153/quisp/utils/UtilFunctions.h#L10)):*
> ```objc
> 
> template <typename Label>
> Label sample(std::map<double, Label> weights) {
> ```

add comment for this function.
___
*[`quisp/utils/UtilFunctions.h` line 12 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOojgMw-Ld2eACvWkr8:-NOojgMw-Ld2eACvWkr9:bspi21b) ([raw file](https://github.com/sfc-aqua/quisp/blob/90a9adb1ac8db35f642a1d7f8bc3bc006c3ab153/quisp/utils/UtilFunctions.h#L12)):*
> ```objc
> Label sample(std::map<double, Label> weights) {
>   // Gives a random double between 0.0 ~ 1.0
>   std::unique_ptr<IRandomNumberGenerator> rng;
> ```

I think we cannot create rng.
we should pass the rng or random value as an argument

**Review by ntanetani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 12 of 19 files reviewed, 4 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 247 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOY1xep9ITZlxzImctO:-NOou6u4Cfqtx9QPA0mT:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/68be309f1450ffe5760d8203e2fb594ffd78963d/quisp/backends/GraphState/Qubit.cc#L247)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

to make it general, labels and weights should have the same size. We want this to be general and use everywhere in QuISP. 
</blockquote></details>

Done.
___
*[`quisp/utils/UtilFunctions.h` line 6 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOojxtx3rgX5Xm85iRR:-NOsXUG6173vx6J29Qit:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/90a9adb1ac8db35f642a1d7f8bc3bc006c3ab153/quisp/utils/UtilFunctions.h#L6)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

in C++17, we can write `namespace quisp::utilFunctions {`
and also namespace identifier should be snake case.
</blockquote></details>

Done.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 4 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/utils/UtilFunctions.h` line 6 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOojxtx3rgX5Xm85iRR:-NOs_PSvCvnVEKNZwkm5:b-madu0o) ([raw file](https://github.com/sfc-aqua/quisp/blob/90a9adb1ac8db35f642a1d7f8bc3bc006c3ab153/quisp/utils/UtilFunctions.h#L6)):*
<details><summary><i>Previously, ntanetani (Nozomi Tanetani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

could you rename to snake_case?

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r6, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/backends/GraphState/Qubit.cc` line 64 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOszxWADN07L1UqXj-r:-NOszxWADN07L1UqXj-s:b-x1st4w) ([raw file](https://github.com/sfc-aqua/quisp/blob/8060fb015d850a0b049454da64930f5ef1546d5b/quisp/backends/GraphState/Qubit.cc#L64)):*
> ```cpp
>       {err.no_error_ceil, ErrorLabel::NO_ERR}, {err.x_error_ceil, ErrorLabel::X}, {err.z_error_ceil, ErrorLabel::Z}, {err.y_error_ceil, ErrorLabel::Y}};
> 
>   double rand = (double)std::rand() / RAND_MAX;
> ```

use `double rand = backend->dblrand()`

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/utils/UtilFunctions_test.cc` line 18 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOt-Q0sEhASJyvHOjd7:-NOt-Q0sEhASJyvHOjd8:b-im54p7) ([raw file](https://github.com/sfc-aqua/quisp/blob/8060fb015d850a0b049454da64930f5ef1546d5b/quisp/utils/UtilFunctions_test.cc#L18)):*
> ```cpp
> }
> 
> TEST(UtilFunctionsTest, mapToLabelTest2) {
> ```

you can combine these tests into one test.

**Comment by zigen** [comment]
could you rebase this?

**Review by ntanetani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 8 of 20 files reviewed, 10 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 67 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOsxLAP5M90ugAn0kDB:-NTSf9YZB33I0w3xJmj-:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/backends/GraphState/Qubit.cc#L67)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

this comment should be deleted since we make it 
</blockquote></details>

Done.
___
*[`quisp/backends/GraphState/Qubit.cc` line 76 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOswSC1COrknggzy7nA:-NTSf3Kq2CCXDqBZImVK:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/backends/GraphState/Qubit.cc#L76)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

switch statement in C++ is a fallthrough mechanism. Meaning unless you break it will execute the statement below as well.
This means everything will be applied with Clifford Y. If the error label is Z then it will get applied with Z and Y. 

Need to add break statement.
</blockquote></details>

Done.
___
*[`quisp/backends/GraphState/Qubit.cc` line 108 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOsxFWX3u1vpxHwfBZX:-NTSfBy7-9xyClxOXPbn:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/backends/GraphState/Qubit.cc#L108)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

same comment as prior switch statement
</blockquote></details>

Done.
___
*[`quisp/backends/GraphState/Qubit.cc` line 208 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOt7EGuCXciU_K9139R:-NTSfE1n1XhU9f2Z4sMn:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/backends/GraphState/Qubit.cc#L208)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

same comment about switch statement.
</blockquote></details>

Done.

**Review by zigen — COMMENTED** [review]
> Reviewed 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 8 unresolved discussions (waiting on @Naphann and @ntanetani)

**Review by zigen — COMMENTED** [review]
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 19 of 20 files reviewed, 8 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/utils/UtilFunctions.h` line 17 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NTmM5xqDlJm6yWzihPV:-NTmM5xqDlJm6yWzihPW:bkaw8bc) ([raw file](https://github.com/sfc-aqua/quisp/blob/fbdfa1dcfa692d1fa5b606dba785b0ed91de9a42/quisp/utils/UtilFunctions.h#L17)):*
> ```objc
>     It returns label which previous_label_weight < rand <= label_weight
>   Example:
>     weight = {{0.3, ErrorLabel::X}, {0.7, ErrorLabel::Z}, {1.0, ErrorLabel::Y}}}
> ```

plz update this example

**Review by ntanetani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 19 of 20 files reviewed, 8 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 62 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOswJOfDmGNcvoNUSOW:-NTqwLyZ6s5yaBrxMLDy:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/backends/GraphState/Qubit.cc#L62)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Why is weight denoted as the `ceil` value? This should be the rate, isn't it?
</blockquote></details>

Done.
___
*[`quisp/utils/UtilFunctions.h` line 23 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOsxVoqBEg5X4oN5uWO:-NTqwPMAAIho1eo3OCKY:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c15f2a95cd8590bc99ea48163f69865f5953b05e/quisp/utils/UtilFunctions.h#L23)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

`mapToLabel` doesn't convey meaning. The main job of this function is to sample. I still think `samplingWithWeights` is a better name.
Also we want to pass in weights not the ceiling itself. The calculation of ceiling is the annoying part.
</blockquote></details>

Done.
___
*[`quisp/utils/UtilFunctions.h` line 17 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NTmM5xqDlJm6yWzihPV:-NTqwOOb00HJIxH4xzZJ:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/fbdfa1dcfa692d1fa5b606dba785b0ed91de9a42/quisp/utils/UtilFunctions.h#L17)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

plz update this example
</blockquote></details>

Done.
___
*[`quisp/utils/UtilFunctions_test.cc` line 18 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NOt-Q0sEhASJyvHOjd7:-NTqwQ5x-UYEjzWBeiM3:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/8060fb015d850a0b049454da64930f5ef1546d5b/quisp/utils/UtilFunctions_test.cc#L18)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you can combine these tests into one test.
</blockquote></details>

Done.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 7 unresolved discussions (waiting on @Naphann and @ntanetani)

___
*[`quisp/utils/UtilFunctions.h` line 17 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NTmM5xqDlJm6yWzihPV:-NTrrAHm1dLhhUupXMgD:b-gpvf4a) ([raw file](https://github.com/sfc-aqua/quisp/blob/fbdfa1dcfa692d1fa5b606dba785b0ed91de9a42/quisp/utils/UtilFunctions.h#L17)):*
<details><summary><i>Previously, ntanetani (Nozomi Tanetani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

label and weight are reversed in the example.

**Review by ntanetani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 21 of 22 files reviewed, 7 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/utils/UtilFunctions.h` line 17 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NTmM5xqDlJm6yWzihPV:-NTs4ATPDfvTvKnXcK_n:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/fbdfa1dcfa692d1fa5b606dba785b0ed91de9a42/quisp/utils/UtilFunctions.h#L17)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

label and weight are reversed in the example. 
</blockquote></details>

Done.

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r3, 2 of 7 files at r4, 9 of 12 files at r8, 2 of 3 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: all files reviewed, 4 unresolved discussions (waiting on @ntanetani)

___
*[`quisp/backends/GraphState/Qubit.cc` line 190 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NUEN0BDCOCgF1P3_F0x:-NUEN0BDCOCgF1P3_F0y:b-f0gl7b) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e547c8671ba156425cac0b4bc360c2ee371429b/quisp/backends/GraphState/Qubit.cc#L190)):*
> ```cpp
>     pi_vector = pi_vector * transition_mat;
> 
>     enum class ErrorLabel { NO_ERR, X, Z, Y, Exitation, Relaxation };
> ```

typo: Excitation
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter_test.cc` line 2 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NUENe_M6CtrGPh6Gj9x:-NUENe_N1jm5IkRzJ8WU:bcn1ja2) ([raw file](https://github.com/sfc-aqua/quisp/blob/0033a939eb3be7131a164623ddc0f41e60b46a28/quisp/rules/RuleSetConverter/RuleSetConverter_test.cc#L2)):*
> ```cpp
> #include "RuleSetConverter.h"
> ```

If this file should be empty, we should delete it.
___
*[`quisp/utils/UtilFunctions_test.cc` line 8 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NUEO8lq0KZ_g4OBq25G:-NUEO8lq0KZ_g4OBq25H:b-8apqsy) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e547c8671ba156425cac0b4bc360c2ee371429b/quisp/utils/UtilFunctions_test.cc#L8)):*
> ```cpp
> using quisp::util_functions::samplingWithWeights;
> 
> TEST(UtilFunctionsTest, samplingWithWeightsTest) {
> ```

Since the function samplingWithWeights accept any label:weights meaning weights doesn't need to sum to 1, if might be a good idea to test those cases as well.

**Review by ntanetani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: 19 of 22 files reviewed, 3 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/utils/UtilFunctions_test.cc` line 8 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NUEO8lq0KZ_g4OBq25G:-NUHvFHA8aeBWrYsmRsh:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e547c8671ba156425cac0b4bc360c2ee371429b/quisp/utils/UtilFunctions_test.cc#L8)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Since the function samplingWithWeights accept any label:weights meaning weights doesn't need to sum to 1, if might be a good idea to test those cases as well.
</blockquote></details>

Done.
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter_test.cc` line 2 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/497#-NUENe_M6CtrGPh6Gj9x:-NUHteU9CB-cFShZmI_N:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/0033a939eb3be7131a164623ddc0f41e60b46a28/quisp/rules/RuleSetConverter/RuleSetConverter_test.cc#L2)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

If this file should be empty, we should delete it.
</blockquote></details>

Done.

**Review by Naphann — APPROVED** [review]
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ntanetani)

**Pull request merged**
