### PR TITLE
Connect backend and stationary qubit (new)

### PR DESCRIPTION
**Pull request by res6idue**
This PR is a rebased version of PR #388.
PR#388 was old and many changes occurred in QuISP (especially the rule engine), I created a new branch and a new PR.
What I did in this PR
- Resolved conflicts
- Adapted several parts of the code to match the current architecture
- Bug fixes

Remaining tasks

- [x] Deal with hacked functions in RuntimeCallback
- [x] Pass all unit tests
        - RealTimeController
        - ActionExecutionTest.Tomography
- [x] Run a simulation test (check whether it produces the same outputs as what we were obtaining before)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)

### CODE REVIEW

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 23 of 38 files at r1, 11 of 12 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)* status: all files reviewed, 11 unresolved discussions (waiting on @res6idue)

___
*[`quisp/backends/ErrorTracking/Backend.cc` line 27 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9U7iJBoZcMp8ke8jy:-NM9U7iJBoZcMp8ke8jz:ba9jso7) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Backend.cc#L27)):*
> ```cpp
> }
> 
> IQubit* ErrorTrackingBackend::getQubit(const IQubitId* id, std::unique_ptr<IConfiguration> conf) {
> ```

Should this be called `createQubit(...)` instead? 
I'm not sure I understand why would we have a single `getQubit` and what it does is it creates a new qubit if it doesn't already exist.

Would it be better to have `createQubit(id)` `getQubit(id)` `deleteQubit(id)`? 
- create should throw error if id already exists
- get should throw error if qubit doesn't exist
- delete should throw error if qubit doesn't exist

If we really need this behaviour maybe also add `getOrCreateQubit(id)` but this should be used very cautiously.

I think this is better when writing code and manage qubits. And I mean it should be like this for all Backend so we should change it at the interface level. 
___
*[`quisp/backends/ErrorTracking/Backend.cc` line 49 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9TfXjECDTK5bhI6aI:-NM9TfXjECDTK5bhI6aJ:bgd5fiw) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Backend.cc#L49)):*
> ```cpp
> }
> 
> IQubit* ErrorTrackingBackend::getQubit(const IQubitId* id) { return getQubit(id, getDefaultConfiguration()); }
> ```

I don't think we should have this. Unless we plan to make changes to the semantics of `ini` file. Since all qubits have its own error parameter when should this function be called?
___
*[`quisp/backends/ErrorTracking/Qubit_measurement_test.cc` line 26 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9WB2HBP1OLr21UhH0:-NM9WB2HBP1OLr21UhH1:b-3p529r) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Qubit_measurement_test.cc#L26)):*
> ```cpp
>     fillParams(another_qubit);
>   }
>   void reset() {
> ```

This is not a good name for a function. Maybe `reinitializeToBellPair()` is better but still I don't like a function having side effects. 
___
*[`quisp/backends/ErrorTracking/Qubit_measurement_test.cc` line 86 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9bobZ0d4-71IG5_lX:-NM9bob_5EzD-iLd6khQ:b-5lj7by) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Qubit_measurement_test.cc#L86)):*
> ```cpp
>     qubit->measurement_err.setParams(x_measurement_error_rate, y_measurement_error_rate, z_measurement_error_rate);
>   }
>   Qubit* qubit;
> ```

Just a comment: I personally don't like the idea of having member level variables for testing since it is easy to leave side effects if setup and teardown are not properly done. I think this is ok. 
___
*[`quisp/backends/interfaces/IQuantumBackend.h` line 24 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NLgR8dF6gb4vKzoCI7v:-NLgR8dF6gb4vKzoCI7w:b-ubbkbh) ([raw file](https://github.com/sfc-aqua/quisp/blob/b3510f9606edc5a6ccbb09a3884b975d2aa2a304/quisp/backends/interfaces/IQuantumBackend.h#L24)):*
> ```objc
>   virtual ~IQuantumBackend(){};
> 
>   virtual IQubit* getQubit(const IQubitId* id) = 0;
> ```

Since the role of IQubitId is to be a unique identifier of a qubit, I think it'd make more sense if the argument here is not a pointer but rather an instance of `IQubitId`.
___
*[`quisp/backends/interfaces/IQuantumBackend.h` line 25 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NLgR82eDiLae12Tynrq:-NLgR82eDiLae12Tynrr:b-1k3niv) ([raw file](https://github.com/sfc-aqua/quisp/blob/b3510f9606edc5a6ccbb09a3884b975d2aa2a304/quisp/backends/interfaces/IQuantumBackend.h#L25)):*
> ```objc
> 
>   virtual IQubit* getQubit(const IQubitId* id) = 0;
>   virtual IQubit* getQubit(const IQubitId* id, std::unique_ptr<IConfiguration> configuration) = 0;
> ```

Since we plan to support backends where adding qubits later might become a problem. 
getQubit should only fetch an existing qubit and not create new ones.

I suggest adding new methods for adding qubits to the backend 
- `IQubit* addQubit(const IQubitId, config)` 
___
*[`quisp/backends/interfaces/IQubit.h` line 22 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9YiUg1pYDi5RsYdCU:-NM9YiUg1pYDi5RsYdCV:baknmvc) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/interfaces/IQubit.h#L22)):*
> ```objc
> };
> struct MeasurementOutcome {
>   char basis;
> ```

I think it would be better if we use enums for this. If it's not too difficult to change maybe change this to enum as well.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 31 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9aavM3-rMVQC2ZrRq:-NM9aavN3LMjmo5wkJ-z:b-hsmr69) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L31)):*
> ```
>         double emission_y_error_rate = default(0);
> 
>         bool overwrite_backend_qubit_config = default(false);
> ```

I don't like having this. It leads to more confusion. Since user needs to set some value anyway. They can just set it via `**.` syntax and then if they later want to change some qubits to have specific error. Declare it later would have the same effect. Redundant variable isn't a good idea.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 228 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9cVxA8S9n-1s5d_P2:-NM9cVxA8S9n-1s5d_P3:b1ju9n3) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L228)):*
> ```objc
>   }
> 
>   void hackSwappingPartners(IQubitRecord *const left_qubit_rec, IQubitRecord *const right_qubit_rec) override {
> ```

if all the code inside is commented out, why not delete the function?

**Review by Naphann — COMMENTED** [review]
> Reviewed 6 of 38 files at r1, 17 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)* status: 42 of 43 files reviewed, 11 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/backends/ErrorTracking/Configuration.h` line 12 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9TF0VDwiL9e7mRaPY:-NME33tt-KIIJdlLs7fR:b-9unw5o) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Configuration.h#L12)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need this, delete it.
</blockquote></details>

deleted
___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h` line 38 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9V0SHDaPeNJvX6Qla:-NME3Igg7xEWj5OFhAvd:b-n9tkhd) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.h#L38)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

type name should be PascalCase, so it should be `SingleQubitError`
</blockquote></details>

changed

**Review by zigen — APPROVED** [review]
> Reviewed 6 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)* status: all files reviewed, 9 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/backends/ErrorTracking/Backend.cc` line 27 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9U7iJBoZcMp8ke8jy:-NME9a8B11yqHxaO8psC:b-8fx2ut) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/ErrorTracking/Backend.cc#L27)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Should this be called `createQubit(...)` instead? 
I'm not sure I understand why would we have a single `getQubit` and what it does is it creates a new qubit if it doesn't already exist.

Would it be better to have `createQubit(id)` `getQubit(id)` `deleteQubit(id)`? 
- create should throw error if id already exists
- get should throw error if qubit doesn't exist
- delete should throw error if qubit doesn't exist

If we really need this behaviour maybe also add `getOrCreateQubit(id)` but this should be used very cautiously.

I think this is better when writing code and manage qubits. And I mean it should be like this for all Backend so we should change it at the interface level. 
</blockquote></details>

:+1:
___
*[`quisp/backends/interfaces/IQuantumBackend.h` line 25 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NLgR82eDiLae12Tynrq:-NME8NeJEk9hZIxcVDvX:b-c8rtla) ([raw file](https://github.com/sfc-aqua/quisp/blob/b3510f9606edc5a6ccbb09a3884b975d2aa2a304/quisp/backends/interfaces/IQuantumBackend.h#L25)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Since we plan to support backends where adding qubits later might become a problem. 
getQubit should only fetch an existing qubit and not create new ones.

I suggest adding new methods for adding qubits to the backend 
- `IQubit* addQubit(const IQubitId, config)` 
</blockquote></details>

I agree with that. it should be also clearer for readers.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 228 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9cVxA8S9n-1s5d_P2:-NME94boESzVcF2rSGPO:bqwzhfn) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L228)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

if all the code inside is commented out, why not delete the function?
</blockquote></details>

it's called from RuleSet through Runtime. we can delete the function itself later.

**Review by Naphann — APPROVED** [review]
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

___
*[`quisp/backends/interfaces/IQubit.h` line 22 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9YiUg1pYDi5RsYdCU:-NMEAjuL3q9HP-YV-ODb:b-3jno5h) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/backends/interfaces/IQubit.h#L22)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think it would be better if we use enums for this. If it's not too difficult to change maybe change this to enum as well.
</blockquote></details>

I looked into it and it's not trivial. Will create issue for this
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 228 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/467#-NM9cVxA8S9n-1s5d_P2:-NMEAtaP8eTD9Q7GCBN7:b-jep1bi) ([raw file](https://github.com/sfc-aqua/quisp/blob/914906c2fb528fcfa0fa4ad475ef688bf7b3cc80/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L228)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's called from RuleSet through Runtime. we can delete the function itself later.
</blockquote></details>

Yes, we should be able to after graph state pr

**Review by Naphann — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Pull request merged**
