### PR TITLE
Add IStationaryQubit

### PR DESCRIPTION
**Pull request by zigen**
after #255

now it's hard to write tests using StationaryQubit because it needs a lot of parameters and set measure results what we want.
So I separated the interface class for StationaryQubit and make it easy to write tests.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256)

### CODE REVIEW

**Review by Naphann — COMMENTED** [review]
> Reviewed 39 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256)* status: 39 of 40 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 101 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgip24w4Br9thOsCmwG:-Mgip24w4Br9thOsCmwH:b-wnezuy) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L101)):*
> ```objc
> 
>   double emission_success_probability;
>   int numemitted;
> ```

Should we follow the convection of separating words by `_` so `num_emitted`?
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 377 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgipv3C-KA3ERHlzAar:-Mgipv3C-KA3ERHlzAas:bh3nohh) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L377)):*
> ```cpp
> void StationaryQubit::CNOT_gate(IStationaryQubit *control_qubit) {
>   // Need to add noise here later
>   apply_two_qubit_gate_error(CNOTgate_error, dynamic_cast<StationaryQubit *>(control_qubit));
> ```

Why `dynamic_cast`?  Is it for future implementation where we might have multiple derivations from `IStationaryQubit`? Or is there any safety measure we get from this?

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256)* status: 39 of 40 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 101 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgip24w4Br9thOsCmwG:-MgitJJ0AhHdxZ2UDOmk:b-rx68s4) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L101)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Should we follow the convection of separating words by `_` so `num_emitted`?
</blockquote></details>

it's better and this member is used in StationaryQubit.cc internally. so I'll fix it.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 377 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgipv3C-KA3ERHlzAar:-Mgiu0FECqx1X1DbueTp:b-r3h5kz) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L377)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Why `dynamic_cast`?  Is it for future implementation where we might have multiple derivations from `IStationaryQubit`? Or is there any safety measure we get from this?
</blockquote></details>

one reason is for future implementation. we may have multiple backend implementations like cirq or qiskit. but we should not mix these backends at the same time. to keep this constraint, I cast IStationaryQubit into StationaryQubit. maybe OMNeT++'s `check_and_cast` is a better choice because it will raise a more informative error message. let me try to use it

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256)* status: 38 of 40 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 101 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgip24w4Br9thOsCmwG:-MgjF9E24sSAE_gAhTqH:bpg2mzy) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L101)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's better and this member is used in StationaryQubit.cc internally. so I'll fix it.
</blockquote></details>

finally I found this member is no longer used, so removed.

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256)* status: 39 of 40 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 101 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/256#-Mgip24w4Br9thOsCmwG:-MgjFOCe-ko112h8-7if:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/0ceb10ffac29bd3e5bdb0598356e090ccc65a048/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L101)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

finally I found this member is no longer used, so removed.
</blockquote></details>

Done.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 33 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/256#-MgjOpI-4ZnD9bvWqqCS:-MgjOpI-4ZnD9bvWqqCT:bj4hi6j) ([raw file](https://github.com/sfc-aqua/quisp/blob/579b8c7e47ad440a95b2d2972a8fe53fadf2cd3a/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L33)):*
> ```cpp
>  */
> void StationaryQubit::initialize() {
>   double rand = dblrand();
> ```

also I removed useless commetns

**Review by Naphann — APPROVED** [review]
it works on my machine and I like the change! 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/256#-:-MgjapB10WSc3a6EoX13:b8wivvx)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

**Pull request merged**
