### PR TITLE
Remove entangled_with

### PR DESCRIPTION
**Pull request by MakotoNakai**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/432)

### CODE REVIEW

**Comment by zigen** [comment]
@MakotoNakai thank you for your contribution! could you put the related issue in the description? and also e2e-test are failed, so also could you check the reason for that?

**Comment by MakotoNakai** [comment]
Close #416

**Review by zigen — CHANGES_REQUESTED** [review]
Be careful if you change a part that unit tests don't cover.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/432#-:-NF9IAH05XnXgLCFVEAW:bifkfvj)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @MakotoNakai)

___
*[`quisp/PhotonicQubit.msg` line 17 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/432#-NF9FO5JErr65sDlQmHt:-NF9FO5JErr65sDlQmHu:b1oj01d) ([raw file](https://github.com/sfc-aqua/quisp/blob/3508c5c16d904d4087c79c69310d1dd66edc97df/quisp/PhotonicQubit.msg#L17)):*
> ```
>     int QNICEntangledWith = -1;//Which QNIC it is entangled with
>     int StationaryQubitEntangledWith = -1;//Which buffer it is entangled with
>     omnetpp::cModule* entangled_with;
> ```

the issue is talking about `PurificationResult`, not `PhotonicQubit`. 
actually, we use this attribute for physical qubit entanglement simulation.
so please don't delete this.
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 131 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/432#-NF9GPfc2iVygaPqPQQ6:-NF9GPfc2iVygaPqPQQ7:belnc78) ([raw file](https://github.com/sfc-aqua/quisp/blob/3508c5c16d904d4087c79c69310d1dd66edc97df/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L131)):*
> ```cpp
>   if (msg->arrivedOn("fromHoM_quantum_port$i", 0)) {
>     left_arrived_at = simTime();
>     left_statQubit_ptr = const_cast<StationaryQubit *>(check_and_cast<const StationaryQubit *>(photon->getEntangled_with()));
> ```

when you delete an assignment expr or variable, I recommend you to check where and how the variable is used. 

in this case, `left_statQubit_ptr` is a member of `BellStateAnalyzer`, and is assigned a meaningful value only here. And also the member is used for manipulating its quantum state by the result of the photon detection.

**Comment by zigen** [comment]
FYI, you can see the test results below, and you can see its detail by clicking the "Details" button.
Screen Shot 2022-10-24 at 23 07 48

and [the error](https://github.com/sfc-aqua/quisp/actions/runs/3310105095/jobs/5464997338) is a segmentation fault. please try to run QuISP, not only the unit test.
```
messages/purification_messages_m.cc
messages/QNode_ipc_messages_m.cc
messages/tomography_messages_m.cc
Creating executable: out/clang-release//quisp
start test 0
test.sh: line 31:  1317 Segmentation fault      (core dumped) $QUISP_ROOT/quisp/out/clang-release/quisp -u Cmdenv --cmdenv-express-mode=true -c "Test$i" -f $QUISP_ROOT/quisp/networks/test.ini -n $NEDPATH >> $QUISP_ROOT/test/Test$i.log
Error: Process completed with exit code 139.
```

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/432#-:-NFDh4GB6gD0bQOUBId6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MakotoNakai)

**Pull request merged**
