### PR TITLE
Refactor actions

### PR DESCRIPTION
**Pull request by zigen**
prev: #326

* make constructor readable
* remove useless comments, var declaration
* fix RandomMeasureAction ctor args so that it takes ruleset id and rule index
* change namespace notation

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/327)

### CODE REVIEW

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> Reviewed 22 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/327#-:-MrLHDN_BV7WqUeSsDG1:bnfp4nl)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/actions/DoublePurifyAction.h, line 9 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/327#-MrLG0buEB8Ilz99PmfE:-MrLG0buEB8Ilz99PmfF:btun6ma) ([raw file](https://github.com/sfc-aqua/quisp/blob/a07a625cbb74bb8216b1bb039c7fcdd0bff364a4/quisp/rules/actions/DoublePurifyAction.h#L9)):*
> ```objc
> class DoublePurifyAction : public Action {
>  public:
>   DoublePurifyAction(unsigned long ruleset_id, unsigned long rule_index, int partner, QNIC_type qnic_type, int qnic_id, int resource, int trash_resource_x, int trash_resource_z);
> ```

I'd like to change the name "rule_index" to "rule_id", but may not be in this PR.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/327)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/rules/actions/DoublePurifyAction.h, line 9 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/327#-MrLG0buEB8Ilz99PmfE:-MrLJv1X9M669MHemx0M:biyti51) ([raw file](https://github.com/sfc-aqua/quisp/blob/a07a625cbb74bb8216b1bb039c7fcdd0bff364a4/quisp/rules/actions/DoublePurifyAction.h#L9)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

I'd like to change the name "rule_index" to "rule_id", but may not be in this PR.
</blockquote></details>

or, we should not put `rule_index` manually. it should be generated by RuleSet like
```cpp
auto *rule = ruleset->addRule();
// and then automatically Ruleset fills rule->rule_index 
```

**Review by Chibikuri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/327)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/actions/DoublePurifyAction.h, line 9 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/327#-MrLG0buEB8Ilz99PmfE:-MrLMx3KEsGILXy3YdA2:b-ivdttf) ([raw file](https://github.com/sfc-aqua/quisp/blob/a07a625cbb74bb8216b1bb039c7fcdd0bff364a4/quisp/rules/actions/DoublePurifyAction.h#L9)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

or, we should not put `rule_index` manually. it should be generated by RuleSet like
```cpp
auto *rule = ruleset->addRule();
// and then automatically Ruleset fills rule->rule_index 
```
</blockquote></details>

Yeah, that would be good. I meant just "index" and "id" are mixed over the different classes.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/327)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/rules/actions/DoublePurifyAction.h, line 9 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/327#-MrLG0buEB8Ilz99PmfE:-MrLPNkI9i7pV1mBRz6r:b-phe6k9) ([raw file](https://github.com/sfc-aqua/quisp/blob/a07a625cbb74bb8216b1bb039c7fcdd0bff364a4/quisp/rules/actions/DoublePurifyAction.h#L9)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Yeah, that would be good. I meant just "index" and "id" are mixed over the different classes.
</blockquote></details>

true, and also `qnic_id` and `qnic_index` are same

**Pull request merged**
