### PR TITLE
Enable logger on off

### PR DESCRIPTION
**Pull request by res6idue**
This PR enables to turn off the json logger by passing an omnetpp parameter (The default value is true)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @res6idue)

___
*[`quisp/modules/Logger/LoggerBase.cc` line 2 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/444#-NGZgE8p1umA_TF-2DG3:-NGZgE8p1umA_TF-2DG4:b-mchm1z) ([raw file](https://github.com/sfc-aqua/quisp/blob/3d0cc4e6c76f7e7ac82dac99753c7d8d1d6142f7/quisp/modules/Logger/LoggerBase.cc#L2)):*
> ```cpp
> #include "LoggerBase.h"
> #include <cstddef>
> ```

do we need this?

**Review by res6idue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[`quisp/modules/Logger/LoggerBase.cc` line 2 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/444#-NGZgE8p1umA_TF-2DG3:-NGZkPWI74d8mpIHvIGM:b-km6tc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/3d0cc4e6c76f7e7ac82dac99753c7d8d1d6142f7/quisp/modules/Logger/LoggerBase.cc#L2)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

I don't think so. I will delete it.

**Review by res6idue — COMMENTED** [review]
I think that the logger is somehow nullptr when we call it from ruleengine.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444#-:-NGZlZrr3EyQinsGCCis:b-vujx46)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
in the unit test? 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444#-:-NGZqX7y4_tlKfYUk_1H:bmm46tm)* status: 10 of 12 files reviewed, 1 unresolved discussion

**Review by res6idue — COMMENTED** [review]
Yes.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444#-:-NGanrvN2dTrf_5gEqOS:bb77ufg)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @zigen)

**Comment by zigen** [comment]
you can use debugger to investigate the error.
1. build with debug symbol ` make -C quisp MODE=debug run-unit-test`
2. set the launch.json for code-lldb
```json 
{

    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Launch",
            "program": "${workspaceFolder}/quisp/run_unit_test",
            "args": [],
            "cwd": "${workspaceFolder}/quisp"
        },
    ],
}
```

3. start debugger

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 1 of 1 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444)* status: 16 of 17 files reviewed, all discussions resolved

**Comment by zigen** [comment]
@res6idue I fixed the segmentation faults. Could you check it?

**Review by res6idue — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by res6idue — COMMENTED** [review]
It works well! Thank you very much

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444#-:-NH8XAiw5f06U9SyYiE-:b-fp7ct7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/444#-:-NH8XojOE6ftHWQyf4xm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Pull request merged**
