### PR TITLE
add BellPairStore to manage RuleEngine::allResources

### PR DESCRIPTION
**Pull request by zigen**
RuleEngine's `allResources` member is so complicated, and this exposes the internal data structure, so we should hide it and focus on the logic itself.

In this PR, the `BellPairStore` class contains the data and provides ways to manipulate the data.

- [x] fundamental implementation
- [x] unit tests for `BellPairStore`
- [x] unit tests for `RuleEngine`
- [x] more comments for `BellPairStore`
- [x] rename `BellPairStore` methods. 
  - `erase` -> `eraseQubit`
  - `find` -> `findQubit`

this approach is effective for QubitStateTable, PurificationTables, rp, and so on.

next #244 to refactor ruleset.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/241)

### CODE REVIEW

**Review by Naphann — APPROVED** [review]
It works on my machine and this change makes resource allocation code a lot cleaner!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/241#-:-MeU6pF65BdsU9dEWLm7:bvf94vm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Comment by zigen** [comment]
the name ResourceStore is ambiguous. this class contains partner qnode address and corresponding entangled qubit in this qnode.
so I renamed ResourceStore to BellPairStore.

**Review by Chibikuri — APPROVED** [review]
> Reviewed 8 of 11 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Chibikuri — APPROVED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/241#-:-Mf1gzPwBrXJURfEt1xl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
