### PR TITLE
add icons and set image path

### PR DESCRIPTION
**Pull request by zigen**
use new icons
see also https://doc.omnetpp.org/omnetpp/manual/#sec:graphics:image-path

スクリーンショット 2022-01-24 20 51 29

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349)

### CODE REVIEW

**Comment by rdviii** [comment]
HoM == BSA. I would be okay with renaming almost all uses of HoM in the code and documentation with BSA (though we need the distinction between the physical-layer mechanism, the logical operation, and the node type, sometimes).
We should also pick an end node type for each of those EndNodes.

**Comment by rdviii** [comment]
Oh, just realized that the top figure is the internal look at an HoM node, and has the BSA icon there.

Unfortunately, that's *backwards*.  HoM is really the *physical mechanism*, and BSA is the *node type*.

Might mean having to change around a bunch of the names in the code.

**Comment by rdviii** [comment]
Just noticed one more potential difference in definition here -- in the bottom example, both of the Repeater nodes have multiple interfaces. In the node type definitions, we defined "Repeater" as having exactly two interfaces (being part of a line), and "Router" as anything having more than two interfaces.  (We didn't make a distinction between 1G and 2G routers.)

**Review by Naphann — APPROVED** [review]
I think we BSA (or currently called HoM) should have default display declared in the `ned` file so we don't have to define it in every topology but for QNode it's ok not to have defaults.

> Reviewed 48 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuBQM2w5r9bnnsVOBsS:bczcdoo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuBWIgr9ukuSDTlFFM9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
I fixed it as whit3z said.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuEAOcz6-YMGDRWpI-B:bbdavm1)* status: 41 of 48 files reviewed, all discussions resolved (waiting on @Naphann)

**Review by Naphann — APPROVED** [review]
I had one last comment but after the fix it is good to be merged! 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuEP3otAoA0BXI4om6A:b-l1pvco)* status: 41 of 48 files reviewed, 1 unresolved discussion (waiting on @Naphann and @zigen)

___
*[quisp/networks/topology_linear_network.ned, line 289 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/349#-MuEOl0o6-7CuNrAlNVc:-MuEOl0pDIIqBdD1zd6u:btx8jq1) ([raw file](https://github.com/sfc-aqua/quisp/blob/c2c4f133a2da95dfcb3561d3c2eccacc65ec822c/quisp/networks/topology_linear_network.ned#L289)):*
> ```
>         		//buffers = 25;
> 
>             @display("i=RTR;p=408,131");
> ```

I think this one should be REP1G, since it only has 2 arms.

**Review by zigen — COMMENTED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuEYqZ39nQcOCxwwNNb:bd5l6mr)* status: 41 of 48 files reviewed, 1 unresolved discussion (waiting on @Naphann and @zigen)

**Review by Naphann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/349#-:-MuEaCnyEiCA-RA7PHr9:bnfp4nl)* status: 41 of 48 files reviewed, all discussions resolved (waiting on @Naphann)

**Pull request merged**
