### PR TITLE
BSM restarting process

### PR DESCRIPTION
**Pull request by Chibikuri**
I found some implementational non-expected behavior in the previous e2e tomography implementation.
I detected the error was from no free qubits anymore. 

The solution currently working on is HoM keep sending notifications. However, this needs some hacks in the RuleEngine tracker.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)

### CODE REVIEW

**Comment by Chibikuri** [comment]
If I make BSA start in HoMController recursive, the simulation only sends BSA notifier, but no more events barely happen. 
The solution for this would be send reject message from neighbors to HoM and restart again.

**Review by zigen — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: all files reviewed, 6 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/Common/Router.cc, line 111 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3aEhx6uBTtPpeuyp2:-Me3aEhx6uBTtPpeuyp3:b6p6ns2) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/modules/Common/Router.cc#L111)):*
> ```cpp
>   int who_are_you = pk->getKind();  // read the type of packet // This might be better fixed
>   // bubble("Message kind "<<message_type<<" received");
>   // EV << "destAddr ==== " << destAddr;
> ```

remove it
___
*[quisp/modules/PhysicalConnection/BSA/HoMController.cc, line 113 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3hqcq1J5c30MNo_Nv:-Me3hqcq1J5c30MNo_Nw:b-ewjx9z) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/modules/PhysicalConnection/BSA/HoMController.cc#L113)):*
> ```cpp
>     sendNotifiers();
> 
>     BSAstart *bsa_start = new BSAstart("BSA trial for the next step");
> ```

use `auto` because we know the type of `bsa_start` is `BSAstart*`.
___
*[quisp/modules/PhysicalConnection/BSA/HoMController.cc, line 113 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3hzhV271ydmCAIPhr:-Me3hzhV271ydmCAIPhs:bvu5p3l) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/modules/PhysicalConnection/BSA/HoMController.cc#L113)):*
> ```
> "BSA trial for the next step"
> ```
this is the name of a packet. so PascalCase is better. when we may use this value for analyzing log data, no space string is easier to handle.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 433 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3jJAYBvzFjM-39_kI:-Me3jJAZ1EMXalJTlIri:b-mjlb0u) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L433)):*
> ```cpp
>   par("GOD_entangled_qnic_type") = -1;
>   entangled_partner = nullptr;
>   EV << "Freeing this qubit!!!" << this <<" at qnode: "<<node_address<<" qnic_type: "<<qnic_type<<" qnic_index: "<<qnic_index<<"\n";
> ```

how about EV_DEBUG?
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 623 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3lMNo2S2yTF1BsQiz:-Me3lMNtEKeLFrBISrsD:bn9tnsd) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L623)):*
> ```cpp
>   if (hasGUI()) {
>     char text[32];
>     sprintf(text, "I'm entangled with %d", entangled_partner->node_address);
> ```

sprintf is not secure and it's too hard to debug if we give a long string.
use `std::string`. we are writing in C++, not C.
___
*[quisp/networks/omnetpp.ini, line 267 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Me3ljXE24nAvz_DxAQD:-Me3ljXE24nAvz_DxAQE:b-h1ib0l) ([raw file](https://github.com/sfc-aqua/quisp/blob/2f38dab945c2482eaeee01d1973be122e157d76b/quisp/networks/omnetpp.ini#L267)):*
> ```INI
> seed-set = 1
> **.num_measure = 7000
> **.buffers = 99
> ```

why do you need to change?

**Comment by Chibikuri** [comment]
Thank you for your reviews. 
It's now under experiment. To understand some weird behavior, I was doing some experiments. 
Eventually, those ones should be cleaned.

**Comment by Chibikuri** [comment]
Once this pull request is merged into master, all simulations must have a time limit for the simulation. 
I'll make some documents for that.

**Comment by Chibikuri** [comment]
Code is now reviewable. Let me make this PR ready for review.

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: 10 of 11 files reviewed, 8 unresolved discussions (waiting on @Chibikuri)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf0av3HD_2NAe545eho:-Mf0av3HD_2NAe545ehp:bvs0vzz) (no related file):*
> ```
> std::vector<bool> tracker_accessible
> ```

So if I understand it right, to fix your bug. This new vector is to track which QNIC has sent out photons and waiting for results?
While the QNIC is waiting, no new emission can occur? Why is this the case? Why should the QNIC be blocked while waiting? 

Since a qubit has busy status, can we just check whether a qubit is busy or not instead and not blocking the entire QNIC?

If I got this wrong, can you explain the logic here?

---
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.h, line 76 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf0amNPCLbHvGvA1g4j:-Mf0amNPCLbHvGvA1g4k:bvb0l4e) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e214ddd3d3a56556324e3f15717d05034e28c20/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L76)):*
> ```objc
>   // Vector for store package for simultaneous entanglement swapping
>   std::map<int, std::map<int, int>> simultaneous_es_results;
>   std::vector<bool> tracker_accessible;  // if the tracker is accessible true
> ```

I don't think this comment is informative. I don't understand what the comment means or what the variable name means. Could you explain it?

**Comment by Chibikuri** [comment]
@Naphann So basically, it's to keep the consistency of the photon emission trial. 
In this implementation, RuleEngine only keeps one tracker. 
So, when the first BSM timing notifier coming in, RE block the tracker for the qnic because the next BSM timing notifier would overwrite the tracker.
To avoid that situation, we need ownership of the tracker.
So, when the tracker table is properly cleared by the previous BSM process, any BSM can use that tracker. Otherwise, it should be blocked. 

But I guess preparing multiple trackers is what you say?
In this case, you can avoid inconsistency of the tracker, but the problem occurs when the BSM notification rate is too high. 
If the first notification emits 50 photons and during that 20 photons are emitted by the other BSM notification, it's not distinguishable by BSA.
In that sense, all BSM processes should be done sequentially, shouldn't they?

**Comment by Chibikuri** [comment]
The comment should have more explanation. Let me fix that.
What I meant when the value holds true, it means the tracker for the qnic can be accessible. It means the now tracker is fully cleaned by previous BSM trial.

**Review by Naphann — COMMENTED** [review]
Thanks for the explanation. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf0qMzcB1b0oWjtqtNc:b-mfdii5)* status: 9 of 11 files reviewed, 8 unresolved discussions (waiting on @Chibikuri and @Naphann)

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/classical_messages.msg, line 161 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf1lvQ366BBCQzaAE-p:-Mf1lvQ366BBCQzaAE-q:b-4yf8uk) ([raw file](https://github.com/sfc-aqua/quisp/blob/e8a2a9211420856b8cf4cf96343a649be5137827/quisp/classical_messages.msg#L161)):*
> ```
> }
> 
> packet BSAstart extends header{}
> ```

this BSAstart is no longer used.
___
*[quisp/networks/omnetpp.ini, line 360 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf1n2Dl759I38OkCDpk:-Mf1n2Dl759I38OkCDpl:b-7y3amm) ([raw file](https://github.com/sfc-aqua/quisp/blob/e8a2a9211420856b8cf4cf96343a649be5137827/quisp/networks/omnetpp.ini#L360)):*
> ```INI
> 
> [Config EntanglementSwapping_Realistic_Layer2_Simple_MIM_MM_Test]
> network= Linear_One_MM
> ```

hey, the config name and actual network are different, so it confuses users. 
could you change the config name or network to keep match it?

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[quisp/classical_messages.msg, line 161 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf1lvQ366BBCQzaAE-p:-Mf1zOJU4fVnd38Fcfx2:bidrs83) ([raw file](https://github.com/sfc-aqua/quisp/blob/e8a2a9211420856b8cf4cf96343a649be5137827/quisp/classical_messages.msg#L161)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

this BSAstart is no longer used.
</blockquote></details>

Right. Fixed.
___
*[quisp/networks/omnetpp.ini, line 360 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf1n2Dl759I38OkCDpk:-Mf1zX0FAo-LWAEOakIS:byzit9u) ([raw file](https://github.com/sfc-aqua/quisp/blob/e8a2a9211420856b8cf4cf96343a649be5137827/quisp/networks/omnetpp.ini#L360)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

hey, the config name and actual network are different, so it confuses users. 
could you change the config name or network to keep match it?
</blockquote></details>

I forgot to revert the config. Fixed it

**Review by zigen — APPROVED** [review]
could you rebase it to the latest master or merge the latest master?

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf2--hVAkT7gQLof7sG:bh3w4f1)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
and one more thing, could you write some tests for the tracker? later I want to refactor it.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf2-KBY-yWjRQmHfdDW:b-dul1gz)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by Chibikuri — COMMENTED** [review]
Yeah, let me merge current master and write some tests for it

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf21sjtBq8zORHfTxZk:bspo4gb)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

**Review by Naphann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf2BJo00zDrdqjk1SZi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by Naphann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc, line 16 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf3z9V91JfcUWIx6T5P:-Mf3z9V91JfcUWIx6T5Q:bkqsx9e) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd52d8ee1d6e02c2d0623d478ac16b3e1164b22c/quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc#L16)):*
> ```cpp
> #include "modules/QRSA/HardwareMonitor/HardwareMonitor.h"
> #include "modules/QRSA/HardwareMonitor/IHardwareMonitor.h"
> #include "modules/QRSA/RealTimeController/RealTimeController.h"
> ```

please use `IRealTimeController.h`. we don't want to care about the detail of RealTimeController in RuleEngine's unit test.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc, line 55 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf3zKub3_P_x0oufbIN:-Mf3zKuc1pVF37quHnHk:b-6ha3i2) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd52d8ee1d6e02c2d0623d478ac16b3e1164b22c/quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc#L55)):*
> ```cpp
> };
> 
> class MockRealTimeController : public RealTimeController {
> ```

inherit `IRealTimeController`

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc, line 55 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf3zKub3_P_x0oufbIN:-Mf6Y4dW2HX7J2RdT4Cs:by2t4gt) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd52d8ee1d6e02c2d0623d478ac16b3e1164b22c/quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc#L55)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

inherit `IRealTimeController`
</blockquote></details>

Yeah, I tried to do it, but it returns this error. I thought it was because we have some undefined functions in the Interface class. Do you have any ideas for this error?

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc, line 55 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf3zKub3_P_x0oufbIN:-Mf6nrXI7wx-QW3X7FQH:b-d1o3ba) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd52d8ee1d6e02c2d0623d478ac16b3e1164b22c/quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc#L55)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Yeah, I tried to do it, but it returns this error. I thought it was because we have some undefined functions in the Interface class. Do you have any ideas for this error?


</blockquote></details>

ah, you need to add `MOCK_METHOD(~~` for all methods in IReamTileController.
IRealTimeControoler is an interface class so all methods are virtual and do not have a method body.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc, line 55 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/237#-Mf3zKub3_P_x0oufbIN:-Mf6sZU_7uTfqlzfNoN4:bugt5a3) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd52d8ee1d6e02c2d0623d478ac16b3e1164b22c/quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc#L55)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

ah, you need to add `MOCK_METHOD(~~` for all methods in IReamTileController.
IRealTimeControoler is an interface class so all methods are virtual and do not have a method body. 

</blockquote></details>

Oh, I see. Now it works! Thanks

**Review by zigen — APPROVED** [review]
seems fine! if CI passed, let's merge it!
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/237#-:-Mf6zri_BxL6nrA7FZUu:b1p5tsx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
