### PR TITLE
filled addRule

### PR DESCRIPTION
**Pull request by Chibikuri**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/341)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/341)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/RuleSet.h, line 8 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/341#-MsySQx551nXs6EM_IR3:-MsySQx551nXs6EM_IR4:b-7el9ha) ([raw file](https://github.com/sfc-aqua/quisp/blob/403a9dde2fdbbe8972a7e19454c3924122e6a9ea/quisp/rules/RuleSet.h#L8)):*
> ```objc
> 
> /**
>  * @brief (Inactive) RuleSet class which includes a set of Rule Information
> ```

I think it's not "inactive" because an "inactive" RuleSet will be deleted when the execution is finished.
___
*[quisp/rules/RuleSet.h, line 19 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/341#-MsySeBA75bNKz5TcaLG:-MsySeBA75bNKz5TcaLH:b-ovl9sk) ([raw file](https://github.com/sfc-aqua/quisp/blob/403a9dde2fdbbe8972a7e19454c3924122e6a9ea/quisp/rules/RuleSet.h#L19)):*
> ```objc
>   std::vector<BaseRule> rules;
> 
>   BaseRule &addRule(const BaseRule rule, std::vector<int> partners);
> ```

should pass a pointer (or it might be a unique_ptr). we don't want to copy it. and we cannot specify a super class to accept its subclasses when we pass it by value.

**Comment by zigen** [comment]
I recommend  you to install  the "editorconfig" plugin https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/341)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/rules/RuleSet.h, line 8 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/341#-MsySQx551nXs6EM_IR3:-Msyw5EMA0Qkvp6xCVHU:b-hmmr0w) ([raw file](https://github.com/sfc-aqua/quisp/blob/403a9dde2fdbbe8972a7e19454c3924122e6a9ea/quisp/rules/RuleSet.h#L8)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think it's not "inactive" because an "inactive" RuleSet will be deleted when the execution is finished.
</blockquote></details>

Ah, yes. I'll remove it.
___
*[quisp/rules/RuleSet.h, line 19 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/341#-MsySeBA75bNKz5TcaLG:-Msyw2jpE4lb_ezlJPCw:b-yq5pcd) ([raw file](https://github.com/sfc-aqua/quisp/blob/403a9dde2fdbbe8972a7e19454c3924122e6a9ea/quisp/rules/RuleSet.h#L19)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should pass a pointer (or it might be a unique_ptr). we don't want to copy it. and we cannot specify a super class to accept its subclasses when we pass it by value. 
</blockquote></details>

Ahh, I see. Let me fix it.

**Review by zigen — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/341#-:-Mt1uonQ1jdi5IpnyL6R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
