### PR TITLE
Implementation of EPPS node and MSM link

### PR DESCRIPTION
**Pull request by res6idue**
This PR introduces the EPPS node, the passive BSA controller, and Rule Engine functions suited for MSM link.

Remaining tasks
- [x] Fix the MSM protocol structure to match MidpointSource introduced in [Jones et al.](https://iopscience.iop.org/article/10.1088/1367-2630/18/8/083015/pdf)
- [x] Write simulation tests
- [x] Write documentation

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)

### CODE REVIEW

**Comment by res6idue** [comment]
I don't really know how detailed the documentation should be, so I will open this pull request. Please feel free to ask questions, and I might increase the amount of documentation according to those reviews.
The parameters that are in the simulation test for MSM, (especially those with errors) were not calculated values but the result from simulation (seed = 1).
In terms of fidelity, it seems to be consistent with theory.
Fidelity for MSM (x error rate = 0.1)

This graph was generated by the code in epps-test, where I performed the fidelity check test.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 42 files at r1, 1 of 8 files at r2, 14 of 40 files at r3, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)* status: 22 of 52 files reviewed, 4 unresolved discussions (waiting on @res6idue)

___
*[`.vscode/launch.json` line 35 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGGbOu5ZjuHzkWjoch:-NkGGbOu5ZjuHzkWjoci:b-4m6pd9) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/.vscode/launch.json#L35)):*
> ```JSON
>             "request": "launch",
>             "name": "simple debug",
>             "program": "${workspaceFolder}/a.out",
> ```

it's not reusable, so could you delete it?
___
*[`quisp/PhotonicQubit.msg` line 22 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGGnUaEz3WhdLpkARg:-NkGGnUaEz3WhdLpkARh:bvka7tt) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/PhotonicQubit.msg#L22)):*
> ```
>     bool has_x_error @getter(hasXError) @setter(setXError) = false;
>     bool has_z_error @getter(hasZError) @setter(setZError) = false;
>     string graph_state @getter (getGraphState) @setter(setGraphState) = "";
> ```

this should be just `string graphState`, then these accessors are automatically generated.
___
*[`quisp/messages/BSA_ipc_messages.msg` line 24 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGHRbR6fabYKQQw33r:-NkGHRbR6fabYKQQw33s:b-ljjcig) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/messages/BSA_ipc_messages.msg#L24)):*
> ```
> packet SingleClickResult extends Header {
>     BSAClickResult click_result @setter(setClickResult) @getter(getClickResult);
>     int qnic_index @getter(getQnicIndex) @setter(setQnicIndex);
> ```

should be like this.
```
BSAClickResult clickResult;
int qnicIndex;
```
___
*[`quisp/modules/PhysicalConnection/BSA/BSAController.cc` line 212 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGLCoQ7BIP8Wl6N72b:-NkGLCoQ7BIP8Wl6N72c:b-2rw08b) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/modules/PhysicalConnection/BSA/BSAController.cc#L212)):*
> ```cpp
>   // this port connects to internal QNIC
>   // since only port 0 is supposed to be connected to internal QNIC
>   if (port == 0 && (strcmp(getParentModule()->getName(), "qnic_r") == 0 || strcmp(getParentModule()->getName(), "qnic_rp") == 0)) {
> ```

I don't want to access parent module and it's attributes. everything should be accessed through component provider.
this coupling makes difficult to write unit tests.
but it's fine to be fixed in later PR. 
___
*[`quisp/modules/PhysicalConnection/EPPS/EntangledPhotonPairSource.cc` line 59 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGM8pIA8d40mIgOuUV:-NkGM8pIA8d40mIgOuUW:bsaibuv) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/modules/PhysicalConnection/EPPS/EntangledPhotonPairSource.cc#L59)):*
> ```cpp
>   // only for debug usage
>   left_photon->setGraphState(left_photon_ref->graphState().c_str());
>   right_photon->setGraphState(right_photon_ref->graphState().c_str());
> ```

remove or comment out

**Comment by zigen** [comment]
@res6idue it's nice if we have a sequence diagram for the MSM protocol with [mermaid](https://mermaid.js.org/syntax/sequenceDiagram.html). you can embed it in markdown and github will render it.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 42 files at r1, 1 of 8 files at r2, 16 of 40 files at r3, 3 of 4 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)* status: 45 of 52 files reviewed, 5 unresolved discussions (waiting on @res6idue)

___
*[`quisp/modules/PhysicalConnection/EPPS/README.md` line 97 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkJ7a7FDlMII89xORtD:-NkJ7a7FDlMII89xORtE:b-1d8xh3) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/modules/PhysicalConnection/EPPS/README.md#L97)):*
> ```Markdown
> 
> ---
> ### Function to handle the link generation result
> ```

these detailed function descriptions should be near its code because it's hard to maintain this README and code at the same time.

**Review by res6idue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)* status: 40 of 52 files reviewed, 5 unresolved discussions (waiting on @zigen)

___
*[`quisp/PhotonicQubit.msg` line 22 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGGnUaEz3WhdLpkARg:-NkYiMdHELGh7MgPUIGe:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/PhotonicQubit.msg#L22)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

this should be just `string graphState`, then these accessors are automatically generated.
</blockquote></details>

Done.
___
*[`quisp/messages/BSA_ipc_messages.msg` line 24 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGHRbR6fabYKQQw33r:-NkYiJ0j8QCrZXY-INrZ:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/messages/BSA_ipc_messages.msg#L24)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should be like this.
```
BSAClickResult clickResult;
int qnicIndex;
```
</blockquote></details>

Done.
___
*[`.vscode/launch.json` line 35 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGGbOu5ZjuHzkWjoch:-NkYiQNd79oX8iIT5jIb:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/.vscode/launch.json#L35)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's not reusable, so could you delete it?
</blockquote></details>

Done.

**Review by res6idue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)* status: 35 of 53 files reviewed, 5 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/PhysicalConnection/EPPS/EntangledPhotonPairSource.cc` line 59 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkGM8pIA8d40mIgOuUV:-NkZPd3M7PU2DKKekrGI:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/modules/PhysicalConnection/EPPS/EntangledPhotonPairSource.cc#L59)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

remove or comment out
</blockquote></details>

Done.
___
*[`quisp/modules/PhysicalConnection/EPPS/README.md` line 97 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/518#-NkJ7a7FDlMII89xORtD:-NkZPei5CXKFDS52cNvN:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/72be709c9c02f5c0b569f51a1a9b869f2056ea0a/quisp/modules/PhysicalConnection/EPPS/README.md#L97)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

these detailed function descriptions should be near its code because it's hard to maintain this README and code at the same time.
</blockquote></details>

Done.

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 42 files at r1, 3 of 40 files at r3, 1 of 1 files at r4, 3 of 6 files at r7, 9 of 9 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @res6idue)

___
*[`quisp/modules/PhysicalConnection/EPPS/EPPSController.cc` line 98 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/518#-Nmcs08OBAfCRP3slP5-:-Nmcs08OBAfCRP3slP50:b-uymxw0) ([raw file](https://github.com/sfc-aqua/quisp/blob/09aada755c9a8ce380ad9c00920c468aa3b5d2d3/quisp/modules/PhysicalConnection/EPPS/EPPSController.cc#L98)):*
> ```cpp
>                                              ->getOwnerModule()  // QNIC
>                                              ->getSubmodule("bsa")  // BellStateAnalyzer
>                                              ->par("photon_detection_per_second");
> ```

the external module references like this makes difficult to write unit tests. 
we should refactor it in another PR later so that it refers the external module via the ComponentProvider.

**Review by zigen — APPROVED** [review]
the PR looks almost good. let's merge it. and then refactor several things later.

FYI you should check codacy for README.md syntax issues.
https://app.codacy.com/gh/sfc-aqua/quisp/pullRequest?prid=11371148&bid=34339178#newIssuesView

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518#-:-Nmct-gV-lfp_Aa-xsnq:b-fdzf29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Comment by res6idue** [comment]
I will merge this

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/518#-:-NnNeYlB4vuB1y3wEDha:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Pull request merged**
