### PR TITLE
Doxygen update

### PR DESCRIPTION
**Pull request by Chibikuri**
# What I did
- Removed anonymous namespace from doxygen.
- Removed unnecessary \todo
- Moved some unsolved \todo to just comment

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/294)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
why don't you remove unsolved comments? if it's still needed,  we should raise a issue.
I wanted to say we should maintain the todo comments. if it should be put on source code, ok, leave it. 
if not, we should remove it or move to github's issue

> Reviewed 7 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/294#-:-MkfHKRM9ORwmNZ7JzTR:b5iox79)* status: 7 of 24 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[Doxyfile, line 472 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/294#-MkfHESKC7iUYuCFlCSE:-MkfHESL5D5ifDgjKmUY:b7jj59x) ([raw file](https://github.com/sfc-aqua/quisp/blob/e075c66f4a9d5cd55ba5f066bb2432d1da22b0c0/Doxyfile#L472)):*
> ```
> # The default value is: NO.
> 
> EXTRACT_ANON_NSPACES   = NO
> ```

this is a perfect solution! thanks!

**Review by Chibikuri — COMMENTED** [review]
Ah, you're right. Let me remove them.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/294#-:-MkfK6gj6rD5xx_dDee_:b-jnpits)* status: 7 of 24 files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — APPROVED** [review]
> Reviewed 13 of 24 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/294#-:-MkfqI-H1xFIvBoVu9ga:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
