### PR TITLE
Extend purification actions with remote partners

### PR DESCRIPTION
**Pull request by Chibikuri**
Currently, we only can do purification with neighbor nodes.
Basically, we need to do,

- [x] Take resource with partner address
- [x] Make ruleset generator at ConnectionManger
- [x] Check behavior and test it.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)

### CODE REVIEW

**Comment by Chibikuri** [comment]
For simplicity, this PR try to purify just after the entanglement swapping.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.h, line 75 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mf7pGAl3TfJu85ub7Fg:-Mf7pGAm6lcpRXgyaIcd:by9yeg6) ([raw file](https://github.com/sfc-aqua/quisp/blob/f2b4030582107faa4dff24dc80f91b3faf7a5324/quisp/modules/QRSA/ConnectionManager/ConnectionManager.h#L75)):*
> ```objc
>   RuleSet *generateSimultaneousEntanglementSwappingRuleSet(int owner, SwappingConfig conf, std::vector<int> path);
>   RuleSet *generateRGSsourceRuleSet(int owner, int partner, int num_of_measure);
>   RuleSet *generateCombinedRuleSet(int owner_address);
> ```

how about `generateEsAndPurificationRuleSet` ?
the word "combined" describes nothing, so it might confuse us later.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.h, line 75 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mf7pGAl3TfJu85ub7Fg:-Mf7rK8SA__2BJ7FkIDb:b-erkm2q) ([raw file](https://github.com/sfc-aqua/quisp/blob/f2b4030582107faa4dff24dc80f91b3faf7a5324/quisp/modules/QRSA/ConnectionManager/ConnectionManager.h#L75)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

how about `generateEsAndPurificationRuleSet` ?
the word "combined" describes nothing, so it might confuse us later.
</blockquote></details>

That's right. Let me rename it.

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 18 files at r4, 1 of 9 files at r5, 2 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/actions/DoublePurifyAction.cc, line 28 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgZdhPG85lXWwcvRd9E:-MgZdhPG85lXWwcvRd9F:b-6wt9d5) ([raw file](https://github.com/sfc-aqua/quisp/blob/7dafadbd24c9908a33dea7bf9cc181f448aa3225/quisp/rules/actions/DoublePurifyAction.cc#L28)):*
> ```cpp
>   StationaryQubit *trash_qubit_Z, *trash_qubit_X = nullptr;
> 
>   qubit = getResourceFromTopWithPartner(resource, partner);
> ```

I'm so happy that you fix these annoying cased namings!
___
*[quisp/rules/actions/SwappingAction.cc, line 40 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgiJld-7crL5kLei76X:-MgiJld-7crL5kLei76Y:b-ueama7) ([raw file](https://github.com/sfc-aqua/quisp/blob/ad08e93fb285d33d61333de319b7e61d9112c74c/quisp/rules/actions/SwappingAction.cc#L40)):*
> ```cpp
>   StationaryQubit *right_qubit = nullptr;
> 
>   // FIXME: left_resource is misleading name. This is just an index.
> ```

I made an issue for this #257

**Comment by Chibikuri** [comment]
Thanks for commenting. I haven't noticed it. Let me fix that.

**Comment by Chibikuri** [comment]
Note: After the purification, just promoting is really a hassle, when the number of rules is large. 
I'll use this way to fix this issue.
1. After the purification, the resource is back to the bell pair store
2. Record the applied rules to avoid reassign the same rule
3. When the resource allocation, it's checked.

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 5 of 18 files at r4, 3 of 9 files at r5, 3 of 12 files at r7, 7 of 19 files at r8, 18 of 20 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 31 of 36 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/Rule.cc, line 59 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgzCCCD-V4x_UGs4orV:-MgzCCCD-V4x_UGs4orW:by4aswt) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1bcab29b0b35621a95224924baa6e33264bf458/quisp/rules/Rule.cc#L59)):*
> ```cpp
> }
> 
> bool Rule::checkActionPartner(int action_partner){
> ```

the name `checkActionPartner` is ambiguous. I think `bool isActionPartner(int action_partner_addr)` is better.
___
*[quisp/rules/Rule.cc, line 60 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgzCben7Em2qAv-byUg:-MgzCben7Em2qAv-byUh:b-l1r93p) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1bcab29b0b35621a95224924baa6e33264bf458/quisp/rules/Rule.cc#L60)):*
> ```cpp
> 
> bool Rule::checkActionPartner(int action_partner){
>   auto iter = std::find(action_partners.begin(), action_partners.end(), action_partner);
> ```

you don't need to use `std::find`, use `action_partners.find`
you can write like this
```cpp
return action_partners.find(action_partner) != action_partners.end()
```
___
*[quisp/rules/actions/Action.cc, line 44 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgzAyc-3NQDHOFTakgX:-MgzAyc-3NQDHOFTakgY:b-1dfajt) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1bcab29b0b35621a95224924baa6e33264bf458/quisp/rules/actions/Action.cc#L44)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>   for (auto it = (*rule_resources).begin(); it != (*rule_resources).end(); ++it) {
>     if(it->first == partner && !it->second->isLocked()){
>       available_entanglements_with_partner.push_back(it->second);
>     }
>   }
>   // 2. check the index
>   for (int i=0; i<available_entanglements_with_partner.size(); i++){
>     if (i == required_index && !available_entanglements_with_partner.at(i)->isLocked()){
>       pt = available_entanglements_with_partner.at(i);
>     }
>   }
> ```
</details>


you can combine these loops like this.
```cpp
int i = 0;
for (auto it = (*rule_resources).begin(); it != (*rule_resources).end(); ++it) {
    if(it->first == partner && !it->second->isLocked()){
      if (i == required_index)  return it->second;
      i++;
    }
}
return nullptr;

```

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 14 of 38 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/Rule.cc, line 59 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgzCCCD-V4x_UGs4orV:-MhGGfXh2BWECHAiT8Qn:b4wvyxf) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1bcab29b0b35621a95224924baa6e33264bf458/quisp/rules/Rule.cc#L59)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

the name `checkActionPartner` is ambiguous. I think `bool isActionPartner(int action_partner_addr)` is better.
</blockquote></details>

Thanks for your suggestion. I noticed this function is not used right now. So I just remove it here.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 14 of 38 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/actions/Action.cc, line 44 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MgzAyc-3NQDHOFTakgX:-MhGHhpZ983Urm7V2Uh0:bbnfbwo) ([raw file](https://github.com/sfc-aqua/quisp/blob/f1bcab29b0b35621a95224924baa6e33264bf458/quisp/rules/actions/Action.cc#L44)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

> ```
>   for (auto it = (*rule_resources).begin(); it != (*rule_resources).end(); ++it) {
>     if(it->first == partner && !it->second->isLocked()){
>       available_entanglements_with_partner.push_back(it->second);
>     }
>   }
>   // 2. check the index
>   for (int i=0; i<available_entanglements_with_partner.size(); i++){
>     if (i == required_index && !available_entanglements_with_partner.at(i)->isLocked()){
>       pt = available_entanglements_with_partner.at(i);
>     }
>   }
> ```

you can combine these loops like this.
```cpp
int i = 0;
for (auto it = (*rule_resources).begin(); it != (*rule_resources).end(); ++it) {
    if(it->first == partner && !it->second->isLocked()){
      if (i == required_index)  return it->second;
      i++;
    }
}
return nullptr;

```

</blockquote></details>

Oh, right. Thanks for your correction!

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r10, 10 of 11 files at r11, 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 37 of 38 files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 752 at r12](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhGe9d50rgX4vgbJOdL:-MhGe9d50rgX4vgbJOdM:bo1oowa) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e428bb2a26bf155b9097664a1f6cbefbe4908ec/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L752)):*
> ```cpp
> 
> // Rule Generators
> std::unique_ptr<Rule> ConnectionManager::purificationRule(int partner_address, int purification_type, int num_purification, QNIC_type qnic_type, int qnic_index,
> ```

it's better to separate these rule generators into another class later.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 366 at r12](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhGfSrc9PcQzgIswols:-MhGfSrc9PcQzgIswolt:bes9bxv) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e428bb2a26bf155b9097664a1f6cbefbe4908ec/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L366)):*
> ```cpp
>     return;
>   } else {
>     // 2. Check if there are some recodes existed.
> ```

typo: records

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 567 at r12](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhI7U3E57KV8jGTaJlO:-MhI7U3F9u8ixWYA-gi3:bx0abx9) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e428bb2a26bf155b9097664a1f6cbefbe4908ec/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L567)):*
> ```cpp
> 
>           // 3. loop for resources currently assined
>           for (auto qubit_map = (*rule)->resources.begin(); qubit_map != (*rule)->resources.end(); ++qubit_map) {
> ```

when we purify, one stationary qubit will be used, but another qubit is discarded (named `trash_qubit` in the action).
shouldn't we handle it here?  
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 603 at r12](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhI91DT2tsAQ42dLXHp:-MhI91DT2tsAQ42dLXHq:bip7bij) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e428bb2a26bf155b9097664a1f6cbefbe4908ec/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L603)):*
> ```cpp
> bool RuleEngine::checkAppliedRule(IStationaryQubit *qubit, unsigned long rule_id) {
>   // check if the rule can be applied (target rule id is not in the applied rules)
>   bool applicable = false;
> ```

you don't need to use this variable. just return it, not assign it.
https://www.fluentcpp.com/2018/08/24/how-to-design-early-returns-in-c-based-on-procedural-programming/

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 567 at r12](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhI7U3E57KV8jGTaJlO:-MhLxNeP2crOsNMZg3_F:b-aivfqp) ([raw file](https://github.com/sfc-aqua/quisp/blob/1e428bb2a26bf155b9097664a1f6cbefbe4908ec/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L567)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

when we purify, one stationary qubit will be used, but another qubit is discarded (named `trash_qubit` in the action).
shouldn't we handle it here?  
</blockquote></details>

it depends on when these actions are executed. so there might be a timing issue. it's ok to solve it later.

**Review by zigen — COMMENTED** [review]
> Reviewed 3 of 5 files at r13, 1 of 2 files at r14, 5 of 7 files at r15, 2 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 40 of 42 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 37 of 42 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 831 at r17](https://reviewable.io/reviews/sfc-aqua/quisp/250#-MhaubxV2XAQI59z9lMB:-MhaubxW1asVkFEy_oIL:bfj4867) ([raw file](https://github.com/sfc-aqua/quisp/blob/a8a805d6e4d0cdec8e70ad09eacd9fe9b758ebb8/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L831)):*
> ```cpp
> std::unique_ptr<Rule> ConnectionManager::purificationRule(int partner_address, int purification_type, int num_purification, QNIC_type qnic_type, int qnic_index,
>                                                           unsigned long ruleset_id, unsigned long rule_id) {
>   if (num_purification != 1) {
> ```

please run the unit tests before pushing the commits. this change affects the unit tests and you can fix it easily

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 56 of 58 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 570 at r25](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi7c8XK3ahmWCcrNSgE:-Mi9tRxbDu_MAGMrXxQz:b-36k3lm) ([raw file](https://github.com/sfc-aqua/quisp/blob/a52b6c0057ffa4355bbf8607aea6fb9410f91081/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L570)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Ah, right. It's a multimap, but in this case, the record would be a good terminology here. So I'll fix here "qubit_record".
</blockquote></details>

I meant it's an element (corresponding pair of input and output) of the multimap, not a map itself. anyway, qubit_record is the clearer name.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 610 at r25](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi7_zsU7dvnPAAMwalz:-Mi9xJLF8w4ObMt9x63Z:b-xut944) ([raw file](https://github.com/sfc-aqua/quisp/blob/a00e46d69c1e513baa44bf91003acec8ba24355a/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L610)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Yeah, because it's discarded and initialized when it's used again. But to make sure the resource is unlocked, I should put unlock here. Let me use unlock here. 
</blockquote></details>

thanks! I fixed the test too!
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 584 at r26](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi9vCvkBV0vmfG4j1HW:-Mi9vCvkBV0vmfG4j1HX:b-28vtse) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfddd4b6bd04d488e5e630e2e88af0234bdb69d9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L584)):*
> ```cpp
>           }
>         } else if ((*rule)->rule_index == next_rule_id) {
>           (*rule)->addResource(partner_address, qubit);
> ```

here should be put on the other loop. 
current implementation needs the particular order of rules that the "next" rule should be placed after the rule which has the "next_rule_id" field.
later let me fix it. 
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 614 at r26](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi9vI8YCV4XlyfZOUpG:-Mi9vI8YCV4XlyfZOUpH:bp6j7tn) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfddd4b6bd04d488e5e630e2e88af0234bdb69d9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L614)):*
> ```cpp
>       // this rule is already applied
>       return false;
>     } else {
> ```

you don't need the "else" clause after a "return" statement because the function returns a value and stops the execution immediately if a "return" statement comes.
so you can write like this
```cpp
  if (iter == applied_rules.end()) {
    // completely fresh resource
   return true;
  }
  auto rules = applied_rules[qubit];
  auto rule_exists = std::find(rules.begin(), rules.end(), rule_id) != rules.end();
  // if the rule exists, this rule is already applied, so you cannot apply any more.
  // if not, you can go ahead to apply the rule
  return !rule_exists;
```

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 56 of 58 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 584 at r26](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi9vCvkBV0vmfG4j1HW:-MiAiATV-05YY6sMlut7:b-3a5ny5) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfddd4b6bd04d488e5e630e2e88af0234bdb69d9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L584)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

here should be put on the other loop. 
current implementation needs the particular order of rules that the "next" rule should be placed after the rule which has the "next_rule_id" field.
later let me fix it. 
</blockquote></details>

Yeah, I'm assuming the next rule must be placed later than the current rule. 
That would be helpful.
___
*[quisp/modules/QRSA/RuleEngine/RuleEngine.cc, line 614 at r26](https://reviewable.io/reviews/sfc-aqua/quisp/250#-Mi9vI8YCV4XlyfZOUpG:-MiAiXjc6GA55paOMhMz:biahnq1) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfddd4b6bd04d488e5e630e2e88af0234bdb69d9/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L614)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need the "else" clause after a "return" statement because the function returns a value and stops the execution immediately if a "return" statement comes.
so you can write like this
```cpp
  if (iter == applied_rules.end()) {
    // completely fresh resource
   return true;
  }
  auto rules = applied_rules[qubit];
  auto rule_exists = std::find(rules.begin(), rules.end(), rule_id) != rules.end();
  // if the rule exists, this rule is already applied, so you cannot apply any more.
  // if not, you can go ahead to apply the rule
  return !rule_exists;
```
</blockquote></details>

Ah, yeah. Let me fix this.

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 24 files at r24.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: 57 of 58 files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r28.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/250#-:-MiFHS-e8P3_Jcmd0dBB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
