### PR TITLE
Setup devcontainer

### PR DESCRIPTION
**Pull request by zigen**
This PR allows us to use devcontainer in VSCode, so you don't need to set up OMNeT++ anymore.

https://code.visualstudio.com/docs/devcontainers/containers

## steps on local
1. install and run [docker](https://www.docker.com/get-started/) host. you can confirm it by `$ docker ps`
2. open quisp with vscode
3. perform the task "Dev Containers: Rebuild and Reopen in Container"
Screen Shot 2022-11-04 at 15 01 58

## steps on Codespaces
1. open the QuISP repository and switch to this branch
2. create codespace
Screen Shot 2022-11-15 at 13 25 24
3. wait 
Screen Shot 2022-11-15 at 13 29 56
4. go to the ports config menu (it's right next to the terminal tab). From there, temporarily port forward the PORT 6080. Then the Codespace will kindly generate the access url, forwarding to the port we set. Click that and you're good to go.
Screen Shot 2022-11-15 at 13 38 21
Screen Shot 2022-11-15 at 13 38 30

5. go to the VNC tab and send `vscode` for password. then you can see the IDE

6. oepn OMNeT++ IDE by `$ omnetpp` on the integrated terminal

7. set `/workspaces/quisp` for launch and following steps on the [wiki](https://github.com/sfc-aqua/quisp/wiki/Building-QuISP-with-OMNeT-IDE#start-omnet-ide-and-configure-a-workspace-for-quisp) 
Screen Shot 2022-11-15 at 13 41 54

## limitations
* No bash's git-completion.
* With GitHub Codespaces, Building quisp on OMNeT++ IDE will crash the IDE. Build QuISP with GNU Make

## Security Considerations
the codespaces port forwarding is secure, if you want to access to the generated URL, GitHub requires you to authenticate through GitHub. see also https://docs.github.com/ja/codespaces/codespaces-reference/security-in-github-codespaces

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439)

### CODE REVIEW

**Comment by zigen** [comment]
we should add `distclean` into tasks.json

**Review by Naphann — COMMENTED** [review]
The breakpoint in debugging unit test doesn't seem to work. Is it due to this PR or is it something unrelated?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439#-:-NG0OiGa48QzWhuakns3:b12ms5p)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @res6idue and @sierpinskiii)

**Comment by sierpinskiii** [comment]
I reckon we have to mention the fact that some SELinux setup will break the devcontainer.
Currently I'm looking for the ideal SELinux config to work with the devcontainer (since disabling SELinux is usually a bad idea), but I assume for now the `su -c "setenforce 0` workaround would be just fine for testing.

**Review by res6idue — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @sierpinskiii and @zigen)

___
*[`.devcontainer/Dockerfile` line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/439#-NG73vRD65mhhebSgKSW:-NG73vRD65mhhebSgKSX:brxyz3f) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd640bd11bb2b138623b23993bd57ad58a116eb5/.devcontainer/Dockerfile#L1)):*
> ```Dockerfile
> FROM ghcr.io/sfc-aqua/quisp:latest
> ```

I think this image is still on omnetpp-6.0, and is only supported for x86_64. We have to fix this first,

**Review by zigen — COMMENTED** [review]
@sierpinskiii thanks for the mention of SELinux. we should note it on the FAQ page on the wiki 
https://github.com/sfc-aqua/quisp/wiki/FAQ

or any other better way to notify users when they start the devcontainer?

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439#-:-NGKjuoD0XsGx_QtejkQ:b-l9jom7)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @res6idue and @sierpinskiii)

___
*[`.devcontainer/Dockerfile` line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/439#-NG73vRD65mhhebSgKSW:-NGKix-VDJZGk1i4WlN7:bd6e5bh) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd640bd11bb2b138623b23993bd57ad58a116eb5/.devcontainer/Dockerfile#L1)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I think this image is still on omnetpp-6.0, and is only supported for x86_64. We have to fix this first,
</blockquote></details>

yeah. waiting for this PR https://github.com/sfc-aqua/omnetpp-dockerfiles/pull/5

**Comment by sierpinskiii** [comment]
To use noVNC, build the Codespace, and go to the ports config menu (it's right next to the terminal tab). From there, temporarily port forward the PORT 6080. Then the Codespace will kindly generate the access url, forwarding to the port we set. Click that and you're good to go.

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Comment by zigen** [comment]
@Naphann @res6idue @sierpinskiii 
I just cleaned up the PR description. I think it's ready for merge.
could you review it and approve?

**Review by Naphann — APPROVED** [review]
I tested and it works well on my local development. I hope @sierpinskiii or @res6idue will test on GH-codespaces

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439#-:-NG0OuLcEFdaHuny2zqC:b1h6wf1)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @sierpinskiii and @zigen)

**Review by res6idue — APPROVED** [review]
It works well on my local m1 mac and github codespaces.

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439#-:-NGufq5qAI4mYr_8bjuy:b-knkbnj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Review by sierpinskiii — APPROVED** [review]
Tested with Codespaces.
Build time is significantly faster. Also, noVNC works like a charm. LGTM!

**Review by sierpinskiii — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/439#-:-NHEEafJ3TQVtgFWAIDq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
