### PR TITLE
Switchable Backend 2: Connect backend and stationary qubit

### PR DESCRIPTION
**Pull request by zigen**
this PR connects Backend and StationaryQubit.
the goal is that the Backend and StationaryQubit work together properly, so the IQubit class exposes several methods we don't want to expose (e.g. `measureDensityIndependent` or `addErrorX`)

what I did in this PR
* connect backend qubit and StationaryQubit
  * several methods or processes are moved to the Backend (e.g. entangled partner checking)
  * `ICallBack`: Before using simTime in the backend, call back the BackendContainer to take the OMNeT++'s simTime.
* move some StationaryQubit tests to ErrorTrackingQubit tests
* cleanup IStationaryQubit methods and. members

the architecture explanation slide.
https://docs.google.com/presentation/d/1t-wo_MDIwoz0YCN1VynMOnWk9bjo3LQb3BJXx2YNn04/edit#slide=id.g12498dc5cc7_0_3

FYI, I plan to move the graph state stabilizer implementation to the backend like [this commit](https://github.com/sfc-aqua/quisp/commit/6b132233fd4590616841d208a9bec85c4cb91906) later.

This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/388)

### CODE REVIEW

**Review by Naphann — COMMENTED** [review]
Please let me confirm if I understand the goal of this correctly. For now, we want to add all the functionality of current Stationary Qubit to the Qubit/IQubit right? The clean up to remove error tracking methods like `measureDensityIndependent` `addXError`wil be for later PR? 

> Reviewed 1 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/388#-:-N-LozqVAVfiO0svW3FX:bk2161w)* status: 1 of 35 files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by zigen — COMMENTED** [review]
Sorry for the inconvenience. I will describe the goal of this PR and some architecture diagrams to show you how they work

>  For now, we want to add all the functionality of current Stationary Qubit to the Qubit/IQubit right?

yes for now. 

> The clean up to remove error tracking methods like measureDensityIndependent addXErrorwil be for later PR?

if we can, we must move those methods later. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/388#-:-N-R7hf25lu4iBBpDWM2:b-utrql9)* status: 1 of 35 files reviewed, all discussions resolved (waiting on @Chibikuri)

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> Reviewed 18 of 35 files at r1, 5 of 14 files at r2, 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/388)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[`quisp/backends/ErrorTracking/Qubit.cc` line 417 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/388#-N120xqm84UGmIY1vl28:-N120xqm84UGmIY1vl29:bss5hoa) ([raw file](https://github.com/sfc-aqua/quisp/blob/26e4cd8ecd140f4f3ba46549968bd6601c64d9fc/quisp/backends/ErrorTracking/Qubit.cc#L417)):*
> ```cpp
>   et_control_qubit->applyMemoryError();
>   gateCNOT(control_qubit);
>   auto result = correlationMeasureZ() == MeasureZResult::NO_X_ERROR;
> ```

Shouldn't this be correlationMeasureX()?

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/388)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[`quisp/backends/ErrorTracking/Qubit.cc` line 417 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/388#-N120xqm84UGmIY1vl28:-N1DF99rB-XdXhuUfVIN:bvsv01q) ([raw file](https://github.com/sfc-aqua/quisp/blob/26e4cd8ecd140f4f3ba46549968bd6601c64d9fc/quisp/backends/ErrorTracking/Qubit.cc#L417)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Shouldn't this be correlationMeasureX()?
</blockquote></details>

I think it's fine because the `purifyX` checks a bit-flip error. On the contrary, the `purifyZ` checks a phase-flip error by adding a Hadamard gate and measuring it on a Z basis.

**Comment by res6idue** [comment]
Continuing this PR in #388

**Pull request closed without merging**
