### PR TITLE
Use runtime in rule engine

### PR DESCRIPTION
**Pull request by zigen**
After merging #446, I'll set the base branch `master`.
In this PR, 
* use Runtime in RuleEngine
* clean up RuleEngine
* remove ActiveRuleSet
* add RuleSet converter in `quisp::rules` to convert `rules::RuleSet` into `runtime::RuleSet`

This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)

### CODE REVIEW

**Review by Naphann — CHANGES_REQUESTED** [review]
`quisp/modules/QRSA/RuleEngine/QNicRecord/QNicRocord_test.cc` has typo, it should be `Record` not `Rocord`

> Reviewed 104 of 109 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453#-:-NJU2pQPCpIeWKFeAwKt:bzhe2c1)* status: all files reviewed, 9 unresolved discussions (waiting on @sierpinskiii and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 171 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJTraJR8i5f4VccQqKG:-NJTraJR8i5f4VccQqKH:by33i5t) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L171)):*
> ```objc
>   bool outcome_is_plus;
>   char GOD_clean;
>   bool operator==(const measurement_outcome &outcome) const { return basis == outcome.basis && outcome_is_plus == outcome.outcome_is_plus && GOD_clean == outcome.GOD_clean; }
> ```

I'm not sure why we need this here. Where is this used?
___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 974 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJTv5PUDSS6xsmZxCS0:-NJTv5PUDSS6xsmZxCS1:b-p2cpob) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L974)):*
> ```cpp
> 
>     // 1 qubit resource required to perform tomography action
>     auto res_check_clause = std::make_unique<EnoughResourceConditionClause>(1, 0.9, partner_address, qnic_type, qnic_index);
> ```

Where does `0.9` come from? Is it just a placeholder to make current syntax work? Or I'm missing something from the old code?
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 157 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU16wp2O1KjoBUlty4:-NJU16wp2O1KjoBUlty5:b5lkm46) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L157)):*
> ```cpp
>     auto *ruleset = pk->getRuleSet();
>     runtimes.acceptRuleSet(ruleset->construct());
>   } else if (auto *pkt = dynamic_cast<PurificationResult *>(msg)) {
> ```

How about we change `PurificationResult` message to be subclass of `base_message` and then all the various purification protocols just need to subclass this `PurificationResult` again so we can reduce the number of conditions in this if-else block?
___
*[`quisp/rules/RuleSet.h` line 6 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU3qEP3Fpu8WjFTmIA:-NJU3qEP3Fpu8WjFTmIB:b-urts5u) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSet.h#L6)):*
> ```objc
> 
> #include <runtime/RuleSet.h>
> ```

why the space here? Should run clang format?
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 92 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU5eDbDvirUcH5hJ1f:-NJU5eDbDvirUcH5hJ1g:brmsbj7) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L92)):*
> ```cpp
> 
>       /*
>         SET temp_qubit_id -1
> ```

This never gets used in the pseudocode here nor 
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 125 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU61ZO0iiZlvo8BY9J:-NJU61ZO0iiZlvo8BY9K:bpikyfb) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L125)):*
> ```cpp
>     } else if (auto *c = dynamic_cast<const FidelityConditionClause *>(clause_ptr)) {
>       // XXX: no impl in the original
>       name += "FidelityCondition ";
> ```

Since it's not yet implemented, should this throw something?
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 180 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU9E9c-gAnfKjhud9t:-NJU9E9c-gAnfKjhud9u:b-y9vsfo) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L180)):*
> ```cpp
>   /*
>   GET_QUBIT q0 left_partner 0
>   GET_QUBIT q1 right_partner 1
> ```

why do we want `right_partner` at index 1? Shouldn't this be `0`? 
___
*[`quisp/runtime/RuntimeManager.h` line 21 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJUCog14_CdTZGHE4WT:-NJUCog14_CdTZGHE4WU:b5eepq1) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.h#L21)):*
> ```objc
>   std::unique_ptr<Runtime::ICallBack> callback;
> };
> }  // namespace quisp::runtime
> ```

clang-format? 
___
*[`quisp/runtime/RuntimeManager.cc` line 31 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJUCsEe9jZcg8UktJ5Q:-NJUCsEe9jZcg8UktJ5R:bg7om6f) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.cc#L31)):*
> ```cpp
> size_t RuntimeManager::size() const { return runtimes.size(); }
> 
> }  // namespace quisp::runtime
> ```

clang-format?

**Review by Naphann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 7 unresolved discussions (waiting on @sierpinskiii and @zigen)

___
*[`quisp/rules/RuleSet.h` line 6 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU3qEP3Fpu8WjFTmIA:-NJUGLr1DVg_OjED4xKo:bdjk3tf) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSet.h#L6)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

why the space here? Should run clang format?
</blockquote></details>

clang-format doesn't seem to care about this.
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 92 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU5eDbDvirUcH5hJ1f:-NJUGS9f0067nHwh8Xjf:b-df7vpe) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L92)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

This never gets used in the pseudocode here nor 
</blockquote></details>

I forgot to complete the sentence, I mean it's here in the IR comment but not used in either the IR comment or the actual code. Should remove it?

**Review by res6idue — CHANGES_REQUESTED** [review]
> Reviewed 5 of 109 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 8 unresolved discussions (waiting on @sierpinskiii and @zigen)

___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 658 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJp8NVr5PtS30jIkwUR:-NJp8NVr5PtS30jIkwUS:b-pi5ot6) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L658)):*
> ```cpp
>       /// 
>       for (int i = 0; i < num_purification; i++) {
>         // First stage X purification
> ```

Can we move out these X, Z, and other types of purification as individual functions?

**Review by res6idue — COMMENTED** [review]
> Reviewed 9 of 109 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 9 unresolved discussions (waiting on @sierpinskiii and @zigen)

___
*[`quisp/runtime/RuntimeManager.cc` line 21 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJpHKq66kGJfhJThyRl:-NJpHKq66kGJfhJThyRm:b-s9jqgn) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.cc#L21)):*
> ```cpp
> void RuntimeManager::exec() {
>   for (auto &runtime : runtimes) {
>     // how should we delete the runtime and its ruleset?
> ```

Does this comment mean that we currently don't have a way to delete runtimes?

**Review by zigen — COMMENTED** [review]
> Reviewed 11 of 109 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 9 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 171 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJTraJR8i5f4VccQqKG:-NKCKm1z82ARIS4V1_w7:b-5nl3sx) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L171)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I'm not sure why we need this here. Where is this used?
</blockquote></details>

it's for testing.
https://github.com/sfc-aqua/quisp/pull/453/files#diff-de9864942972caa204e01f1851b4c2ac282a40bfb4e58f707f63350952ce7bdcR86
___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 658 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJp8NVr5PtS30jIkwUR:-NKCNFu91Oq3aAuVm0kS:b-yzbr9p) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L658)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Can we move out these X, Z, and other types of purification as individual functions?
</blockquote></details>

I think this `constructPurifyRule` is enough for readability. 
Could you elaborate more like an example pseudo code?



_Suggestion:_
```cpp
 auto rule = constructPurifyRule(rule_name, PurType::SINGLE_X, partner_address, ...
```
___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 974 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJTv5PUDSS6xsmZxCS0:-NKCO3IE65L68O4eq33D:bdn9owb) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L974)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Where does `0.9` come from? Is it just a placeholder to make current syntax work? Or I'm missing something from the old code?
</blockquote></details>

It's just a placeholder for now.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 157 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU16wp2O1KjoBUlty4:-NKCOtaR1_jzDMoP1GRg:bhcqayj) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L157)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

How about we change `PurificationResult` message to be subclass of `base_message` and then all the various purification protocols just need to subclass this `PurificationResult` again so we can reduce the number of conditions in this if-else block?
</blockquote></details>

That's a good idea. I'll fix it.
___
*[`quisp/rules/RuleSet.h` line 6 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU3qEP3Fpu8WjFTmIA:-NJV7HbFCGUWAbkTG873:bwkix9o) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSet.h#L6)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

clang-format doesn't seem to care about this.
</blockquote></details>

It's intentional. I separated the includes whether it is from quisp itself or not.
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 92 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU5eDbDvirUcH5hJ1f:-NKCPCiP2j9mceRglpIr:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L92)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I forgot to complete the sentence, I mean it's here in the IR comment but not used in either the IR comment or the actual code. Should remove it?
</blockquote></details>

Done.
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 125 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU61ZO0iiZlvo8BY9J:-NKCPVZn740zIr6a0yYB:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L125)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Since it's not yet implemented, should this throw something?
</blockquote></details>

Done.
___
*[`quisp/rules/RuleSetConverter/RuleSetConverter.cc` line 180 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU9E9c-gAnfKjhud9t:-NKCPdUJ-Bb6L6z0YuNU:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/rules/RuleSetConverter/RuleSetConverter.cc#L180)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

why do we want `right_partner` at index 1? Shouldn't this be `0`? 
</blockquote></details>

Done.
___
*[`quisp/runtime/RuntimeManager.h` line 21 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJUCog14_CdTZGHE4WT:-NKCPj_Y-NQCRLFaa7NK:b-jasvt1) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.h#L21)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

clang-format? 
</blockquote></details>

The editorconfig extension should treat this.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: 104 of 109 files reviewed, 9 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 157 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJU16wp2O1KjoBUlty4:-NKCVBJN7ciAPvTYBb5J:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L157)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

That's a good idea. I'll fix it.
</blockquote></details>

Done.
___
*[`quisp/runtime/RuntimeManager.cc` line 21 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJpHKq66kGJfhJThyRl:-NKCVDq82AZsWrI9L_fG:b-t8ghm3) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.cc#L21)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Does this comment mean that we currently don't have a way to delete runtimes?
</blockquote></details>

thanks, I forgot to implement it. I'll do it.

**Review by res6idue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: 104 of 109 files reviewed, 8 unresolved discussions (waiting on @Naphann and @sierpinskiii)

___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 658 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJp8NVr5PtS30jIkwUR:-NKDXm3A3Ibkl5wVhg79:b-y499d9) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L658)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think this `constructPurifyRule` is enough for readability. 
Could you elaborate more like an example pseudo code?
</blockquote></details>


I thought it might be better if we could write in the way as the shown c++-like code However, I am not confident if this is a good(or even possible) way.
I will resolve this because after looking back at it this seems quite enough.



_Code snippet:_
```cpp

void x_purification(&rule_name, &rule, &rule_id,&shared_tag,&tomography_RuleSet,"and more?"){
          rule_name = "X purification with: " + std::to_string(partner_address);
          auto rule = constructPurifyRule(rule_name, PurType::SINGLE_X, partner_address, qnic_type, qnic_index, rule_id, shared_tag);
          rule_id++;
          shared_tag++;
          tomography_RuleSet->addRule(std::move(rule));
        }
void double_inv_purification(&rule_name, &rule, &rule_id,&shared_tag,&tomography_RuleSet,"and more?"){
          rule_name = "Double purification Inverse with: " + std::to_string(partner_address);
          rule = constructPurifyRule(rule_name, PurType::DOUBLE_INV, partner_address, qnic_type, qnic_index, rule_id, shared_tag);
          rule_id++;
          shared_tag++;
          tomography_RuleSet->addRule(std::move(rule));
        }
```

**Review by Naphann — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue and @sierpinskiii)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue and @sierpinskiii)

___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 658 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJp8NVr5PtS30jIkwUR:-NKDl8e5EQyAHJvZffT_:bsod55i) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L658)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>


I thought it might be better if we could write in the way as the shown c++-like code However, I am not confident if this is a good(or even possible) way.
I will resolve this because after looking back at it this seems quite enough.
</blockquote></details>

I considered this pattern, but I don't want to pass the states like rule_id and shared_tag as references. And also, these part will be removed by this https://github.com/sfc-aqua/quisp/issues/463

**Review by res6idue — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 1 unresolved discussion (waiting on @sierpinskiii)

**Review by res6idue — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: 105 of 109 files reviewed, all discussions resolved (waiting on @Naphann and @sierpinskiii)

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 1 unresolved discussion (waiting on @sierpinskiii and @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/QNicRecord/QNicRocord_test.cc` line 1 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NKODZC516SfTB5kWtWa:-NKODZC516SfTB5kWtWb:b-822s56) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfc9deafe1de391c5b68e0c76a093eb6c33d8693/quisp/modules/QRSA/RuleEngine/QNicRecord/QNicRocord_test.cc#L1)):*
> ```cpp
> #include <gtest/gtest.h>
> ```

Maybe you didn't check the general comment section, so I'll comment here again.
The file name has a typo. It should be QNICRecord not Rocord.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: 103 of 109 files reviewed, 1 unresolved discussion (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/RuntimeManager.cc` line 21 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NJpHKq66kGJfhJThyRl:-NKQf9ln8u7HIBnw78Ca:bb7f2mf) ([raw file](https://github.com/sfc-aqua/quisp/blob/42be62a86e66e274377a508475bccc4884b8c17f/quisp/runtime/RuntimeManager.cc#L21)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

thanks, I forgot to implement it. I'll do it.
</blockquote></details>

done
___
*[`quisp/modules/QRSA/RuleEngine/QNicRecord/QNicRocord_test.cc` line 1 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/453#-NKODZC516SfTB5kWtWa:-NKQfBQz2xchd-MtfP-c:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/dfc9deafe1de391c5b68e0c76a093eb6c33d8693/quisp/modules/QRSA/RuleEngine/QNicRecord/QNicRocord_test.cc#L1)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Maybe you didn't check the general comment section, so I'll comment here again.
The file name has a typo. It should be QNICRecord not Rocord. 
</blockquote></details>

Done.

**Review by res6idue — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann and @sierpinskiii)

**Review by Naphann — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Review by res6idue — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453#-:-NKRMRt41_InoYqiraae:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Review by zigen — COMMENTED** [review]
@naphann I fixed the typo in the file name. if it's okay, plz give me the LGTM stamp

> Reviewed 2 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453#-:-NKRYjCW0rqqbABf2G14:b7pne4r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Review by Naphann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/453#-:-NKRZAj4DamWTRj2GOSp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii)

**Pull request merged**
