### PR TITLE
Rewrite simulation tests (former e2e-test)

### PR DESCRIPTION
**Pull request by zigen**
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)

### CODE REVIEW

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 10 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/networks/topology_simple_network.ned` line 42 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfDExV1A8811YHGXqW:-NNfDExV1A8811YHGXqX:bsvv0p5) ([raw file](https://github.com/sfc-aqua/quisp/blob/df6cd763b83d030a23fe16793053f615ac50b46c/quisp/networks/topology_simple_network.ned#L42)):*
> ```
> 
> 
> // network Star_MSM
> ```

can we remove these for now and add them later when we write more tests?
___
*[`simulation_tests/utils.py` line 35 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfD0mA4yIkTn_Fodcw:-NNfD0mA4yIkTn_Fodcx:b-vho3n6) ([raw file](https://github.com/sfc-aqua/quisp/blob/df6cd763b83d030a23fe16793053f615ac50b46c/simulation_tests/utils.py#L35)):*
> ```Python
> 
> class WorkerStatus(Enum):
>     WAINTING_FOR_TASK = "Waiting for task"
> ```

typo? Should this be `WAITING_FOR_TASK`?

**Review by zigen — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Naphann and @res6idue)

___
*[`quisp/networks/topology_simple_network.ned` line 42 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfDExV1A8811YHGXqW:-NNfxK9XEwzj34_x0Q-H:bx9c71b) ([raw file](https://github.com/sfc-aqua/quisp/blob/df6cd763b83d030a23fe16793053f615ac50b46c/quisp/networks/topology_simple_network.ned#L42)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

can we remove these for now and add them later when we write more tests?
</blockquote></details>

I added simple MM link. yeah later we can add more networks for testing.
___
*[`simulation_tests/simulation_test.py` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfxoVSA5eaYWyyhH3W:-NNfxoVSA5eaYWyyhH3X:b-u2vpzl) ([raw file](https://github.com/sfc-aqua/quisp/blob/da92b6c9724198e297c87589b0f28b3292c2ff43/simulation_tests/simulation_test.py#L26)):*
> ```Python
>     }
> 
> @pytest.mark.asyncio
> ```

FYI, we can separate this file into several files for more simulation cases later.

**Review by Naphann — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

___
*[`quisp/networks/topology_simple_network.ned` line 42 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfDExV1A8811YHGXqW:-NNfyBrRCD38wdCaMLqE:b-7m74ok) ([raw file](https://github.com/sfc-aqua/quisp/blob/df6cd763b83d030a23fe16793053f615ac50b46c/quisp/networks/topology_simple_network.ned#L42)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I added simple MM link. yeah later we can add more networks for testing.
</blockquote></details>

nice.
___
*[`simulation_tests/simulation_test.py` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfxoVSA5eaYWyyhH3W:-NNfyIaqDGDcPeQz0KHS:b-dhyttx) ([raw file](https://github.com/sfc-aqua/quisp/blob/da92b6c9724198e297c87589b0f28b3292c2ff43/simulation_tests/simulation_test.py#L26)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

FYI, we can separate this file into several files for more simulation cases later.
</blockquote></details>

can you provide examples within this PR by separating the MIM and MM test into two files? I reckon we will populate those two files with more tests real soon.

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: all files reviewed, 2 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`simulation_tests/test_simple_error_case.py` line 9 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNg-oQE9HBW99osrIw4:-NNg-oQE9HBW99osrIw5:b606sr5) ([raw file](https://github.com/sfc-aqua/quisp/blob/8da11f14ee1ccdaa770dbae9ff1e9c2b995b6c8e/simulation_tests/test_simple_error_case.py#L9)):*
> ```Python
>     worker = Worker()
>     await worker.run(
>         config_name="XChannelErrorSimpleMIM",
> ```

Did you forget to push this config? I don't see it in the `simulation_test.ini` file.
___
*[`simulation_tests/test_simple_error_case.py` line 32 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNg-wKD2JXync6Wo5Qv:-NNg-wKD2JXync6Wo5Qw:b-7ikcgd) ([raw file](https://github.com/sfc-aqua/quisp/blob/8da11f14ee1ccdaa770dbae9ff1e9c2b995b6c8e/simulation_tests/test_simple_error_case.py#L32)):*
> ```Python
>     worker = Worker()
>     await worker.run(
>         config_name="XChannelErrorSimpleMM",
> ```

This config as well.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`simulation_tests/test_simple_error_case.py` line 9 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNg-oQE9HBW99osrIw4:-NNg0kpUCn-CdC0uZqeF:bjxeba6) ([raw file](https://github.com/sfc-aqua/quisp/blob/8da11f14ee1ccdaa770dbae9ff1e9c2b995b6c8e/simulation_tests/test_simple_error_case.py#L9)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Did you forget to push this config? I don't see it in the `simulation_test.ini` file.
</blockquote></details>

yeah I forgot...
___
*[`simulation_tests/simulation_test.py` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNfxoVSA5eaYWyyhH3W:-NNg-6Xd4yt15Z_GGkdx:b64b194) ([raw file](https://github.com/sfc-aqua/quisp/blob/da92b6c9724198e297c87589b0f28b3292c2ff43/simulation_tests/simulation_test.py#L26)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

can you provide examples within this PR by separating the MIM and MM test into two files? I reckon we will populate those two files with more tests real soon.
</blockquote></details>

I added one more file and

**Review by Naphann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: all files reviewed, 2 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`simulation_tests/test_simple_error_case.py` line 6 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNgDvcl1RkmiJWLhA2n:-NNgDvcm1-j3aDi4Pp_E:b-17ejvo) ([raw file](https://github.com/sfc-aqua/quisp/blob/44531c40acca209dad02672f68431dfd3895bdea/simulation_tests/test_simple_error_case.py#L6)):*
> ```Python
> 
> @pytest.mark.asyncio
> async def test_NoErrorMIM():
> ```

I think this is a typo, we're testing X error right?
___
*[`simulation_tests/test_simple_error_case.py` line 29 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNgE7VKDhO6wOkjGgh5:-NNgE7VKDhO6wOkjGgh6:b-17ejvo) ([raw file](https://github.com/sfc-aqua/quisp/blob/44531c40acca209dad02672f68431dfd3895bdea/simulation_tests/test_simple_error_case.py#L29)):*
> ```Python
> 
> @pytest.mark.asyncio
> async def test_NoErrorMM():
> ```

I think this is a typo, we're testing X error right?

**Review by res6idue — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 7 of 12 files at r2, 2 of 5 files at r3, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: all files reviewed, 2 unresolved discussions (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`simulation_tests/test_simple_error_case.py` line 6 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNgDvcl1RkmiJWLhA2n:-NNi9enD7wgyri4Q7eqm:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/44531c40acca209dad02672f68431dfd3895bdea/simulation_tests/test_simple_error_case.py#L6)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think this is a typo, we're testing X error right?
</blockquote></details>

Done.
___
*[`simulation_tests/test_simple_error_case.py` line 29 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/485#-NNgE7VKDhO6wOkjGgh5:-NNi9dRqCF6H9jeho1V0:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/44531c40acca209dad02672f68431dfd3895bdea/simulation_tests/test_simple_error_case.py#L29)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think this is a typo, we're testing X error right?
</blockquote></details>

Done.

**Review by Naphann — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Naphann — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485#-:-NNjc2gkArc-hYknVVqj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by res6idue — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by res6idue — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/485#-:-NNjvsCm1mviGQbVPMf5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
