### PR TITLE
RuleSet generation in Connection Manager

### PR DESCRIPTION
**Pull request by Chibikuri**
This PR introduce the RuleSet generation in Connection Manager.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)

### CODE REVIEW

**Comment by Chibikuri** [comment]
Added RuleSet creation functions and field for distribute serialized ruleset in packet.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r2, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 7 of 17 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.h, line 59 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXmmAl1WZa9gNeuX-d:-MxXmmAl1WZa9gNeuX-e:b-vbaopg) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager.h#L59)):*
> ```objc
>   bool es_with_purify;
>   int num_remote_purification;
>   std::string pur_type;
> ```

should be a member? I think it should be a local var in `initialize()`
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 41 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXV1RR40NFTz9MHsIl:-MxXV1RR40NFTz9MHsIm:b6cc4co) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L41)):*
> ```cpp
>     error("Currently, simultaneous entanglement swapping cannot be simulated with purification");
>   }
>   if (pur_type == "SINGLE_X") {
> ```

hmm, these should be a separated static method like `static PurType parsePurType(const string & str) const`

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.h, line 59 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXmmAl1WZa9gNeuX-d:-MxXzF0q6sr5juVc_A8A:b-o419a3) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager.h#L59)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

should be a member? I think it should be a local var in `initialize()`
</blockquote></details>

Right, fixed.
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 41 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXV1RR40NFTz9MHsIl:-MxbmBLS5mpbWmV6FIAm:bc8c9g7) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L41)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

hmm, these should be a separated static method like `static PurType parsePurType(const string & str) const`
</blockquote></details>

OK, I added it

**Review by zigen — CHANGES_REQUESTED** [review]
please remove the hard tabs

> Reviewed 4 of 17 files at r2, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381#-:-MxXtBUg2yMAD1rsqVYs:bhlnqs9)* status: 10 of 18 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 149 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxgvPrh5wAHVsmoAHfo:-MxgvPrh5wAHVsmoAHfp:b-evxyqz) ([raw file](https://github.com/sfc-aqua/quisp/blob/1b815c43054cbae3165dbf6543d9992ba36f5814/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L149)):*
> ```cpp
>   } else {
>     purify_type = PurType::INVALID;
>   }
> ```

please use the early return to make it readable and simple.
you don't need the if-else, just use the if statements.
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_ruleset_test.cc, line 108 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXt9Uk2ZuoGTIaE5a0:-MxXt9Uk2ZuoGTIaE5a1:b-p0gx6s) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager_ruleset_test.cc#L108)):*
> ```cpp
>   json expected = R"({
>           "rule_id": -1,
> 					"next_rule_id": -1,
> ```

remove hard tabs
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 468 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXt4kk92O4uRPicVyS:-MxXt4kk92O4uRPicVyT:b-fgyzl2) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L468)):*
> ```cpp
>         "name": "purification",
> 		    "next_rule_id": 2,
> 		    "partners": [3],
> ```

please remove the hard tab

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 10 of 18 files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 149 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxgvPrh5wAHVsmoAHfo:-MxhBwul7PIpXufdbdvB:b-gubs72) ([raw file](https://github.com/sfc-aqua/quisp/blob/1b815c43054cbae3165dbf6543d9992ba36f5814/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L149)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

please use the early return to make it readable and simple.
you don't need the if-else, just use the if statements.
</blockquote></details>

OK, fixed it.
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_ruleset_test.cc, line 108 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXt9Uk2ZuoGTIaE5a0:-MxhBP9P28BwJ8hhhGBQ:b-659yio) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager_ruleset_test.cc#L108)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

remove hard tabs
</blockquote></details>

Removed and formatted.
___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 468 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxXt4kk92O4uRPicVyS:-MxhBuVQ05IvMaiAISZh:ba3dfob) ([raw file](https://github.com/sfc-aqua/quisp/blob/fa9201aac2912431c6b37aad248c587f8c7625b2/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L468)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

please remove the hard tab
</blockquote></details>

Removed

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3, 2 of 4 files at r4, 1 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/rules/Action.h, line 23 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhVQdcComjuhpcCdCQ:-MxhVQdcComjuhpcCdCR:b9bjzh) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/rules/Action.h#L23)):*
> ```objc
>   DSDA_SECOND,  ///< Different type of Double Selection and Dual Action for both X and Z errors
>   DSDA_SECOND_INV,  ///< Different type of Inverse Double Selection and Dual Action for both X and Z errors
>   INVALID,  ///< Invalid purification type
> ```

we should move this `INVALID` to the first element because int's default value is zero.
so we can notice that we forget to initialize it.
https://stackoverflow.com/questions/6032638/default-variable-value
___
*[quisp/rules/Rule.h, line 28 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhUSC282TcqFujXV_w:-MxhUSC282TcqFujXV_x:b-9mytuw) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/rules/Rule.h#L28)):*
> ```objc
>   int rule_id = -1;
>   int to = -1;
>   bool finalize;
> ```

`finalize` is a verb, so it should be `finalized` or `is_finalized`.

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhXi6J-cZUx_0V41DL:-MxhXi6J-cZUx_0V41DM:b-wommm) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L387)):*
> ```cpp
> 
>     auto expected_ruleset = R"({
>    "ruleset_id":2817478050987672464,
> ```

in my mac, the ruleset_id is `433750096136460660` and the test failed.  how did you define this?

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: all files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhXi6J-cZUx_0V41DL:-MxiI8449CsowY9RkqNZ:bwz1qug) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L387)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

in my mac, the ruleset_id is `433750096136460660` and the test failed.  how did you define this?
</blockquote></details>

Ah, I need to set a seed value here. What do you think is the easiest way of setting seed in source?
___
*[quisp/rules/Action.h, line 23 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhVQdcComjuhpcCdCQ:-MxiDdQpCPmWbE7Hjyp9:b-4wuxg7) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/rules/Action.h#L23)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we should move this `INVALID` to the first element because int's default value is zero.
so we can notice that we forget to initialize it.
https://stackoverflow.com/questions/6032638/default-variable-value
</blockquote></details>

You're right. Fixed it.
___
*[quisp/rules/Rule.h, line 28 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhUSC282TcqFujXV_w:-MxiE4ou21PyedBknuRF:b-u5xjlu) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/rules/Rule.h#L28)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

`finalize` is a verb, so it should be `finalized` or `is_finalized`.
</blockquote></details>

Right, renamed it.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 11 of 18 files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhXi6J-cZUx_0V41DL:-MxiVNU72_DOVqKsjgPr:bhbfwqt) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L387)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Ah, I need to set a seed value here. What do you think is the easiest way of setting seed in source?
</blockquote></details>

I added a seed number in random number generator. What about now?

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhXi6J-cZUx_0V41DL:-MxiVE-cAVW9BRa0PD5e:b-ui69z6) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L387)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I added a seed number in random number generator. What about now?
</blockquote></details>

make `createUniqueId()` virtual and override it. then you can change the id value arbitrarily.
the seed value approach seems fragile because it depends on how you generate the random numbers.

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc, line 387 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/381#-MxhXi6J-cZUx_0V41DL:-My5zGMq0pTbdudgA5ce:b-g6tatn) ([raw file](https://github.com/sfc-aqua/quisp/blob/3b0790e8c66839dc9982e42565e393aa0457738f/quisp/modules/QRSA/ConnectionManager/ConnectionManager_test.cc#L387)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

make `createUniqueId()` virtual and override it. then you can change the id value arbitrarily.
the seed value approach seems fragile because it depends on how you generate the random numbers.
</blockquote></details>

Right, I fixed it.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 38 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/381#-My5zrob2ZOBaZS8AbsM:-My5zrob2ZOBaZS8AbsN:b-q3kjkr) ([raw file](https://github.com/sfc-aqua/quisp/blob/409d8028cc82cc1693ea972288f2a9b60a8af692/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L38)):*
> ```cpp
>   pur_type = pur_type.substr(1, pur_type.size() - 2);
>   threshold_fidelity = par("threshold_fidelity");
>   seed_value = par("seed_cm");
> ```

do we need the seed value?
FYI omnetpp has the configuration for the seed https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:rng-config

**Review by zigen — COMMENTED** [review]
you can merge it after removing the `seed_value`.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381#-:-My6-bF8E-B2m6cfA4D7:b4wawce)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381#-:-My6-jM48PPmQDCJLdOm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/381)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc, line 38 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/381#-My5zrob2ZOBaZS8AbsM:-My61I-21cRHd1UYJ1eP:bqjk7c5) ([raw file](https://github.com/sfc-aqua/quisp/blob/409d8028cc82cc1693ea972288f2a9b60a8af692/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L38)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

do we need the seed value?
FYI omnetpp has the configuration for the seed https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:rng-config
</blockquote></details>

Oh, right. I forgot removing this.

**Pull request merged**
