### PR TITLE
Fix e2e test and enable channel error

### PR DESCRIPTION
**Pull request by res6idue**
This PR combines two significant issues. It fixes the e2e-test, which was not working, and the issue that the channel error was not being simulated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @res6idue)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 346 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NG_sLBm8_1vcrGELkNs:-NG_sLBm8_1vcrGELkNt:brecfdf) ([raw file](https://github.com/sfc-aqua/quisp/blob/8239d40c86a109cb73eb07a311da7e620fad69ab/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L346)):*
> ```cpp
>   updated_time = simTime();  // Should be no error at this time.
>   // GUI part
>   if (hasGUI()) {
> ```

the changes for the StationaryQubit seem outside of the PR.
___
*[`quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc` line 418 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NG_r4lw54qkCFXzMZYP:-NG_r4lw54qkCFXzMZYQ:b-dv40gw) ([raw file](https://github.com/sfc-aqua/quisp/blob/8239d40c86a109cb73eb07a311da7e620fad69ab/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L418)):*
> ```cpp
>                      << "; GOD_Z_pair_total=" << GOD_Z_pair_total << ";}<-->" << partner_node->getFullName() << "; F=" << fidelity << "; X=" << Xerr_rate << "; Z=" << Zerr_rate
>                      << "; Y=" << Yerr_rate << endl;
>     // output to cout, this is a temporary implementation
> ```

it'd be better to note that this part is used for e2e-test
___
*[`quisp/networks/test.ini` line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NG_r_a-Ano1OmOXy6sm:-NG_r_a0DwIXiiADlHt1:b-5zpup3) ([raw file](https://github.com/sfc-aqua/quisp/blob/8239d40c86a109cb73eb07a311da7e620fad69ab/quisp/networks/test.ini#L8)):*
> ```INI
> seed-set = 1   # this is the default =0 results in the same seed every time
> network= Realistic_Layer2_Simple_MIM_MM_5km
> real-time-limit = 20s
> ```

I think we should keep the limit for sim time.
if the simulations get longer, it fails, and if our code is optimized, it needs to wait at least 20sec.
if you need the time limit for simulations, use the GitHub Actions' time limit feature or handle it in the shell script.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @res6idue)

___
*[`test/test_result.py` line 502 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGao8Ml-Q73ogMHFRjB:-NGao8Ml-Q73ogMHFRjC:b-djwk0g) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L502)):*
> ```Python
>         with 3003 purification
>         """
>         test_number = 15  # TEST15
> ```

we don't need these comments...

**Review by zigen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @res6idue)

___
*[`test/test_result.py` line 96 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGaoQ8C7SoyZOVyL6OJ:-NGaoQ8C7SoyZOVyL6OK:b-d1sks7) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L96)):*
> ```Python
>                     self.assertEqual(actual, est)
>                 else:
>                     self.assertAlmostEqual(actual, est, delta=0.05)
> ```

can we reduce the delta? we cannot notice a bug. 
or maybe we still have a bug...

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: all files reviewed, 2 unresolved discussions (waiting on @res6idue)

**Review by zigen — COMMENTED** [review]
you can delete the compile_commands.events.json from the commit by git-rebase.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NGauR2_0PnzUf-v521F:b-rwyh2f)* status: all files reviewed, 2 unresolved discussions (waiting on @res6idue)

**Review by res6idue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[`test/test_result.py` line 96 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGaoQ8C7SoyZOVyL6OJ:-NGauJ9-4SeXpEZIrjl-:b-6kqoce) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L96)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

can we reduce the delta? we cannot notice a bug. 
or maybe we still have a bug...
</blockquote></details>

I don't know what amount of delta we should reduce. For now, what amount should be good?
___
*[`test/test_result.py` line 502 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGao8Ml-Q73ogMHFRjB:-NGauGbv6bFC-Wx47xn5:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L502)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we don't need these comments...
</blockquote></details>

Done.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue)

___
*[`test/test_result.py` line 96 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGaoQ8C7SoyZOVyL6OJ:-NGdMLaY3FdygKzToe-I:bsvqj5c) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L96)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I don't know what amount of delta we should reduce. For now, what amount should be good?
</blockquote></details>

hmm, try to change it and run the test, then we can find the minimum value. or another way is that just skip the test for now and fix it later
https://docs.python.org/ja/3/library/unittest.html#skipping-tests-and-expected-failures

**Review by zigen — COMMENTED** [review]
summary of the test results and the test conditions
```
# # test  Fidelity diff             pur  condition
# test 1  0.025958000000000037      1001 ch_x = 0.5
# test 2  0.014555999999999958      1001 ch_z = 0.5, hom_darkcount = 10e-8 #1%
# test 3  0.0011980000000000324     1001 mem_x = 0.5
# test 4  0.005547000000000024      3003 mem_x 0.5, 3003
# test 5  0.027009000000000005      1001 mem_y = 0.5, hom_darkcount 10e-8
# test 6  0.015167000000000042      1001 mem_z = 0.5, hom_darkcount = 10e-8
# test 7  0.01052900000000001       1031 mem_ex=0.5, hom_darkcount = 10e-8
# test 8  0.0011569999999999636     1001 mem_ex = 0.5
# test 9  0.0037750000000000283     1001 mem_cm = 0.5
# test 10 passed                    2002 hom_loss = 0.5
# test 11 passed                    1221 hom_loss = 0.5
# test 12 passed                    1031 hom_loss = 0.5
# test 13 passed                    1001 hom_loss = 0.5, hom_darkcount = 10e-8
# test 14 0.0006500000000000394     1221 meas = 1/2000, meas_x = 1/3
# test 15 0.0006779999999999564     3003 meas = 1/2000, meas_y = 1/3
# test 16 0.0006329999999999947     3003 meas = 1/2000, meas_z = 1/3
# test 17 passed                    1011 meas = 1/2000, meas_x = 1/3
# test 18 passed                    1011 meas = 1/2000, meas_y = 1/3
# test 19 passed                    1011 meas = 1/2000, meas_z = 1/3
# test 20 passed                    2002 x_gate = 1/2000, x_gate_x = 1/3
# test 21 passed                    2002 x_gate = 1/2000, x_gate_y = 1/3
# test 22 passed                    2002 x_gate = 1/2000, x_gate_z = 1/3
# test 23 passed                    3003 z_gate = 1/2000, z_gate_x = 1/3
# test 24 passed                    3003 z_gate = 1/2000, z_gate_y = 1/3
# test 25 passed                    3003 z_gate = 1/2000, z_gate_z = 1/3
# test 26 passed                    1221 cnot = 1/2000, cnot_iz = 1/9
# test 27 passed                    1221 cnot = 1/2000, cnot_zi = 1/9
# test 28 0.000018000000000073513   1221 cnot = 1/2000, cnot_zz = 1/9
# test 29 0.000026999999999999247   1221 cnot = 1/2000, cnot_ix = 1/9
# test 30 0.000026999999999999247   1221 cnot = 1/2000, cnot_xi = 1/9
# test 31 0.0012020000000000364     1221 cnot = 1/2000, cnot_xx = 1/9
# test 32 0.0011839999999999629     1221 cnot = 1/2000, cnot_iy = 1/9
# test 33 0.0011839999999999629     1221 cnot = 1/2000, cnot_yi = 1/9
# test 34 0.0011839999999999629     1221 cnot = 1/2000, cnot_yy = 1/9
```

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NGdepRF9J-4g3TvjsIa:bqznfhl)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
I added a commit to skip the broken tests. We need to keep the current tests for validation and investigate and fix the broken tests later.

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NGuNKRZ2-4SHbFmPl45:b-4s4ux9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

___
*[`test/test_result.py` line 96 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/442#-NGaoQ8C7SoyZOVyL6OJ:-NGuNaD82NmIL0-xdLQk:bhaas72) ([raw file](https://github.com/sfc-aqua/quisp/blob/2b2c412d1f0da1b9238ee554ff669fa3952a4e72/test/test_result.py#L96)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

hmm, try to change it and run the test, then we can find the minimum value. or another way is that just skip the test for now and fix it later
https://docs.python.org/ja/3/library/unittest.html#skipping-tests-and-expected-failures
</blockquote></details>

I removed the delta. as I posted before, the orders of the fidelity diffs are different, and it means there're different reasons that the tests failed. We should investigate it later in another PR. We might need to change the result value because we changed several invalid behaviors like:
https://github.com/sfc-aqua/quisp/issues/343
https://github.com/sfc-aqua/quisp/issues/337
https://github.com/sfc-aqua/quisp/issues/239
https://github.com/sfc-aqua/quisp/issues/227

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NGuOtoxChpAHxUuvvsc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Comment by zigen** [comment]
Wait, I got the error in e2e-test. the log file size might be a problem.
```
e2e-test An error occurred while provisioning resources (Error Type: Disconnect).
--
[e2e-test](https://github.com/sfc-aqua/quisp/actions/runs/3468661312/jobs/5794726778)
An error occurred while provisioning resources (Error Type: Disconnect).
```

**Review by zigen — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NHDzOeX2_5V1fRBjLTs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Comment by zigen** [comment]
@res6idue could you check this PR? I merged the disabled logger and fix the test.sh

**Review by res6idue — COMMENTED** [review]
Yeah, it is working well for me. But, we need further work for this PR, such as modifying the makefile to make it easy to do the e2e test and output the test log files and tomography files. What should I prioritise now? Should I merge this and think later, or add more commits for convenience?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NHFYyXk3f0qkUPBLADV:b-pmq8hv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Review by zigen — APPROVED** [review]
That'd be nice. But I want to deliver this fix as soon as possible and keep it small. So let's merge it now!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/442#-:-NHFa-K71ORpor1soBLt:b-jv466x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Pull request merged**
