### PR TITLE
Rename Action, Condition, Clause with ActiveAction, ActiveCondition, ActiveClause

### PR DESCRIPTION
**Pull request by Chibikuri**
For the first step for creating a static ruleset, I renamed all `Action`, `Condition`, `Clause` with `ActiveAction`, `ActiveCondition`, `ActiveClause`, and moved them into `./rules/Action/`

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 17 of 70 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)* status: 17 of 70 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/Rule.h, line 16 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrXJlm55lhWijA3_kx:-MsrXJlm55lhWijA3_ky:bwyq06s) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Rule.h#L16)):*
> ```objc
> namespace quisp::rules {
> 
> typedef enum : int {
> ```

please don't use typedef and "plain" enum
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-enum
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rt-using

use enum class
```cpp
enum class PurType: int {
  SingleX,
  SingleZ,
...
};
```
___
*[quisp/rules/Rule.h, line 28 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrYYbx3sdBQSWL4sTG:-MsrYYbx3sdBQSWL4sTH:b-4kp38o) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Rule.h#L28)):*
> ```objc
>   DSDA_inv,  ///< Inverse Double Selection and Dual Action for both X and Z errors
>   DSDA_second,  ///< Different type of Double Selection and Dual Action for both X and Z errors
>   DSDA_inv_second  ///< Different type of Inverse Double Selection and Dual Action for both X and Z errors
> ```

these naming styles are not a CamelCase nor CAPITAL_SNAKE_CASE. we should use a standard naming style like CamelCase or CAPITAL_SNAKE_CASE, e.g. DSDA, DSDA_INV, DSDA_SECOND, or Dsda, DsdaInv, DsdaSecond (Dsda2nd).

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 70 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)* status: 24 of 70 files reviewed, 6 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/rules/RuleSet.h, line 16 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrZGZ14eEiLg2oyrsB:-MsrZGZ14eEiLg2oyrsC:b2hwoy) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/RuleSet.h#L16)):*
> ```objc
> namespace rules {
> 
> using namespace omnetpp;
> ```

do we need this? 
`using namespace` in header file affects the "namespace pollution"

and use `omnetpp::simtime_t started_at;`
___
*[quisp/rules/Active/ActiveAction.h, line 14 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_nBy2ZUnsXkTTXbs:-Msr_nBy2ZUnsXkTTXbt:b-avfaiv) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveAction.h#L14)):*
> ```objc
> 
> namespace quisp {
> namespace rules {
> ```

how about changing new namespace like `namespace quisp::rules::active`
___
*[quisp/rules/Active/ActiveCondition.h, line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_yuh8eRvGglErvst:-Msr_yuh8eRvGglErvsu:b6p6ns2) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveCondition.h#L1)):*
> ```objc
> /** \file Condition.h
> ```

remove it
___
*[quisp/rules/Active/ActiveCondition.cc, line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msra25C2D6OIpUvBPWT:-Msra25C2D6OIpUvBPWU:b6p6ns2) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveCondition.cc#L1)):*
> ```cpp
> /** \file Condition.cc
> ```

remove it

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)* status: 8 of 74 files reviewed, 6 unresolved discussions (waiting on @zigen)

___
*[quisp/rules/Rule.h, line 16 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrXJlm55lhWijA3_kx:-MssBq02APKJBgfMSKz2:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Rule.h#L16)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

please don't use typedef and "plain" enum
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-enum
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rt-using

use enum class
```cpp
enum class PurType: int {
  SingleX,
  SingleZ,
...
};
```
</blockquote></details>

Done.
___
*[quisp/rules/Rule.h, line 28 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrYYbx3sdBQSWL4sTG:-MssBgaXD5wfSjMvL6Y4:b8s45bc) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Rule.h#L28)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

these naming styles are not a CamelCase nor CAPITAL_SNAKE_CASE. we should use a standard naming style like CamelCase or CAPITAL_SNAKE_CASE, e.g. DSDA, DSDA_INV, DSDA_SECOND, or Dsda, DsdaInv, DsdaSecond (Dsda2nd).
</blockquote></details>

Fixed, used CAPITAL_SNAKE_CASE.
___
*[quisp/rules/RuleSet.h, line 16 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-MsrZGZ14eEiLg2oyrsB:-MssBz8r6zUVKs_V4XTj:b-j7uq43) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/RuleSet.h#L16)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

do we need this? 
`using namespace` in header file affects the "namespace pollution"

and use `omnetpp::simtime_t started_at;`
</blockquote></details>

Actually, we don't need it. So I removed it
___
*[quisp/rules/Active/ActiveAction.h, line 14 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_nBy2ZUnsXkTTXbs:-MssCcRZAo8IO6oE5bQs:bo1lc82) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveAction.h#L14)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

how about changing new namespace like `namespace quisp::rules::active`
</blockquote></details>

That would be good. Let me fix it.
___
*[quisp/rules/Active/ActiveCondition.h, line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_yuh8eRvGglErvst:-Msx10OS65J5HolkZn8i:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveCondition.h#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

remove it
</blockquote></details>

Done.
___
*[quisp/rules/Active/ActiveCondition.cc, line 1 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msra25C2D6OIpUvBPWT:-Msx14l_7jtiP8Z5B5-W:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveCondition.cc#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

remove it
</blockquote></details>

Done.

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 70 files at r1, 64 of 64 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)

___
*[quisp/rules/Active/ActiveAction.h, line 14 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_nBy2ZUnsXkTTXbs:-Msx1vRSEdS-j78Y3joG:b-55unye) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveAction.h#L14)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

That would be good. Let me fix it.
</blockquote></details>

good! and one more thing, use `namespace quisp::rules::active` instead of  
```cpp
namespace quisp {
namespace rules {
namespace active {
...
```

we can use this syntax since C++ 17, see item (8) in the page.
https://en.cppreference.com/w/cpp/language/namespace

**Review by Chibikuri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340)* status: 68 of 74 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[quisp/rules/Active/ActiveAction.h, line 14 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/340#-Msr_nBy2ZUnsXkTTXbs:-Msx5STr1ENNKiEdrtB-:b-5vxmfx) ([raw file](https://github.com/sfc-aqua/quisp/blob/37484d7d106a4aae18dad98a7ad58add4931e762/quisp/rules/Active/ActiveAction.h#L14)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

good! and one more thing, use `namespace quisp::rules::active` instead of  
```cpp
namespace quisp {
namespace rules {
namespace active {
...
```

we can use this syntax since C++ 17, see item (8) in the page.
https://en.cppreference.com/w/cpp/language/namespace
</blockquote></details>

Ah, OK. Let me fix it.

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/340#-:-MsxMuAg6AexhBKqiuYc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Pull request merged**
