### PR TITLE
E2e debug

### PR DESCRIPTION
**Pull request by Chibikuri**
Fixed current e2e tomography
Leave `temporal_tomography_output` for the other PR.

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/234)

### CODE REVIEW

**Comment by Chibikuri** [comment]
I don't know why, but if you put `temporal_tomography_output[local_qnic.address][partner_addr]` as a variable, it returns segmentation fault at `finish()`.

**Review by zigen — APPROVED** [review]
hmm, you can found the reason by checking stackframes in your debugger.
does it access to some invalid memory address or something?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/234#-:-Md_tg5N-1vWHMIcDu2L:b-pwoiwg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)

**Comment by Chibikuri** [comment]
Let me check. I only checked it in GUI environment.

**Comment by Chibikuri** [comment]
Hmm, I only got some bug in QuantumChannel, but I'm not sure what was that.
Maybe I'm using the debugger in the wrong way.

**Comment by Chibikuri** [comment]
Ah, now it says "invalid address". Yeah, it's referring wrong address.

**Comment by Chibikuri** [comment]
```
* thread #1, name = 'quisp', stop reason = signal SIGSEGV: invalid address (fault address: 0x9)
    frame #0: 0x00007ffff5fe14e1 libc.so.6`__strlen_avx2 at strlen-avx2.S:65
```
I guess the place where return this error is https://github.com/sfc-aqua/quisp/blob/fb969565b333c3f14fc0a19fe2eb165c7ce9187a/quisp/modules/QRSA/HardwareMonitor/HardwareMonitor.cc#L316
I think when I used the previous one, this basis combination was a single character, with white space. 
I should put this as an issue.

**Comment by zigen** [comment]
we should create a class to manage such nested data like this in next PR.
```cpp
class TomographyResultStore {
  void incrementCount(qnic, partner_address, basis_combination);
  void findResult(qnic, partner_address);
  void saveResult(qnic, partner_address, tomography_data);
};
```

**Comment by zigen** [comment]
basically current out codebase exposes all data structure and their core logic into the module's methods. 
there's no abstraction. so we face these problems again and again.
we should consider proper abstraction to avoid these problems in the future.

**Comment by Chibikuri** [comment]
Right.
Anyway, I should merge this and let's keep this discussion with another issue.
Thank you for your reviews.

**Pull request merged**
