### PR TITLE
update .cproject file to utilize parallel build

### PR DESCRIPTION
**Pull request by Naphann**
In this PR, I update the `.cproject` file to enable parallel building when compiling with OMNeT++ GUI (Eclipse).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/441)

### CODE REVIEW

**Review by zigen — APPROVED** [review]
this configuration works on the release build. could you enable it on debug build either?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/441#-:-NGK9G3a7P8FvXUwp83j:b-93o15e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue and @sierpinskiii)

**Review by Naphann — COMMENTED** [review]
Sure, added! 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/441#-:-NGKyNGOEuEz-qwYa5jB:bnteeup)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @res6idue, @sierpinskiii, and @zigen)

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/441#-:-NGL5l55A3ZmicDANCl1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue and @sierpinskiii)

**Review by sierpinskiii — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/441#-:-NHDLcFh8vWZcgi0yJYc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
