### PR TITLE
Reorganize simulation files

### LINKED ISSUE #122: Aparicio network
This is the network that Lucho used for testing multiplexing schemes.  We should attempt to recreate it, and to replicate the work.

(It's possible that the .ned file still exists somewhere...)
Screenshot 2020-04-17 19 20 32

### PR DESCRIPTION
**Pull request by Naphann**
This PR reorganized file structures. We make it cleaner by separating the definition of ned files and the simulation files (.ini).

Now all `.ini` files are in `/quisp/simulations` directory except the `omnetpp.ini` which is left there to be the default one.

This PR also adds aparicio network definition which closes #122.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464)

### CODE REVIEW

**Review by res6idue — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann, @sierpinskiii, and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/HOMController.cc` line 47 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/464#-NJpMFi0-R3yVobJPLOR:-NJpMFi0-R3yVobJPLOS:bc0n2na) ([raw file](https://github.com/sfc-aqua/quisp/blob/4236f6be417239d6af50e901b2e1b987192ffca9/quisp/modules/PhysicalConnection/BSA/HOMController.cc#L47)):*
> ```cpp
>   accepted_burst_interval = (double)1 / (double)photon_detection_per_sec;
>   auto *generatePacket = new HOMNotificationTimer("BsaStart");
>   scheduleAt(simTime() + par("initial_notification_timing_buffer"), generatePacket);
> ```

shouldn't this par have .doubleValue() ?

**Review by res6idue — COMMENTED** [review]
I think in the current state, we are outputting our json log (which is supposed to go inside simulations/results), and the dm file, and the output file(which has the x,y,z errors and fidelity in it)
I think that we should change where to output those files or modify our .gitignore inside quisp/quisp.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464#-:-NJpXKMh2umZpc58Du8m:bmesw7g)* status: all files reviewed, 1 unresolved discussion (waiting on @Naphann, @sierpinskiii, and @zigen)

**Review by Naphann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue, @sierpinskiii, and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/HOMController.cc` line 47 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/464#-NJpMFi0-R3yVobJPLOR:-NJzUmxC7WsY8296edgm:b-s9oyrc) ([raw file](https://github.com/sfc-aqua/quisp/blob/4236f6be417239d6af50e901b2e1b987192ffca9/quisp/modules/PhysicalConnection/BSA/HOMController.cc#L47)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

shouldn't this par have .doubleValue() ?
</blockquote></details>

I think it's properly coerced to be double. But if we want to be semantically correct, using `.doubleValue()` would be better. If you're okay with this please mark the comment as satisfied.

**Review by res6idue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii and @zigen)

**Review by res6idue — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/464#-:-NJzc6Nd6b7f2bp5dvyV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sierpinskiii and @zigen)

**Pull request merged**
