### PR TITLE
Add StationaryQubit::apply_memory_error test

### PR DESCRIPTION
**Pull request by zigen**
- [x] add StationaryQubit::apply_memory_error test
- [x] refactor StationaryQubit::apply_memory_error test
- [x] add TestRNG to mock random number generator return value 
- [x] clean up useless comments in StationaryQubit
- [x] change test simulation exponential -3 -> -9

see also https://arxiv.org/abs/1908.10758 5.3.1 Noisy memory errors

I renamed  pi(0), pi(1)...pi(6) -> `pi_vector` , \overline{Q} -> `transition_mat`, pi(t) -> `output_vector` in the method
Eq 5.1
\begin{align*}
\vec{\pi}(0) = (
\overset{Clean}{1} \hspace{1em} 
\overset{Xerror}{0} \hspace{1em} 
\overset{Zerror}{0} \hspace{1em} 
\overset{Yerror}{0} \hspace{1em} 
\overset{Excited}{0} \hspace{1em} 
\overset{Relaxed}{0} \hspace{1em} 
\overset{Mixed}{0}
)
\end{align*}

Eq 5.2
\begin{align*}
\bar{Q}=\begin{pmatrix}
(1 - \Sigma_0) & P_X  & P_Z & P_Y & P_E & P_R & 0\\
 P_X  & (1 - \Sigma_1) & P_Y & P_Z & P_E & P_R & 0\\
 P_Z  & P_Y  & (1 - \Sigma_2) & P_X & P_E & P_R & 0\\
 P_Y  & P_Z  & P_X & (1 - \Sigma_3) & P_E & P_R & 0\\
 0 & 0 & 0 & 0 & (1 - \Sigma_4) & P_R & 0\\
 0 & 0 & 0 & 0 & P_E & (1 - \Sigma_5) & 0\\
 0 & 0 & 0 & 0 & P_E &  P_R & (1 - \Sigma_6)\\
\end{pmatrix}
\end{align*}

Eq 5.3
\begin{align*}
\vec{\pi}(t) = \vec{\pi}(0)\overline{Q}^t
\end{align*}

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)

### CODE REVIEW

**Review by zigen — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @Chibikuri, @Naphann, and @ngym)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 665 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-TroV7ep1wsYAG-yK:-Me-TroV7ep1wsYAG-yL:bhxtvmb) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L665)):*
> ```cpp
> 
> // Single qubit memory error based on Markov-Chain
> void StationaryQubit::apply_memory_error(StationaryQubit *qubit) {
> ```

I will remove this `qubit` arg later.

**Review by Naphann — COMMENTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @ngym, and @zigen)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-fWAxE4pVD2zdjoBV:-Me-fWAxE4pVD2zdjoBW:b-9pr1kp) (no related file):*
This looks cleaner! Just a heads up, but there are some errors in the logic of applying memory error itself which is present which should be fixed (or big rewrite) in later PR but I need to recheck the mathematics first.

---
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 683 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-b_v5D0dxtwcMtIow:-Me-b_v5D0dxtwcMtIox:b-wa0gnm) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L683)):*
> ```cpp
>     bool has_x_err = qubit->par("GOD_Xerror");
>     bool has_z_err = qubit->par("GOD_Zerror");
>     bool has_excited_error = qubit->par("GOD_EXerror");
> ```

A little bit about naming, I think `is_excited` `is_relaxed` and `is_completely_mixed` is a better naming meaning-wise. Since these three are non-reversable state.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc, line 87 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-dTKQBdLiOtxbMEYj:-Me-dTKQBdLiOtxbMEYk:bo1yzqr) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc#L87)):*
> ```cpp
> TEST(StationaryQubitMemoryErrorTest, do_nothing) {
>   auto *sim = prepareSimulation();
>   auto *rng = useTestRNG();
> ```

this line triggers warning as it's not used(?)
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc, line 113 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-f4ikA20N_6mYwEmu:-Me-f4ikA20N_6mYwEmv:bo1yzqr) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc#L113)):*
> ```cpp
> TEST(StationaryQubitMemoryErrorTest, update_timestamp) {
>   auto *sim = prepareSimulation();
>   auto *rng = useTestRNG();
> ```

this line triggers warning as it's not used(?)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @Naphann, @ngym, and @zigen)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-fWAxE4pVD2zdjoBV:-Me-lFqy7ysq73W0pmAN:bejep0e) (no related file):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

This looks cleaner! Just a heads up, but there are some errors in the logic of applying memory error itself which is present which should be fixed (or big rewrite) in later PR but I need to recheck the mathematics first.
</blockquote></details>

thanks for reviewing. I asked @ngym (shota nagayama) to check the logic itself. The error model is his field. 
And we need to clean up and confirm the current code deeply before the big fix (rewrite).

---
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 683 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-b_v5D0dxtwcMtIow:-Me-lrlaE4GHNqcKTLOc:b-1dy6q3) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L683)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

A little bit about naming, I think `is_excited` `is_relaxed` and `is_completely_mixed` is a better naming meaning-wise. Since these three are non-reversable state.
</blockquote></details>

that's right. I'll rename it. thanks!
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc, line 87 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-dTKQBdLiOtxbMEYj:-Me-lykN4VqI9w0sdI16:bf811hz) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc#L87)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

this line triggers warning as it's not used(?)
</blockquote></details>

oh, ok, let me fix it.

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @Naphann, @ngym, and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 683 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-b_v5D0dxtwcMtIow:-Me-pCzV5-Pn7FCln90S:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L683)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

that's right. I'll rename it. thanks!
</blockquote></details>

Done.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc, line 87 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-dTKQBdLiOtxbMEYj:-Me-nsQOBpy97deppkEk:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc#L87)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

oh, ok, let me fix it.
</blockquote></details>

Done.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc, line 113 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-f4ikA20N_6mYwEmu:-Me-ntFS-ByXmk7y1bCZ:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/6f2313c2bbdfc48eb644d568db6b5375d55f5999/quisp/modules/QNIC/StationaryQubit/StationaryQubit_memory_error_test.cc#L113)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

this line triggers warning as it's not used(?)
</blockquote></details>

Done.

**Review by Chibikuri — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: all files reviewed, 5 unresolved discussions (waiting on @Naphann, @ngym, and @zigen)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me8U0ip7JcxXm-kkRtY:-Me8U0ip7JcxXm-kkRtZ:bsj099k) (no related file):*
Error transition matrix seems fine. And the test is working on my docker.

---

**Comment by ngym** [comment]
I don't quite understand the background theory of the matrix. X/Y/Z errors should be derived from I/2, like, $p\frac{I}{2} + (1-p)I \rhoI = \frac{p}{3}\{X\rho X + Y\rho Y + Z\rho } + (1-p)I\rho I$, according to the depolarizing model. However, there is I/2 error. It's duplicated. I'll ask kaaki the intention.

**Comment by ngym** [comment]
>Mixed state occurs due to dark counts, or when the paired qubit gets excited/relaxed.
sounds fine. 
>Element PX, PY and PZ correspond to Pauli X, Y and Z error accordingly. PE and PR are memory excitation and relaxation errors, which are used to represent T1 time and the Boltzmann thermal distribution
I have a new question, why T2 is not considered?

**Review by Naphann — COMMENTED** [review]
This is an old error model and is due for an update. I think it's best to not question the current design and check if it is good enough for current use before implementing the updated model. The newer one, Q7 model (I/X/Y/Z/Relaxation/Excitation/Loss), would be better for design discussion and you could discuss that with michal and rod at QuISP meeting.  

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238#-:-MeOZ-gZ0MkeCx-pSu0t:b-iuz4u7)* status: all files reviewed, 2 unresolved discussions (waiting on @ngym and @zigen)

**Review by zigen — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @ngym)

*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me-fWAxE4pVD2zdjoBV:-MeOkEoP9MVxt123-gm6:b-896fix) (no related file):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

thanks for reviewing. I asked @ngym (shota nagayama) to check the logic itself. The error model is his field. 
And we need to clean up and confirm the current code deeply before the big fix (rewrite).
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/sfc-aqua/quisp/238#-Me8U0ip7JcxXm-kkRtY:-MeOkFC0BxKGppo_3AdJ:b-896fix) (no related file):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Error transition matrix seems fine. And the test is working on my docker.
</blockquote></details>

Done.

---

**Comment by zigen** [comment]
okay, let's talk about it tomorrow. I'll consider how to switch the error models.
I want to merge this PR, Are there any problems?

---
@Naphann @Chibikuri 
when you want to just a comment, set "Discussing". the default mode is "Blocking", so we will not overlook any points. if you feel it solved, please set "Satisfied"


スクリーンショット 2021-07-12 17 07 21

スクリーンショット 2021-07-12 17 07 34


and then all problems for the PR solved, click "LGTM" and publish it!


スクリーンショット 2021-07-12 17 11 30

**Review by Naphann — APPROVED** [review]
Oh sorry, I thought I setting it to "comment" already made it not blocking. And I only see "comment/approve/request change" I can't seem to find options in that screenshots. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/238#-:-MeOpHZd-_XNSFBNk_oi:ba9q5hk)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @ngym)

**Pull request merged**
