### PR TITLE
fixed HoM to HOM

### PR DESCRIPTION
**Pull request by res6idue**
Related issue: #373

- - -
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/433)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/433)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue)

___
*[`doc/BSA Node.md` line 19 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/433#-NFv08uR8fV61Hog17tV:-NFv08uSEgl6ygu-zzxy:b-trpehi) ([raw file](https://github.com/sfc-aqua/quisp/blob/544eb527bae91363cf280376cd709ef63eebe1d8/doc/BSA%20Node.md#L19)):*
> ```Markdown
> 
> There are two main ways, with or without hand-shake, to distribute entangled pairs using a stand-alone or an internal BSA.
> Slides explaining those with figures can be found [slides](HOMProtocol.pptx).
> ```

then you should also rename this https://github.com/sfc-aqua/quisp/blob/master/doc/HoMProtocol.pptx

**Comment by res6idue** [comment]
Should I also edit the slide itself? If so, should I also change the images inside it?

**Review by zigen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/433#-:-NFvwrsv2RuRIU6MWcbn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)

**Comment by res6idue** [comment]
close #373

**Pull request merged**
