### PR TITLE
Switchable backend 1: Copy ErrorTrackingQubit impl to quisp/backends

### PR DESCRIPTION
**Pull request by zigen**
* create interfaces: IQuantumBackend, IQubit, IQubitId
* implement BackendContainer module
* copy ErrorTrackingQubit Implementation from `quisp::modules::StationaryQubit `to `quisp::backends::error_tracking`
* not connected StationaryQubit and QuantumBackend

in the next PR, StationaryQubit uses QuantumBackend
#375 
memo: https://docs.google.com/presentation/d/1t-wo_MDIwoz0YCN1VynMOnWk9bjo3LQb3BJXx2YNn04/edit#slide=id.p

---
This change is [Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)

### CODE REVIEW

**Review by Chibikuri — COMMENTED** [review]
> Reviewed 5 of 34 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: 6 of 42 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/backends/Backends.h, line 12 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My61vFG8NUdPt10l0XQ:-My61vFH-22-UlDVuSzp:bsvi0ka) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/Backends.h#L12)):*
> ```objc
> using abstract::IQubit;
> using abstract::IQubitId;
> using error_tracking::ErrorTrackingBackend;
> ```

Actually, we call this method "error basis". "error-tracking" should also be fine, but just in case. 
___
*[quisp/backends/ErrorTracking/Backend.cc, line 19 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My66tRv8pVcscpDZceQ:-My66tRv8pVcscpDZceR:b9it1up) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/ErrorTracking/Backend.cc#L19)):*
> ```cpp
>     return qubit->second.get();
>   }
>   auto original_qubit = std::make_unique<ErrorTrackingQubit>(id, this);
> ```

Don't we need to check the number of available qubits here?

**Review by zigen — COMMENTED** [review]
> Reviewed 2 of 34 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: 6 of 42 files reviewed, 2 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/backends/Backends.h, line 12 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My61vFG8NUdPt10l0XQ:-My7013r8mmAT6mUqsvW:bra7p3d) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/Backends.h#L12)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Actually, we call this method "error basis". "error-tracking" should also be fine, but just in case. 
</blockquote></details>

ah okay, thanks.
___
*[quisp/backends/ErrorTracking/Backend.cc, line 19 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My66tRv8pVcscpDZceQ:-My7-Q8WBv9qrsZpz7HQ:b-5bbf60) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/ErrorTracking/Backend.cc#L19)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Don't we need to check the number of available qubits here?
</blockquote></details>

the backend is a kind of singleton in a network. so the backend shouldn't know the number of available qubits.
a QNIC module should be responsible for the number of available qubits.

**Review by Chibikuri — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1, 26 of 34 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: all files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[quisp/backends/ErrorTracking/Backend.cc, line 19 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My66tRv8pVcscpDZceQ:-MyA6nOx-JwtrVRMp5ro:b-mzse4n) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/ErrorTracking/Backend.cc#L19)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

the backend is a kind of singleton in a network. so the backend shouldn't know the number of available qubits.
a QNIC module should be responsible for the number of available qubits. 
</blockquote></details>

Ah, ok. I think I get it now.
___
*[quisp/backends/interfaces/IQubit.h, line 20 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyI8v3n2nNIJylxTurO:-MyI8v3n2nNIJylxTurP:b8qdmoe) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/interfaces/IQubit.h#L20)):*
> ```objc
>   // two qubit operations
>   virtual void gateCNOT(IQubit *const control_qubit) { throw std::runtime_error("gateCNOT not implemented"); };
>   virtual void gateCZ(IQubit *const anoter) { throw std::runtime_error("gateCZ not implemented"); };
> ```

Argument "anoter" (maybe another?) can be "control_qubit" the same as the CNOT.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 111 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyIC0kM-yk9I4BSpqBx:-MyIC0kM-yk9I4BSpqBy:b-tq1v8s) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L111)):*
> ```cpp
> 
>   auto *backend = provider.getQuantumBackend();
>   // qubit_ref = backend->getQubit({node_address, qnic_index, qnic_type, stationaryQubit_address});
> ```

Is this for later use?

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri)

___
*[quisp/backends/ErrorTracking/Backend.cc, line 19 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-My66tRv8pVcscpDZceQ:-MykPvikCTnQPVvtwYV1:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/ErrorTracking/Backend.cc#L19)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Ah, ok. I think I get it now.
</blockquote></details>

Done.
___
*[quisp/backends/interfaces/IQubit.h, line 20 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyI8v3n2nNIJylxTurO:-MykQ71DAIyOlTCRbMjF:b68z1ak) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/interfaces/IQubit.h#L20)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Argument "anoter" (maybe another?) can be "control_qubit" the same as the CNOT.
</blockquote></details>

it must be a typo. thanks. 

CZ is a symmetric gate so I chose "another", not "control_qubit". should I use "control_qubit" even though?
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 111 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyIC0kM-yk9I4BSpqBx:-MykQccvBAYNfdT5u9Cg:b-cpvlkq) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L111)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is this for later use?
</blockquote></details>

yes, for later use.
https://github.com/sfc-aqua/quisp/pull/388/files#diff-8adaef17c366fdb119380ef6d0e51335ec531a0d5d194df22c9fafbef48ac031R62

**Review by Chibikuri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/backends/interfaces/IQubit.h, line 20 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyI8v3n2nNIJylxTurO:-Myom3XtC3TqaJTmNT_h:bpbtlv8) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/interfaces/IQubit.h#L20)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it must be a typo. thanks. 

CZ is a symmetric gate so I chose "another", not "control_qubit". should I use "control_qubit" even though?
</blockquote></details>

Right, CZ is symmetric, but for me "control_qubit" sounds more natural. Qiskit used CZ with control qubit. 
We can discuss this later on, so for now, it's fine. 
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc, line 111 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyIC0kM-yk9I4BSpqBx:-MyomQSUB8BCX7HoBDap:b32w0x) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L111)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

yes, for later use.
https://github.com/sfc-aqua/quisp/pull/388/files#diff-8adaef17c366fdb119380ef6d0e51335ec531a0d5d194df22c9fafbef48ac031R62
</blockquote></details>

OK

**Review by Chibikuri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

___
*[quisp/backends/interfaces/IQubit.h, line 20 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/382#-MyI8v3n2nNIJylxTurO:-MyomvOtCz2oPOVZaudq:b-kkh8kf) ([raw file](https://github.com/sfc-aqua/quisp/blob/13046baec0cb8d71344b647e387abb90beb157bc/quisp/backends/interfaces/IQubit.h#L20)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Right, CZ is symmetric, but for me "control_qubit" sounds more natural. Qiskit used CZ with control qubit. 
We can discuss this later on, so for now, it's fine. 
</blockquote></details>

hmm, let's align to the qiskit's way for now.
everyone knows it's symmetric

**Review by Chibikuri — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by zigen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Review by Chibikuri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/382#-:-MyqlG9E1TRn3Olb08Ho:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zigen)

**Pull request merged**
